begin;

select plan(51);

select is((select count(*) from information_schema.tables where table_schema = 'app' and table_name in ('educational_brands','app_users','brand_memberships','student_profiles','admin_profiles','admin_permissions','admin_roles','admin_role_permissions','platform_admin_role_assignments','admin_command_receipts','admin_audit_events')), 11::bigint, 'Exactly eleven M1 and M4A-owned tables exist after M4A.');
select is((select count(*) from information_schema.tables where table_schema = 'app' and table_name in ('admin_command_receipts', 'admin_audit_events')), 2::bigint, 'Exactly two M4A tables exist.');
select is((select count(*) from app.admin_command_receipts), 0::bigint, 'No command receipt is seeded.');
select is((select count(*) from app.admin_audit_events), 0::bigint, 'No audit event is seeded.');
select is((select count(*) from pg_policies where schemaname = 'app'), 0::bigint, 'M4A adds no RLS policy.');
select is((select count(*) from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'app' and p.prosecdef), 0::bigint, 'M4A adds no SECURITY DEFINER function.');
select is((select count(*) from (values ('public'), ('anon'), ('authenticated')) r(role_name) cross join (values ('app.admin_command_receipts'), ('app.admin_audit_events')) t(table_name) cross join (values ('select'), ('insert'), ('update'), ('delete'), ('truncate'), ('references'), ('trigger')) p(privilege_name) where has_table_privilege(r.role_name, t.table_name, p.privilege_name)), 0::bigint, 'Client roles have no M4A table privileges.');
select is((select count(*) from (values ('public'), ('anon'), ('authenticated')) r(role_name) cross join (values ('app.reject_m4a_immutable_change()'::regprocedure), ('app.enforce_admin_audit_receipt_consistency()'::regprocedure)) f(function_oid) where has_function_privilege(r.role_name, f.function_oid, 'execute')), 0::bigint, 'Client roles have no M4A helper execution privilege.');
select is((select count(*) from pg_constraint fk join pg_class c on c.oid = fk.conrelid join pg_namespace n on n.oid = c.relnamespace where n.nspname = 'app' and fk.contype = 'f' and c.relname in ('educational_brands','app_users','brand_memberships','student_profiles','admin_profiles','admin_permissions','admin_roles','admin_role_permissions','platform_admin_role_assignments','admin_command_receipts','admin_audit_events')), 16::bigint, 'M1 and M4A-owned tables contain sixteen foreign keys.');
select is((with fk as (select c.conrelid, c.conkey from pg_constraint c join pg_namespace n on n.oid = c.connamespace where c.contype = 'f' and n.nspname = 'app'), uncovered as (select 1 from fk f where not exists (select 1 from pg_index i where i.indrelid = f.conrelid and i.indisvalid and i.indisready and ((i.indpred is null) or pg_get_expr(i.indpred, i.indrelid) = '(assigned_by_admin_profile_id IS NOT NULL)') and array(select k.attnum::smallint from unnest(i.indkey) with ordinality k(attnum, ordinality) where k.ordinality <= array_length(f.conkey, 1) order by k.ordinality) = f.conkey)) select count(*) from uncovered), 0::bigint, 'Every M1 and M4A foreign key has an ordered child-side index.');

insert into app.educational_brands (id, code, name, slug) values ('00000000-0000-4000-8000-000000000101', 'test-brand', 'Test Brand', 'test-brand');
insert into app.app_users (id, auth_user_id, status) values ('00000000-0000-4000-8000-000000000201', '00000000-0000-4000-8000-000000000211', 'active');
insert into app.admin_profiles (id, app_user_id, status) values ('00000000-0000-4000-8000-000000000301', '00000000-0000-4000-8000-000000000201', 'active');
insert into app.educational_brands (id, code, name, slug) values ('00000000-0000-4000-8000-000000000102', 'test-brand-2', 'Test Brand Two', 'test-brand-2');
insert into app.app_users (id, auth_user_id, status) values ('00000000-0000-4000-8000-000000000202', '00000000-0000-4000-8000-000000000212', 'active');
insert into app.admin_profiles (id, app_user_id, status) select '00000000-0000-4000-8000-000000000302', u.id, 'active' from app.app_users u where u.id = '00000000-0000-4000-8000-000000000202' and not exists (select 1 from app.admin_profiles ap where ap.app_user_id = u.id);

insert into app.admin_command_receipts (actor_admin_profile_id, scope_kind, brand_id, command_name, target_type, target_id, idempotency_key, request_fingerprint, correlation_id, outcome, result_summary)
select ap.id, 'brand', b.id, 'admin.brand.update', 'educational_brand', b.id, 'command-001', repeat('a', 64), 'correlation-001', 'succeeded', '{"version":1}'::jsonb from app.admin_profiles ap cross join app.educational_brands b where ap.id = '00000000-0000-4000-8000-000000000301' and b.code = 'test-brand';
select is((select count(*) from app.admin_command_receipts), 1::bigint, 'A succeeded brand command receipt is accepted.');
select throws_ok($$insert into app.admin_command_receipts (actor_admin_profile_id, scope_kind, brand_id, command_name, target_type, target_id, idempotency_key, request_fingerprint, outcome) select ap.id, 'brand', b.id, 'admin.brand.update', 'educational_brand', b.id, 'command-001', repeat('b', 64), 'succeeded' from app.admin_profiles ap cross join app.educational_brands b where ap.id='00000000-0000-4000-8000-000000000301' and b.code='test-brand'$$, '23505', null, 'Actor idempotency key is unique.');
select throws_ok($$insert into app.admin_command_receipts (actor_admin_profile_id, scope_kind, command_name, target_type, target_id, idempotency_key, request_fingerprint, outcome) select ap.id, 'brand', 'admin.brand.update', 'educational_brand', b.id, 'command-002', repeat('c', 64), 'succeeded' from app.admin_profiles ap cross join app.educational_brands b where ap.id='00000000-0000-4000-8000-000000000301' and b.code='test-brand'$$, '23514', null, 'Brand receipt requires an explicit brand.');
select throws_ok($$insert into app.admin_command_receipts (actor_admin_profile_id, scope_kind, brand_id, command_name, target_type, target_id, idempotency_key, request_fingerprint, outcome) select ap.id, 'global', b.id, 'admin.global.update', 'global_target', b.id, 'command-003', repeat('d', 64), 'succeeded' from app.admin_profiles ap cross join app.educational_brands b where ap.id='00000000-0000-4000-8000-000000000301' and b.code='test-brand'$$, '23514', null, 'Global receipt cannot carry a brand.');
select throws_ok($$insert into app.admin_command_receipts (actor_admin_profile_id, scope_kind, brand_id, command_name, target_type, target_id, idempotency_key, request_fingerprint, outcome) select ap.id, 'brand', b.id, 'admin.brand.update', 'educational_brand', b.id, 'command-004', repeat('A', 64), 'succeeded' from app.admin_profiles ap cross join app.educational_brands b where ap.id='00000000-0000-4000-8000-000000000301' and b.code='test-brand'$$, '23514', null, 'Fingerprint must be lowercase hexadecimal.');
select throws_ok($$insert into app.admin_command_receipts (actor_admin_profile_id, scope_kind, brand_id, command_name, target_type, target_id, idempotency_key, request_fingerprint, outcome, result_summary) select ap.id, 'brand', b.id, 'admin.brand.update', 'educational_brand', b.id, 'command-005', repeat('e', 64), 'succeeded', '[]'::jsonb from app.admin_profiles ap cross join app.educational_brands b where ap.id='00000000-0000-4000-8000-000000000301' and b.code='test-brand'$$, '23514', null, 'Receipt summary must be a bounded JSON object.');

insert into app.admin_audit_events (receipt_id, actor_admin_profile_id, scope_kind, brand_id, command_name, target_type, target_id, reason, before_summary, after_summary, metadata)
select r.id, r.actor_admin_profile_id, r.scope_kind, r.brand_id, r.command_name, r.target_type, r.target_id, 'Approved correction', '{"version":1}'::jsonb, '{"version":1}'::jsonb, '{"version":1}'::jsonb from app.admin_command_receipts r where r.idempotency_key = 'command-001';
select is((select count(*) from app.admin_audit_events), 1::bigint, 'One matching audit event is accepted for a succeeded receipt.');
select throws_ok($$insert into app.admin_audit_events (receipt_id, actor_admin_profile_id, scope_kind, brand_id, command_name, target_type, target_id, reason) select r.id, r.actor_admin_profile_id, r.scope_kind, r.brand_id, r.command_name, r.target_type, r.target_id, 'Duplicate evidence' from app.admin_command_receipts r where r.idempotency_key = 'command-001'$$, '23505', null, 'A receipt has at most one audit event.');
select throws_ok($$insert into app.admin_audit_events (receipt_id, actor_admin_profile_id, scope_kind, brand_id, command_name, target_type, target_id, reason) select r.id, r.actor_admin_profile_id, r.scope_kind, r.brand_id, 'admin.other.update', r.target_type, r.target_id, 'Wrong command' from app.admin_command_receipts r where r.idempotency_key = 'command-001'$$, '23514', 'Audit event must match one succeeded command receipt.', 'Audit command must match its receipt.');
select throws_ok($$insert into app.admin_audit_events (receipt_id, actor_admin_profile_id, scope_kind, brand_id, command_name, target_type, target_id, reason) select r.id, r.actor_admin_profile_id, r.scope_kind, r.brand_id, r.command_name, r.target_type, r.target_id, '   ' from app.admin_command_receipts r where r.idempotency_key = 'command-001'$$, '23514', null, 'Audit reason must be nonblank.');
select throws_ok($$insert into app.admin_audit_events (receipt_id, actor_admin_profile_id, scope_kind, brand_id, command_name, target_type, target_id, reason, metadata) select r.id, r.actor_admin_profile_id, r.scope_kind, r.brand_id, r.command_name, r.target_type, r.target_id, 'Array metadata', '[]'::jsonb from app.admin_command_receipts r where r.idempotency_key = 'command-001'$$, '23514', null, 'Audit metadata must be a bounded JSON object.');

insert into app.admin_command_receipts (actor_admin_profile_id, scope_kind, command_name, target_type, target_id, idempotency_key, request_fingerprint, outcome)
select id, 'global', 'admin.global.replay', 'global_target', gen_random_uuid(), 'command-006', repeat('f', 64), 'replayed' from app.admin_profiles where id='00000000-0000-4000-8000-000000000301';
select throws_ok($$insert into app.admin_audit_events (receipt_id, actor_admin_profile_id, scope_kind, command_name, target_type, target_id, reason) select r.id, r.actor_admin_profile_id, r.scope_kind, r.command_name, r.target_type, r.target_id, 'Replay has no event' from app.admin_command_receipts r where r.idempotency_key = 'command-006'$$, '23514', 'Audit event must match one succeeded command receipt.', 'Replay receipt cannot receive an audit event.');
select throws_ok($$update app.admin_command_receipts set outcome = 'replayed' where idempotency_key = 'command-001'$$, '55000', 'M4A command receipts and audit events are immutable.', 'Receipt update is rejected.');
select throws_ok($$delete from app.admin_command_receipts where idempotency_key = 'command-001'$$, '55000', 'M4A command receipts and audit events are immutable.', 'Receipt delete is rejected.');
select throws_ok($$update app.admin_audit_events set reason = 'Changed'$$, '55000', 'M4A command receipts and audit events are immutable.', 'Audit update is rejected.');
select throws_ok($$delete from app.admin_audit_events$$, '55000', 'M4A command receipts and audit events are immutable.', 'Audit delete is rejected.');

select is((select count(*) from pg_trigger t join pg_class c on c.oid = t.tgrelid join pg_namespace n on n.oid = c.relnamespace where n.nspname = 'app' and not t.tgisinternal and c.relname in ('admin_command_receipts', 'admin_audit_events')), 3::bigint, 'M4A has only the two immutability and one consistency triggers.');
select is((select count(*) from app.admin_command_receipts where outcome = 'succeeded'), 1::bigint, 'The successful command has exactly one receipt.');
select is((select count(*) from app.admin_audit_events where reason = 'Approved correction'), 1::bigint, 'The successful command has exactly one audit event.');

insert into app.admin_command_receipts (actor_admin_profile_id, scope_kind, command_name, target_type, target_id, idempotency_key, request_fingerprint, correlation_id, outcome, result_summary) select id, 'global', 'admin.global.create', 'global_target', gen_random_uuid(), 'command-global', repeat('1',64), 'correlation-global', 'succeeded', '{}'::jsonb from app.admin_profiles where id='00000000-0000-4000-8000-000000000301';
select is((select count(*) from app.admin_command_receipts where idempotency_key = 'command-global'), 1::bigint, 'Valid global receipt is accepted.');
insert into app.admin_command_receipts (actor_admin_profile_id, scope_kind, command_name, target_type, target_id, idempotency_key, request_fingerprint, outcome, result_summary) select id, 'shared', 'admin.shared.create', 'shared_target', gen_random_uuid(), 'command-shared', repeat('2',64), 'succeeded', '{"version":1}'::jsonb from app.admin_profiles where id='00000000-0000-4000-8000-000000000301';
select is((select count(*) from app.admin_command_receipts where idempotency_key = 'command-shared'), 1::bigint, 'Valid shared receipt is accepted.');
select throws_ok($$insert into app.admin_command_receipts (actor_admin_profile_id,scope_kind,command_name,target_type,target_id,idempotency_key,request_fingerprint,outcome) select id,'invalid','admin.x','target',gen_random_uuid(),'command-invalid-scope',repeat('3',64),'succeeded' from app.admin_profiles where id='00000000-0000-4000-8000-000000000301'$$,'23514',null,'Unknown receipt scope is rejected.');
select throws_ok($$insert into app.admin_command_receipts (actor_admin_profile_id,scope_kind,command_name,target_type,target_id,idempotency_key,request_fingerprint,outcome) select id,'global','admin.x','target',gen_random_uuid(),'command-invalid-outcome',repeat('4',64),'invalid' from app.admin_profiles where id='00000000-0000-4000-8000-000000000301'$$,'23514',null,'Unknown receipt outcome is rejected.');
select throws_ok($$insert into app.admin_command_receipts (actor_admin_profile_id,scope_kind,brand_id,command_name,target_type,target_id,idempotency_key,request_fingerprint,outcome) select ap.id,'shared',b.id,'admin.x','target',b.id,'command-shared-brand',repeat('5',64),'succeeded' from app.admin_profiles ap cross join app.educational_brands b where ap.id='00000000-0000-4000-8000-000000000301' and b.code='test-brand'$$,'23514',null,'Shared receipt cannot carry a brand.');
select throws_ok($$insert into app.admin_command_receipts (actor_admin_profile_id,scope_kind,command_name,target_type,target_id,idempotency_key,request_fingerprint,outcome) select id,'global','   ','target',gen_random_uuid(),'command-blank-command',repeat('6',64),'succeeded' from app.admin_profiles where id='00000000-0000-4000-8000-000000000301'$$,'23514',null,'Blank receipt command is rejected.');
select throws_ok($$insert into app.admin_command_receipts (actor_admin_profile_id,scope_kind,command_name,target_type,target_id,idempotency_key,request_fingerprint,outcome) select id,'global','admin.x','   ',gen_random_uuid(),'command-blank-target',repeat('7',64),'succeeded' from app.admin_profiles where id='00000000-0000-4000-8000-000000000301'$$,'23514',null,'Blank receipt target type is rejected.');
select throws_ok($$insert into app.admin_command_receipts (actor_admin_profile_id,scope_kind,command_name,target_type,target_id,idempotency_key,request_fingerprint,outcome) select id,'global','admin.x','target',gen_random_uuid(),'   ',repeat('8',64),'succeeded' from app.admin_profiles where id='00000000-0000-4000-8000-000000000301'$$,'23514',null,'Blank receipt idempotency key is rejected.');
select throws_ok($$insert into app.admin_command_receipts (actor_admin_profile_id,scope_kind,command_name,target_type,target_id,idempotency_key,request_fingerprint,correlation_id,outcome) select id,'global','admin.x','target',gen_random_uuid(),'command-blank-correlation',repeat('9',64),'   ','succeeded' from app.admin_profiles where id='00000000-0000-4000-8000-000000000301'$$,'23514',null,'Blank receipt correlation identifier is rejected.');
select throws_ok($$insert into app.admin_command_receipts (actor_admin_profile_id,scope_kind,command_name,target_type,target_id,idempotency_key,request_fingerprint,outcome) select id,'global','admin.x','target',gen_random_uuid(),'command-short-fingerprint',repeat('a',63),'succeeded' from app.admin_profiles where id='00000000-0000-4000-8000-000000000301'$$,'23514',null,'Short fingerprint is rejected.');
select throws_ok($$insert into app.admin_command_receipts (actor_admin_profile_id,scope_kind,command_name,target_type,target_id,idempotency_key,request_fingerprint,outcome) select id,'global','admin.x','target',gen_random_uuid(),'command-nonhex-fingerprint',repeat('a',63)||'g','succeeded' from app.admin_profiles where id='00000000-0000-4000-8000-000000000301'$$,'23514',null,'Non-hex fingerprint is rejected.');
select throws_ok($$insert into app.admin_command_receipts (actor_admin_profile_id,scope_kind,command_name,target_type,target_id,idempotency_key,request_fingerprint,outcome,result_summary) select id,'global','admin.x','target',gen_random_uuid(),'command-scalar-summary',repeat('b',64),'succeeded','1'::jsonb from app.admin_profiles where id='00000000-0000-4000-8000-000000000301'$$,'23514',null,'Scalar receipt summary is rejected.');
select throws_ok($$insert into app.admin_command_receipts (actor_admin_profile_id,scope_kind,command_name,target_type,target_id,idempotency_key,request_fingerprint,outcome,result_summary) select id,'global','admin.x','target',gen_random_uuid(),'command-large-summary',repeat('c',64),'succeeded',jsonb_build_object('x',repeat('x',32769)) from app.admin_profiles where id='00000000-0000-4000-8000-000000000301'$$,'23514',null,'Oversized receipt summary is rejected.');
select throws_ok($$insert into app.admin_audit_events (receipt_id,actor_admin_profile_id,scope_kind,brand_id,command_name,target_type,target_id,reason) select r.id,ap.id,r.scope_kind,r.brand_id,r.command_name,r.target_type,r.target_id,'Actor mismatch' from app.admin_command_receipts r cross join app.admin_profiles ap where r.actor_admin_profile_id='00000000-0000-4000-8000-000000000301' and r.idempotency_key='command-001' and ap.id='00000000-0000-4000-8000-000000000302'$$,'23514',null,'Audit actor mismatch is rejected.');
select throws_ok($$insert into app.admin_audit_events (receipt_id,actor_admin_profile_id,scope_kind,command_name,target_type,target_id,reason) select r.id,r.actor_admin_profile_id,'global',r.command_name,r.target_type,r.target_id,'Scope mismatch' from app.admin_command_receipts r where r.idempotency_key='command-001'$$,'23514',null,'Audit scope mismatch is rejected.');
select throws_ok($$insert into app.admin_audit_events (receipt_id,actor_admin_profile_id,scope_kind,brand_id,command_name,target_type,target_id,reason) select r.id,r.actor_admin_profile_id,r.scope_kind,b.id,r.command_name,r.target_type,r.target_id,'Brand mismatch' from app.admin_command_receipts r cross join app.educational_brands b where r.actor_admin_profile_id='00000000-0000-4000-8000-000000000301' and r.idempotency_key='command-001' and b.code='test-brand-2'$$,'23514',null,'Audit non-null brand mismatch is rejected.');
select throws_ok($$insert into app.admin_audit_events (receipt_id,actor_admin_profile_id,scope_kind,command_name,target_type,target_id,reason) select r.id,r.actor_admin_profile_id,r.scope_kind,r.command_name,'other_target',r.target_id,'Target type mismatch' from app.admin_command_receipts r where r.idempotency_key='command-global'$$,'23514',null,'Audit target type mismatch is rejected.');
select throws_ok($$insert into app.admin_audit_events (receipt_id,actor_admin_profile_id,scope_kind,command_name,target_type,target_id,reason) select r.id,r.actor_admin_profile_id,r.scope_kind,r.command_name,r.target_type,gen_random_uuid(),'Target id mismatch' from app.admin_command_receipts r where r.idempotency_key='command-global'$$,'23514',null,'Audit target id mismatch is rejected.');
select throws_ok($$insert into app.admin_audit_events (receipt_id,actor_admin_profile_id,scope_kind,brand_id,command_name,target_type,target_id,reason,before_summary) select r.id,r.actor_admin_profile_id,r.scope_kind,r.brand_id,r.command_name,r.target_type,r.target_id,'Bad before','[]'::jsonb from app.admin_command_receipts r where r.idempotency_key='command-001'$$,'23514',null,'Audit before summary non-object is rejected.');
select throws_ok($$insert into app.admin_audit_events (receipt_id,actor_admin_profile_id,scope_kind,brand_id,command_name,target_type,target_id,reason,after_summary) select r.id,r.actor_admin_profile_id,r.scope_kind,r.brand_id,r.command_name,r.target_type,r.target_id,'Bad after','[]'::jsonb from app.admin_command_receipts r where r.idempotency_key='command-001'$$,'23514',null,'Audit after summary non-object is rejected.');
select throws_ok($$insert into app.admin_audit_events (receipt_id,actor_admin_profile_id,scope_kind,brand_id,command_name,target_type,target_id,reason,metadata) select r.id,r.actor_admin_profile_id,r.scope_kind,r.brand_id,r.command_name,r.target_type,r.target_id,'Large metadata',jsonb_build_object('x',repeat('x',32769)) from app.admin_command_receipts r where r.idempotency_key='command-001'$$,'23514',null,'Oversized audit metadata is rejected.');
select throws_ok($$insert into app.admin_audit_events (receipt_id,actor_admin_profile_id,scope_kind,command_name,target_type,target_id,reason) select r.id,r.actor_admin_profile_id,r.scope_kind,r.command_name,r.target_type,r.target_id,'No op event' from app.admin_command_receipts r where r.idempotency_key='command-006'$$,'23514',null,'No-op receipt cannot receive an audit event.');

select * from finish();
rollback;
