begin;
select plan(30);
select is((select count(*) from app.educational_brands),3::bigint,'Seed has three commercial brands.');
select is((select count(*) from app.academic_institutions),2::bigint,'Seed has BUC and Delta academic institutions.');
select is((select count(*) from app.brand_academic_institution_access),6::bigint,'All three brands are mapped to both academic institutions.');
select is((select count(*) from app.academic_levels),2::bigint,'Seed has one Level 1 row per academic institution.');
select is((select count(*) from app.academic_semesters),4::bigint,'Seed has BUC and Delta Level 1 Semesters 1 and 2.');
select is((select count(*) from app.academic_modules),30::bigint,'Seed has fourteen BUC modules, fourteen shared Delta modules, and two Delta-specific modules.');
select is((select count(*) from app.academic_module_chapters),98::bigint,'Seed has forty-nine ordered topics for both BUC and Delta shared modules.');
select is((select count(*) from app.academic_module_aliases),0::bigint,'Seed has no aliases.');
select is((select count(*) from app.instructors),3::bigint,'Seed has three instructors.');
select is((select count(*) from app.instructor_brand_assignments),3::bigint,'Seed has three teaching scopes.');
select is((select count(*) from app.brand_courses),0::bigint,'Seed has no BrandCourses.');
select is((select count(*) from app.course_instructor_assignments),0::bigint,'Seed has no CourseInstructorAssignments.');
select is((select array_agg(code order by code) from app.educational_brands),array['elite','medway','nexus']::text[],'Seed brand codes are exactly Elite, Medway, and Nexus.');
select is((select count(*) from app.educational_brands where code='buc'),0::bigint,'BUC is not seeded as a brand.');
select is((select array_agg(code::text order by code) from app.academic_institutions),array['buc','delta']::text[],'Academic institution codes are exactly BUC and Delta.');
select is((select array_agg(level_number order by academic_institution_id, level_number) from app.academic_levels),array[1,1]::integer[],'Only Level 1 is seeded for each institution.');
select is((select count(*) from app.academic_semesters s join app.academic_levels l on l.id=s.academic_level_id join app.academic_institutions i on i.id=l.academic_institution_id where (i.code,l.level_number,s.semester_number) in (('buc',1,1),('buc',1,2),('delta',1,1),('delta',1,2))),4::bigint,'Semester hierarchy is exactly BUC and Delta Level 1 Semesters 1-2.');
select is((select count(*) from app.academic_modules m join app.academic_semesters s on s.id=m.academic_semester_id join app.academic_levels l on l.id=s.academic_level_id join app.academic_institutions i on i.id=l.academic_institution_id where i.code='buc' and l.level_number=1),14::bigint,'BUC Level 1 has fourteen modules.');
select is((select count(*) from app.academic_modules m join app.academic_semesters s on s.id=m.academic_semester_id join app.academic_levels l on l.id=s.academic_level_id join app.academic_institutions i on i.id=l.academic_institution_id where i.code='delta' and l.level_number=1 and s.semester_number=1 and m.code in ('DELTA-ENG1','DELTA-IT')),2::bigint,'Delta Level 1 Semester 1 has English 1 and IT modules.');
select is((select count(*) from app.academic_modules m join app.academic_semesters s on s.id=m.academic_semester_id join app.academic_levels l on l.id=s.academic_level_id join app.academic_institutions i on i.id=l.academic_institution_id where i.code='delta' and m.code in ('1101 TSF','1102 ANA','1103 CBG','1104 BIO','1105 PMD','1106 ECX','1107 SIM','1208 IPP','1209 PAT','1210 MIC','1211 PHE','1212 IMM','1213 SIM','1214 SBS')),14::bigint,'Delta has the fourteen shared medical modules.');
select is((select count(*) from app.academic_modules m join app.academic_semesters s on s.id=m.academic_semester_id join app.academic_levels l on l.id=s.academic_level_id where l.level_number=2),0::bigint,'Level 2 is not seeded.');
select is((select count(*) from app.academic_modules where code in ('1101 TSF','1102 ANA','1103 CBG','1104 BIO','1105 PMD','1106 ECX','1107 SIM','1208 IPP','1209 PAT','1210 MIC','1211 PHE','1212 IMM','1213 SIM','1214 SBS')),28::bigint,'The exact fourteen shared module codes are present for both institutions.');
select is((select count(*) from app.academic_modules where code='1105 PMD' and review_status='blocked'),2::bigint,'1105 PMD is present once per institution and blocked.');
select is((select count(*) from app.academic_modules where normalized_code='PDM1105'),0::bigint,'No PDM1105 canonical code exists.');
select is((select count(*) from app.academic_module_aliases where normalized_alias='PDM1105' and status='active'),0::bigint,'No active PDM1105 alias exists.');
select is((select count(*) from app.academic_modules where review_status='unreviewed'),28::bigint,'The other twenty-eight Level 1 modules are unreviewed.');
select is((select count(*) from app.academic_modules where review_status='approved'),0::bigint,'No module is marked approved.');
select is((select array_agg(display_name::text order by code)::text[] from app.instructors),array['محمد بسيوني فايد','زياد وائل فتحي','شروق محمد عاطف']::text[],'Arabic Instructor names are exact.');
select is((select count(*) from app.instructor_brand_assignments iba join app.educational_brands b on b.id=iba.brand_id where b.code='elite' and iba.status='active'),3::bigint,'All Instructor teaching scopes are active Elite assignments.');
select is((select count(*) from app.instructor_brand_assignments iba join app.educational_brands b on b.id=iba.brand_id where b.code='medway'),0::bigint,'No Instructor teaching scope is Medway.');
select * from finish();
rollback;
