begin;
select plan(40);

select is((select count(*) from information_schema.tables where table_schema='app' and table_name='academic_module_resources' and table_type='BASE TABLE'),1::bigint,'M021 creates exactly its intended resource table.');
select is((select count(*) from information_schema.tables where table_schema='app' and table_type='BASE TABLE' and table_name in ('educational_brands','app_users','brand_memberships','student_profiles','admin_profiles','admin_permissions','admin_roles','admin_role_permissions','platform_admin_role_assignments','admin_command_receipts','admin_audit_events','academic_levels','academic_semesters','academic_modules','academic_module_aliases','instructors','instructor_brand_assignments','brand_courses','course_instructor_assignments','academic_module_resources')),20::bigint,'The scoped chain through M021 has twenty app tables.');
select is((select count(*) from app.academic_module_resources),0::bigint,'Migration 021 creates no business rows.');
select is((select count(*) from pg_constraint c join pg_class r on r.oid=c.conrelid join pg_namespace n on n.oid=r.relnamespace where n.nspname='app' and r.relname='academic_module_resources' and c.contype='p'),1::bigint,'Resource table has one primary key.');
select is((select count(*) from pg_constraint c join pg_class r on r.oid=c.conrelid join pg_namespace n on n.oid=r.relnamespace where n.nspname='app' and r.relname='academic_module_resources' and c.contype='u'),2::bigint,'Resource key and source path have unique constraints.');
select ok((select c.confdeltype='r' and c.confupdtype='r' from pg_constraint c join pg_class r on r.oid=c.conrelid join pg_namespace n on n.oid=r.relnamespace where n.nspname='app' and r.relname='academic_module_resources' and c.contype='f'),'Resource FK restricts delete and update.');
select ok((select not is_nullable::boolean from (select (is_nullable='YES') is_nullable from information_schema.columns where table_schema='app' and table_name='academic_module_resources' and column_name='academic_module_id') q),'Resource module FK column is required.');

insert into app.academic_levels (id,level_number,display_title,sort_order) values ('71000000-0000-4000-8000-000000000001',99,'Fixture Level',1);
insert into app.academic_semesters (id,academic_level_id,semester_number,display_title,sort_order) values ('71000000-0000-4000-8000-000000000002','71000000-0000-4000-8000-000000000001',1,'Fixture Semester',1);
insert into app.academic_modules (id,academic_semester_id,code,source_display_label,sort_order) values
 ('71000000-0000-4000-8000-000000000003','71000000-0000-4000-8000-000000000002','9901 TST','9901 TST',1),
 ('40000000-0000-4000-8000-000000000005','71000000-0000-4000-8000-000000000002','1105 PMD','1105 PMD',2);

insert into app.academic_module_resources (id,academic_module_id,resource_key,source_relative_path,display_name,file_format,mime_type,resource_classification)
values ('72000000-0000-4000-8000-000000000001','71000000-0000-4000-8000-000000000003','fixture-001','Semester 1/9901 TST/Lecture 1.pdf','Lecture 1.pdf','pdf','application/pdf','lecture');

select throws_ok($$insert into app.academic_module_resources (id,academic_module_id,resource_key,source_relative_path,display_name,file_format,resource_classification) values ('72000000-0000-4000-8000-000000000001','71000000-0000-4000-8000-000000000003','fixture-pk','Semester 1/9901 TST/pk.pdf','pk.pdf','pdf','lecture')$$,'23505',null,'Duplicate resource UUID is rejected.');
select throws_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,resource_classification) values ('71000000-0000-4000-8000-000000000003','fixture-001','Semester 1/9901 TST/key.pdf','key.pdf','pdf','lecture')$$,'23505',null,'Duplicate resource key is rejected.');
select throws_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,resource_classification) values ('71000000-0000-4000-8000-000000000003','fixture-path','Semester 1/9901 TST/Lecture 1.pdf','path.pdf','pdf','lecture')$$,'23505',null,'Duplicate source path is rejected.');
select throws_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,resource_classification) values ('71000000-0000-4000-8000-000000000003',' ','Semester 1/9901 TST/blank-key.pdf','blank-key.pdf','pdf','lecture')$$,'23514',null,'Blank resource key is rejected.');
select throws_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,resource_classification) values ('71000000-0000-4000-8000-000000000003','fixture-blank-path',' ','blank-path.pdf','pdf','lecture')$$,'23514',null,'Blank source path is rejected.');
select throws_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,resource_classification) values ('71000000-0000-4000-8000-000000000003','fixture-blank-name','Semester 1/9901 TST/blank-name.pdf',' ','pdf','lecture')$$,'23514',null,'Blank display name is rejected.');
select throws_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,resource_classification,version) values ('71000000-0000-4000-8000-000000000003','fixture-version','Semester 1/9901 TST/version.pdf','version.pdf','pdf','lecture',0)$$,'23514',null,'Non-positive version is rejected.');
select throws_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,resource_classification) values ('71000000-0000-4000-8000-000000000003','fixture-format','Semester 1/9901 TST/format.pdf','format.pdf','exe','lecture')$$,'23514',null,'Invalid file format is rejected.');
select throws_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,resource_classification) values ('71000000-0000-4000-8000-000000000003','fixture-class','Semester 1/9901 TST/class.pdf','class.pdf','pdf','invalid')$$,'23514',null,'Invalid classification is rejected.');
select throws_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,resource_classification,distribution_review_status) values ('71000000-0000-4000-8000-000000000003','fixture-review','Semester 1/9901 TST/review.pdf','review.pdf','pdf','lecture','invalid')$$,'23514',null,'Invalid review state is rejected.');
select throws_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,resource_classification,publication_state) values ('71000000-0000-4000-8000-000000000003','fixture-publication','Semester 1/9901 TST/publication.pdf','publication.pdf','pdf','lecture','invalid')$$,'23514',null,'Invalid publication state is rejected.');
select throws_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,resource_classification) values ('71000000-0000-4000-8000-000000000099','fixture-fk','Semester 1/9901 TST/fk.pdf','fk.pdf','pdf','lecture')$$,'23503',null,'Unknown AcademicModule is rejected.');
select throws_ok($$delete from app.academic_modules where id='71000000-0000-4000-8000-000000000003'$$,'23503',null,'AcademicModule deletion is restricted while resources exist.');
select throws_ok($$update app.academic_modules set id='71000000-0000-4000-8000-000000000004' where id='71000000-0000-4000-8000-000000000003'$$,'23503',null,'AcademicModule identity update is restricted while resources exist.');
select throws_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,resource_classification,distribution_review_status,publication_state) values ('71000000-0000-4000-8000-000000000003','fixture-no-storage','Semester 1/9901 TST/no-storage.pdf','no-storage.pdf','pdf','lecture','approved','published')$$,'23514',null,'Published resource without storage path is rejected.');
select throws_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,resource_classification,distribution_review_status,publication_state,storage_object_path) values ('71000000-0000-4000-8000-000000000003','fixture-assessment-publish','Semester 1/9901 TST/assessment.pdf','assessment.pdf','pdf','assessment','restricted','published','private/assessment.pdf')$$,'23514',null,'Assessment cannot be initially published.');
select throws_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,resource_classification,distribution_review_status,publication_state,storage_object_path) values ('71000000-0000-4000-8000-000000000003','fixture-admin-publish','Semester 1/9901 TST/admin.pdf','admin.pdf','pdf','administrative','restricted','published','private/admin.pdf')$$,'23514',null,'Administrative material cannot be initially published.');
select throws_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,resource_classification,distribution_review_status) values ('71000000-0000-4000-8000-000000000003','fixture-assessment-review','Semester 1/9901 TST/assessment-review.pdf','assessment-review.pdf','pdf','assessment','unreviewed')$$,'23514',null,'Assessment must be restricted at insertion.');
select lives_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,resource_classification,distribution_review_status) values ('71000000-0000-4000-8000-000000000003','fixture-assessment-valid','Semester 1/9901 TST/assessment-valid.pdf','assessment-valid.pdf','pdf','assessment','restricted')$$,'Restricted unpublished assessment metadata is accepted.');
select throws_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,resource_classification,distribution_review_status) values ('40000000-0000-4000-8000-000000000005','fixture-pmd-approved','Semester 1/1105 PMD/approved.pdf','approved.pdf','pdf','lecture','approved')$$,'23514',null,'1105 PMD resource cannot be approved.');
select lives_ok($$insert into app.academic_module_resources (id,academic_module_id,resource_key,source_relative_path,display_name,file_format,resource_classification,distribution_review_status) values ('72000000-0000-4000-8000-000000000005','40000000-0000-4000-8000-000000000005','fixture-pmd-valid','Semester 1/1105 PMD/blocked.pdf','blocked.pdf','pdf','lecture','blocked_restricted')$$,'Blocked and restricted 1105 PMD metadata is accepted.');
select throws_ok($$update app.academic_module_resources set publication_state='published',storage_object_path='private/pmd.pdf' where id='72000000-0000-4000-8000-000000000005'$$,'23514',null,'1105 PMD resource cannot be published.');
select throws_ok($$update app.academic_module_resources set distribution_review_status='approved' where id='72000000-0000-4000-8000-000000000005'$$,'23514',null,'1105 PMD resource cannot leave blocked and restricted review.');

select is((select count(*) from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace join pg_proc p on p.oid=t.tgfoid where n.nspname='app' and c.relname='academic_module_resources' and not t.tgisinternal and p.oid='app.set_updated_at()'::regprocedure),1::bigint,'Resource table uses app.set_updated_at exactly once.');
select is((select count(*) from information_schema.role_table_grants where table_schema='app' and table_name='academic_module_resources' and grantee in ('PUBLIC','anon','authenticated') and privilege_type in ('INSERT','UPDATE','DELETE','SELECT','TRUNCATE','REFERENCES','TRIGGER')),0::bigint,'Client roles have no direct M021 table grants.');
select is((select count(*) from (values ('anon'),('authenticated')) roles(role_name), (values ('SELECT'),('INSERT'),('UPDATE'),('DELETE'),('TRUNCATE'),('REFERENCES'),('TRIGGER')) privileges(privilege_name) where has_table_privilege(roles.role_name,'app.academic_module_resources',privileges.privilege_name)),0::bigint,'Client roles have zero effective M021 table privileges.');
select is((select count(*) from pg_policies where schemaname='app' and tablename='academic_module_resources'),0::bigint,'M021 adds no RLS policy.');
select is((select count(*) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='app' and c.relname like 'academic_module_resources%' and c.relkind in ('v','m')),0::bigint,'M021 adds no exposed view.');
select is((select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='app' and p.prosecdef and p.proname like '%academic_module_resource%'),0::bigint,'M021 adds no SECURITY DEFINER function.');
select is((with f as (select c.conrelid,c.conkey from pg_constraint c join pg_class r on r.oid=c.conrelid join pg_namespace n on n.oid=r.relnamespace where c.contype='f' and n.nspname='app' and r.relname='academic_module_resources'),u as (select f.* from f where not exists (select 1 from pg_index i where i.indrelid=f.conrelid and i.indpred is null and (select array_agg(k.attnum order by k.ordinality) from unnest(i.indkey) with ordinality k(attnum,ordinality) where k.ordinality<=array_length(f.conkey,1))=f.conkey)) select count(*) from u),0::bigint,'Every M021 foreign key has a full ordered non-partial child index.');
select is((select count(*) from pg_indexes where schemaname='app' and tablename='academic_module_resources' and indexname='academic_module_resources_academic_module_id_idx' and indexdef not like '% WHERE %'),1::bigint,'M021 has its full child-side FK index.');
select is((select count(*) from pg_indexes where schemaname='app' and tablename='academic_module_resources' and indexname='academic_module_resources_module_classification_path_idx' and indexdef like '%(academic_module_id, resource_classification, source_relative_path)%'),1::bigint,'M021 has its module classification and path listing index.');
select is((select count(*) from information_schema.columns where table_schema='app' and table_name='academic_module_resources' and column_name in ('drive_id','drive_url','source_url','provider_id','permission_data','file_bytes','checksum')),0::bigint,'Resource table stores no prohibited provider identifiers, URLs, permissions, bytes, or download checksums.');

select * from finish();
rollback;
