begin;
select plan(31);

select is((select count(*) from information_schema.tables where table_schema='app' and table_name='academic_module_resources' and table_type='BASE TABLE'),1::bigint,'M026 extends exactly the private academic resource table.');
select is((select count(*) from information_schema.columns where table_schema='app' and table_name='academic_module_resources' and column_name in ('source_provider','source_drive_file_id','source_title','source_file_size_bytes','source_folder_path','resource_type','resource_category','approval_state','visibility_state','manual_review_required','approval_required','student_publish_default')),12::bigint,'M026 adds all required metadata/state columns.');
select is((select column_default::text from information_schema.columns where table_schema='app' and table_name='academic_module_resources' and column_name='publication_state'),'''not_published''::text','M026 publication default is not_published.');
select is((select column_default::text from information_schema.columns where table_schema='app' and table_name='academic_module_resources' and column_name='student_publish_default'),'false','Student publication defaults false.');
select is((select column_default::text from information_schema.columns where table_schema='app' and table_name='academic_module_resources' and column_name='approval_required'),'true','Approval defaults required.');

insert into app.academic_levels (id,level_number,display_title,sort_order) values ('73000000-0000-4000-8000-000000000001',98,'M026 Fixture Level',1);
insert into app.academic_semesters (id,academic_level_id,semester_number,display_title,sort_order) values ('73000000-0000-4000-8000-000000000002','73000000-0000-4000-8000-000000000001',1,'M026 Fixture Semester',1);
insert into app.academic_modules (id,academic_semester_id,code,source_display_label,sort_order) values ('73000000-0000-4000-8000-000000000003','73000000-0000-4000-8000-000000000002','M026','M026',1);

select lives_ok($$insert into app.academic_module_resources (id,academic_module_id,resource_key,source_relative_path,display_name,file_format,mime_type,resource_classification,source_provider,source_drive_file_id,source_title,source_file_size_bytes,source_folder_path,resource_type,resource_category,approval_state,visibility_state,manual_review_required) values ('74000000-0000-4000-8000-000000000001','73000000-0000-4000-8000-000000000003','m026-lecture','Semester 1/M026/Lecture 1.pdf','Lecture 1.pdf','pdf','application/pdf','lecture','google_drive','drive-lecture-1','Lecture 1.pdf',1024,'Semester 1/M026','lecture_pdf','lecture','pending_review','draft',false)$$,'Valid Google Drive lecture PDF metadata is accepted.');
select lives_ok($$insert into app.academic_module_resources (id,academic_module_id,resource_key,source_relative_path,display_name,file_format,mime_type,resource_classification,source_provider,source_drive_file_id,source_title,source_folder_path,resource_type,resource_category,approval_state,visibility_state,manual_review_required) values ('74000000-0000-4000-8000-000000000002','73000000-0000-4000-8000-000000000003','m026-slide','Semester 1/M026/Slides.pptx','Slides.pptx','pptx','application/vnd.openxmlformats-officedocument.presentationml.presentation','lecture','google_drive','drive-slide-1','Slides.pptx','Semester 1/M026','slide_deck','lecture','imported','draft',false)$$,'Valid Google Drive slide-deck metadata is accepted.');
select lives_ok($$insert into app.academic_module_resources (id,academic_module_id,resource_key,source_relative_path,display_name,file_format,mime_type,resource_classification,source_provider,source_drive_file_id,source_title,source_folder_path,resource_type,resource_category,approval_state,visibility_state) values ('74000000-0000-4000-8000-000000000003','73000000-0000-4000-8000-000000000003','m026-video','Semester 1/M026/Session.mp4','Session.mp4','mp4','video/mp4','recorded_lecture','google_drive','drive-video-1','Session.mp4','Semester 1/M026','video','session','pending_review','restricted')$$,'Valid video/session metadata remains approval-required and unpublished.');
select lives_ok($$insert into app.academic_module_resources (id,academic_module_id,resource_key,source_relative_path,display_name,file_format,mime_type,resource_classification,distribution_review_status,source_provider,source_drive_file_id,source_title,source_folder_path,resource_type,resource_category,approval_state,visibility_state) values ('74000000-0000-4000-8000-000000000004','73000000-0000-4000-8000-000000000003','m026-qb','Semester 1/M026/Question Bank.pdf','Question Bank.pdf','pdf','application/pdf','assessment','restricted','google_drive','drive-qb-1','Question Bank.pdf','Semester 1/M026','question_bank','assessment','blocked','restricted')$$,'Valid question-bank metadata remains restricted and unpublished.');

select throws_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,mime_type,resource_classification,source_provider,source_title,source_folder_path,resource_type,resource_category) values ('73000000-0000-4000-8000-000000000003','m026-no-drive-id','Semester 1/M026/no-id.pdf','no-id.pdf','pdf','application/pdf','lecture','google_drive','no-id.pdf','Semester 1/M026','lecture_pdf','lecture')$$,'23514',null,'Google Drive provider requires a nonblank Drive file ID.');
select throws_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,mime_type,resource_classification,source_provider,source_drive_file_id,source_title,source_folder_path,resource_type,resource_category) values ('73000000-0000-4000-8000-000000000003','m026-no-title','Semester 1/M026/no-title.pdf','no-title.pdf','pdf','application/pdf','lecture','google_drive','drive-no-title',null,'Semester 1/M026','lecture_pdf','lecture')$$,'23514',null,'Google Drive provider requires a source title.');
select throws_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,mime_type,resource_classification,source_provider,source_drive_file_id,source_title,source_folder_path,resource_type,resource_category) values ('73000000-0000-4000-8000-000000000003','m026-duplicate-drive','Semester 1/M026/duplicate.pdf','duplicate.pdf','pdf','application/pdf','lecture','google_drive','drive-lecture-1','duplicate.pdf','Semester 1/M026','lecture_pdf','lecture')$$,'23505',null,'Duplicate Drive file ID is rejected.');
select throws_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,mime_type,resource_classification,source_provider,source_drive_file_id,source_title,source_folder_path,resource_type,resource_category) values ('73000000-0000-4000-8000-000000000003','m026-bad-provider','Semester 1/M026/bad.pdf','bad.pdf','pdf','application/pdf','lecture','dropbox','drive-bad','bad.pdf','Semester 1/M026','lecture_pdf','lecture')$$,'23514',null,'Source provider is controlled.');
select throws_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,mime_type,resource_classification,source_provider,source_drive_file_id,source_title,source_file_size_bytes,source_folder_path,resource_type,resource_category) values ('73000000-0000-4000-8000-000000000003','m026-bad-size','Semester 1/M026/bad-size.pdf','bad-size.pdf','pdf','application/pdf','lecture','google_drive','drive-bad-size','bad-size.pdf',-1,'Semester 1/M026','lecture_pdf','lecture')$$,'23514',null,'Source file size cannot be negative.');
select throws_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,mime_type,resource_classification,source_provider,source_drive_file_id,source_title,source_folder_path,resource_type,resource_category) values ('73000000-0000-4000-8000-000000000003','m026-bad-type','Semester 1/M026/bad-type.pdf','bad-type.pdf','pdf','application/pdf','lecture','google_drive','drive-bad-type','bad-type.pdf','Semester 1/M026','bad_type','lecture')$$,'23514',null,'Resource type is controlled.');
select throws_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,mime_type,resource_classification,source_provider,source_drive_file_id,source_title,source_folder_path,resource_type,resource_category) values ('73000000-0000-4000-8000-000000000003','m026-bad-category','Semester 1/M026/bad-category.pdf','bad-category.pdf','pdf','application/pdf','lecture','google_drive','drive-bad-category','bad-category.pdf','Semester 1/M026','lecture_pdf','bad_category')$$,'23514',null,'Resource category is controlled.');
select throws_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,mime_type,resource_classification,source_provider,source_drive_file_id,source_title,source_folder_path,resource_type,resource_category,approval_state) values ('73000000-0000-4000-8000-000000000003','m026-bad-approval','Semester 1/M026/bad-approval.pdf','bad-approval.pdf','pdf','application/pdf','lecture','google_drive','drive-bad-approval','bad-approval.pdf','Semester 1/M026','lecture_pdf','lecture','bad')$$,'23514',null,'Approval state is controlled.');
select throws_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,mime_type,resource_classification,source_provider,source_drive_file_id,source_title,source_folder_path,resource_type,resource_category,visibility_state) values ('73000000-0000-4000-8000-000000000003','m026-bad-visibility','Semester 1/M026/bad-visibility.pdf','bad-visibility.pdf','pdf','application/pdf','lecture','google_drive','drive-bad-visibility','bad-visibility.pdf','Semester 1/M026','lecture_pdf','lecture','public')$$,'23514',null,'Visibility state is controlled.');

select throws_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,mime_type,resource_classification,source_provider,source_drive_file_id,source_title,source_folder_path,resource_type,resource_category,approval_state,visibility_state,manual_review_required,publication_state) values ('73000000-0000-4000-8000-000000000003','m026-unknown-publish','Semester 1/M026/unknown.bin','unknown.bin','binary','application/octet-stream','unknown','google_drive','drive-unknown','unknown.bin','Semester 1/M026','unknown','unknown','approved','internal',true,'not_published')$$,'23514',null,'Unknown resources cannot be approved.');
select throws_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,mime_type,resource_classification,source_provider,source_drive_file_id,source_title,source_folder_path,resource_type,resource_category,approval_state,visibility_state,publication_state) values ('73000000-0000-4000-8000-000000000003','m026-qb-public','Semester 1/M026/qb-public.pdf','qb-public.pdf','pdf','application/pdf','assessment','google_drive','drive-qb-public','qb-public.pdf','Semester 1/M026','question_bank','assessment','blocked','internal','not_published')$$,'23514',null,'Question banks must remain restricted.');
select throws_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,mime_type,resource_classification,source_provider,source_drive_file_id,source_title,source_folder_path,resource_type,resource_category,approval_state,visibility_state,publication_state) values ('73000000-0000-4000-8000-000000000003','m026-video-publish','Semester 1/M026/video-publish.mp4','video-publish.mp4','mp4','video/mp4','recorded_lecture','google_drive','drive-video-publish','video-publish.mp4','Semester 1/M026','video','session','approved','restricted','published')$$,'23514',null,'Video/session metadata cannot be published in M026.');
select throws_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,mime_type,resource_classification,source_provider,source_drive_file_id,source_title,source_folder_path,resource_type,resource_category,approval_state,visibility_state,student_publish_default) values ('73000000-0000-4000-8000-000000000003','m026-student-visible','Semester 1/M026/student-visible.pdf','student-visible.pdf','pdf','application/pdf','lecture','google_drive','drive-student-visible','student-visible.pdf','Semester 1/M026','lecture_pdf','lecture','approved','draft',true)$$,'23514',null,'Student publication cannot be enabled in M026.');
select throws_ok($$insert into app.academic_module_resources (academic_module_id,resource_key,source_relative_path,display_name,file_format,mime_type,resource_classification,source_provider,source_drive_file_id,source_title,source_folder_path,resource_type,resource_category,storage_object_path) values ('73000000-0000-4000-8000-000000000003','m026-storage','Semester 1/M026/storage.pdf','storage.pdf','pdf','application/pdf','lecture','google_drive','drive-storage','storage.pdf','Semester 1/M026','lecture_pdf','lecture','private/storage.pdf')$$,'23514',null,'Storage locator remains unavailable in M026.');

select is((select count(*) from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace join pg_proc p on p.oid=t.tgfoid where n.nspname='app' and c.relname='academic_module_resources' and not t.tgisinternal and p.oid='app.set_updated_at()'::regprocedure),1::bigint,'M026 preserves the single updated-at trigger.');
select is((select count(*) from information_schema.role_table_grants where table_schema='app' and table_name='academic_module_resources' and grantee in ('PUBLIC','anon','authenticated') and privilege_type in ('INSERT','UPDATE','DELETE','SELECT','TRUNCATE','REFERENCES','TRIGGER')),0::bigint,'Client roles have no direct resource-table grants.');
select is((select count(*) from (values ('anon'),('authenticated')) roles(role_name), (values ('SELECT'),('INSERT'),('UPDATE'),('DELETE'),('TRUNCATE'),('REFERENCES'),('TRIGGER')) privileges(privilege_name) where has_table_privilege(roles.role_name,'app.academic_module_resources',privileges.privilege_name)),0::bigint,'Client roles have zero effective resource-table privileges.');
select is((select count(*) from pg_policies where schemaname='app' and tablename='academic_module_resources'),0::bigint,'M026 adds no RLS policy to private app schema.');
select is((select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='app' and p.prosecdef),0::bigint,'M026 adds no SECURITY DEFINER function.');
select is((select count(*) from pg_indexes where schemaname='app' and tablename='academic_module_resources' and indexname='academic_module_resources_source_drive_file_id_key'),1::bigint,'M026 has a unique Drive-file index.');
select is((with f as (select c.conrelid,c.conkey from pg_constraint c join pg_class r on r.oid=c.conrelid join pg_namespace n on n.oid=r.relnamespace where c.contype='f' and n.nspname='app' and r.relname='academic_module_resources'),u as (select f.* from f where not exists (select 1 from pg_index i where i.indrelid=f.conrelid and i.indpred is null and (select array_agg(k.attnum order by k.ordinality) from unnest(i.indkey) with ordinality k(attnum,ordinality) where k.ordinality<=array_length(f.conkey,1))=f.conkey)) select count(*) from u),0::bigint,'M026 FK child indexes are covered.');
select is((select count(*) from information_schema.columns where table_schema='app' and table_name='academic_module_resources' and column_name in ('drive_url','source_url','provider_id','permission_data','file_bytes','checksum','cdn_url','delivery_url','public_url','signed_url')),0::bigint,'M026 adds no public/provider URL or payload columns.');

select * from finish();
rollback;
