begin;
select plan(18);
select has_table('app','academic_module_chapters','Chapter table exists.');
select has_column('app','academic_module_chapters','academic_module_id','Chapter points to a module.');
select has_column('app','academic_module_chapters','code','Chapter has a code.');
select has_column('app','academic_module_chapters','title','Chapter has a title.');
select has_column('app','academic_module_chapters','sort_order','Chapter has an order.');
select col_is_pk('app','academic_module_chapters','id','Chapter id is primary key.');
select ok((select count(*) from pg_constraint where conname in ('academic_module_chapters_module_code_key','academic_module_chapters_module_sort_key'))=2,'Module/code and module/order uniqueness constraints exist.');
select ok((select count(*) from pg_constraint where conname='academic_module_chapters_module_code_key')=1,'Module/code uniqueness exists.');
select ok((select count(*) from pg_constraint where conname='academic_module_chapters_module_sort_key')=1,'Module/order uniqueness exists.');
select ok((select count(*) from pg_constraint where conname='academic_module_chapters_module_id_fkey')=1,'Module foreign key exists.');
select ok((select count(*) from pg_indexes where schemaname='app' and indexname='academic_module_chapters_academic_module_id_idx')=1,'Child FK index exists.');
select ok((select count(*) from pg_trigger where tgrelid='app.academic_module_chapters'::regclass and tgname='academic_module_chapters_set_updated_at')=1,'Updated-at trigger exists.');
select ok((select has_function_privilege('anon','app.set_updated_at()','execute') is false),'Anon cannot execute helper function.');
select ok((select has_table_privilege('anon','app.academic_module_chapters','select,insert,update,delete') is false),'Anon has no chapter table privileges.');
select ok((select count(*) from pg_policies where schemaname='app' and tablename='academic_module_chapters')=0,'No chapter RLS policies exist.');
select ok((select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='app' and p.prosecdef)=0,'No app SECURITY DEFINER functions exist.');
select ok((select count(*) from information_schema.check_constraints where constraint_name in ('academic_module_chapters_sort_order_check','academic_module_chapters_status_check','academic_module_chapters_title_trimmed_check'))=3,'Chapter checks exist.');
select ok((select count(*) from pg_description d join pg_class c on c.oid=d.objoid join pg_namespace n on n.oid=c.relnamespace where n.nspname='app' and c.relname='academic_module_chapters')=1,'Chapter table is documented.');
select * from finish();
rollback;
