import type { AdminRequestContext } from "../context";
import { fail, ok, type Result } from "../../shared";
import { policyValidationError, targetBrandMismatchError, type AdminCoreError } from "../errors";

export interface AdminPolicyValidationInput { readonly context: AdminRequestContext; readonly commandName: string; readonly targetType: string; readonly targetId: string; readonly targetBrandId?: string; /** @deprecated Compatibility alias for brand scope. */ readonly targetPlatformId?: string; readonly policySetId?: string; readonly expectedVersion?: string | number; readonly metadata?: Readonly<Record<string, unknown>>; }
export interface AdminLifecycleTransitionInput { readonly context: AdminRequestContext; readonly entityType: string; readonly entityId: string; readonly fromStatus?: string; readonly toStatus: string; readonly policySetId?: string; }
export interface AdminPolicyValidator { validateCommandPolicy(input: AdminPolicyValidationInput): Promise<Result<void, AdminCoreError>>; validateLifecycleTransition(input: AdminLifecycleTransitionInput): Promise<Result<void, AdminCoreError>>; validateTargetBrand(input: { readonly context: AdminRequestContext; readonly targetBrandId: string }): Result<void, AdminCoreError>; /** @deprecated Compatibility alias for brand validation. */ validateTargetPlatform(input: { readonly context: AdminRequestContext; readonly targetPlatformId: string }): Result<void, AdminCoreError>; }
export interface InMemoryAdminPolicyValidatorOptions { readonly rejectedCommands?: readonly string[]; readonly rejectedTransitions?: readonly string[]; readonly unsupportedScopes?: readonly string[]; }
/** Real effective-date, version, lifecycle, and scope policy evaluation remains future work. */
export class InMemoryAdminPolicyValidator implements AdminPolicyValidator {
  private readonly options: InMemoryAdminPolicyValidatorOptions;
  constructor(options: InMemoryAdminPolicyValidatorOptions = {}) { this.options = options; }
  validateTargetBrand(input: { readonly context: AdminRequestContext; readonly targetBrandId: string }): Result<void, AdminCoreError> { return input.context.brand.brandId === input.targetBrandId ? ok(undefined) : fail(targetBrandMismatchError(input.context.correlationId, { brandCode: input.context.brand.brandCode })); }
  validateTargetPlatform(input: { readonly context: AdminRequestContext; readonly targetPlatformId: string }): Result<void, AdminCoreError> { return this.validateTargetBrand({ context: input.context, targetBrandId: input.targetPlatformId }); }
  async validateCommandPolicy(input: AdminPolicyValidationInput): Promise<Result<void, AdminCoreError>> { const targetBrandId = input.targetBrandId ?? input.targetPlatformId; if (!targetBrandId) return fail(policyValidationError(input.context.correlationId, { reason: "brand_required" })); const brand = this.validateTargetBrand({ context: input.context, targetBrandId }); if (!brand.ok) return brand; if (this.options.unsupportedScopes?.includes(input.targetType)) return fail({ ...policyValidationError(input.context.correlationId), code: "unsupported_scope", message: "The requested scope is not supported by this evaluator." }); if (this.options.rejectedCommands?.includes(input.commandName)) return fail(policyValidationError(input.context.correlationId, { commandName: input.commandName, targetType: input.targetType })); return ok(undefined); }
  async validateLifecycleTransition(input: AdminLifecycleTransitionInput): Promise<Result<void, AdminCoreError>> { if (this.options.rejectedTransitions?.includes(`${input.entityType}:${input.toStatus}`)) return fail({ code: "lifecycle_transition_denied", message: "The lifecycle transition is not allowed by the configured test policy.", correlationId: input.context.correlationId }); return ok(undefined); }
}