import { createApplication } from "../../../app";
import { repositoryErr, repositoryOk, type RepositoryResult } from "../../../core/persistence";
import type { M1EducationalBrand, M1EducationalBrandReadRepository, M2ReadRepositories } from "../../../core/repositories";
import { InMemoryAdminM2ReadModel } from "./in-memory-admin-m2-read-model";
import { PostgresAdminM2ReadModel } from "./postgres-admin-m2-read-model";
import { AdminM2ReadModelConfigurationError, resolveAdminM2ReadModelSource } from "./admin-m2-source";
function assert(condition: unknown, message: string): asserts condition { if(!condition) throw new Error(message); }
class Brands implements M1EducationalBrandReadRepository { calls=0; async findEducationalBrandById(input:{id:string}):Promise<RepositoryResult<M1EducationalBrand>> { this.calls++; return input.id === "123e4567-e89b-12d3-a456-426614174000" ? repositoryOk({id:input.id,code:"medway",name:"Medway",slug:"medway",status:"active",createdAt:"x",updatedAt:"x"}) : repositoryErr({code:"not_found",message:"missing"}); } async findEducationalBrandByCode():Promise<RepositoryResult<M1EducationalBrand>> { return repositoryErr({code:"not_found",message:"missing"}); } }
function repositories(calls:string[]):M2ReadRepositories { const none=repositoryErr({code:"not_found" as const,message:"missing"}); return { academicLevels:{async findAcademicLevelById(){return none;},async listAcademicLevels(){calls.push("levels");return repositoryOk([]);}}, academicSemesters:{async findAcademicSemesterById(){return none;},async listAcademicSemesters(){calls.push("semesters");return repositoryOk([]);},async listAcademicSemestersByLevelId(i){calls.push(`level:${i.levelId}`);return repositoryOk([]);}}, academicModules:{async findAcademicModuleById(){return none;},async findAcademicModuleByCode(){return none;},async listAcademicModules(){calls.push("modules");return repositoryOk([]);},async listAcademicModulesBySemesterId(i){calls.push(`semester:${i.semesterId}`);return repositoryOk([]);}}, academicModuleAliases:{async findAcademicModuleAlias(){return none;}}, instructors:{async findInstructorById(){return none;},async findInstructorByCode(){return none;},async listInstructors(){calls.push("instructors");return repositoryOk([]);}}, instructorBrandAssignments:{async listBrandAssignments(i){calls.push(`brand-instructors:${i.brand.brandId}`);return repositoryOk([]);},async findBrandAssignment(){return none;},async listInstructorBrands(){return repositoryOk([]);}}, brandCourses:{async findBrandCourseById(){return none;},async findBrandCourseByCode(){return none;},async listBrandCourses(){return repositoryOk([]);},async listBrandCoursesByAcademicModule(i){calls.push(`module-courses:${i.academicModuleId}`);return repositoryOk([]);},async listStandaloneBrandCourses(i){calls.push(`standalone:${i.brand.brandId}`);return repositoryOk([]);}}, courseInstructorAssignments:{async listCourseInstructors(i){calls.push(`course-instructors:${i.brand.brandId}:${i.courseId}`);return repositoryOk([]);},async listInstructorCourseAssignments(i){calls.push(`instructor-courses:${i.brand.brandId}:${i.instructorId}`);return repositoryOk([]);}} }; }
export async function runAdminM2ReadModelSelfTest(): Promise<void> { assert(resolveAdminM2ReadModelSource({}) === "mock","default must be mock"); assert(resolveAdminM2ReadModelSource({ADMIN_M2_READ_MODEL_SOURCE:"postgres"}) === "postgres","postgres source invalid"); try{resolveAdminM2ReadModelSource({ADMIN_M2_READ_MODEL_SOURCE:"bad"});throw new Error("invalid source accepted");}catch(error){assert(error instanceof AdminM2ReadModelConfigurationError,"invalid source must be safe");} const mock=new InMemoryAdminM2ReadModel(); const empty=await mock.listAcademicLevels(); assert(empty.ok&&empty.value.length===0,"mock list must be empty"); const missing=await mock.findInstructor({instructorId:"x"});assert(!missing.ok&&missing.error.code === "not_found","mock find must be missing"); const calls:string[]=[];const brands=new Brands();const postgres=new PostgresAdminM2ReadModel(brands,repositories(calls));assert(!calls.length&&!brands.calls,"construction must not query"); await postgres.listAcademicSemesters({levelId:"level"});await postgres.listAcademicModules({semesterId:"semester"});await postgres.listInstructors();await postgres.listBrandCourses({brandId:"123e4567-e89b-12d3-a456-426614174000",academicModuleId:"module"});await postgres.listCourseInstructors({brandId:"123e4567-e89b-12d3-a456-426614174000",courseId:"course"}); assert(calls.includes("level:level")&&calls.includes("semester:semester")&&calls.includes("instructors")&&calls.includes("module-courses:module")&&calls.some(v=>v.startsWith("course-instructors:")),"repository calls not correctly scoped"); const mockApp=createApplication({environment:{PERSISTENCE_PROVIDER:"mock",ADMIN_READ_MODEL_SOURCE:"mock",ADMIN_M2_READ_MODEL_SOURCE:"mock"}});assert(mockApp.adminM2Source === "mock"&&mockApp.persistence.provider === "mock","mock matrix invalid");await mockApp.close();try{createApplication({environment:{PERSISTENCE_PROVIDER:"mock",ADMIN_READ_MODEL_SOURCE:"mock",ADMIN_M2_READ_MODEL_SOURCE:"postgres"}});throw new Error("invalid matrix accepted");}catch(error){assert(error instanceof AdminM2ReadModelConfigurationError,"invalid matrix must be safe");} }
if(process.argv[1]?.endsWith("admin-m2-read-model.selftest.js"))runAdminM2ReadModelSelfTest().then(()=>console.log("admin M2 read model selftest passed"));
