import { repositoryErr, repositoryOk, type RepositoryResult } from "../../../core/persistence";
import type { ReadQueryTransport } from "../../../infrastructure/supabase/read-query-transport";

export type AdminStudentsBrandFilter = "all" | "medway" | "elite" | "nexus";
export type AdminStudentsStatusFilter = "active" | "pending" | "disabled" | "suspended";
export interface AdminStudentReadItem { readonly id: string; readonly platform: { readonly platformId: string; readonly platformCode: "medway" | "elite" | "nexus"; readonly platformDisplayName: string }; readonly displayName: null; readonly emailMasked: null; readonly phoneMasked: null; readonly academicTermOrYear: null; readonly university: null; readonly studentIdMasked: null; readonly status: "active" | "disabled"; readonly activeSubscriptionCount: null; readonly activeGrantCount: null; readonly activeDeviceCount: null; readonly activeSessionCount: null; readonly lastSeenAt: null; readonly riskFlags: readonly ["none"]; }
export interface AdminStudentReadDetail extends AdminStudentReadItem { readonly createdAt: string; readonly updatedAt: string; readonly access: { readonly activeSubscriptionCount: null; readonly activeSeatCount: null; readonly activeGrantCount: null; readonly expiredGrantCount: null; readonly revokedGrantCount: null; readonly enrollmentCount: null }; readonly learning: { readonly enrollmentCount: null; readonly completedLessonCount: null; readonly attemptCount: null; readonly playbackSessionCount: null; readonly lastLearningActivityAt: null }; readonly devices: readonly []; readonly sessions: readonly []; }
export interface AdminStudentsPageResult { readonly data: readonly AdminStudentReadItem[]; readonly pagination: { readonly page: number; readonly pageSize: number; readonly totalItems: number; readonly totalPages: number }; }
export interface AdminStudentsReadModel { listStudents(input: { readonly brand: AdminStudentsBrandFilter; readonly search?: string; readonly status?: AdminStudentsStatusFilter; readonly page: number; readonly pageSize: number; readonly correlationId?: string }): Promise<RepositoryResult<AdminStudentsPageResult>>; findStudent(input: { readonly studentId: string; readonly brand: AdminStudentsBrandFilter; readonly correlationId?: string }): Promise<RepositoryResult<AdminStudentReadDetail>>; }

const commercial = ["medway", "elite", "nexus"] as const;
const unavailable = <T>(message: string, correlationId?: string): RepositoryResult<T> => repositoryErr({ code: "provider_unavailable", message, correlationId });
const number = (value: unknown) => { const parsed = typeof value === "number" ? value : Number(value); if (!Number.isSafeInteger(parsed) || parsed < 0) throw new Error("number"); return parsed; };
const string = (row: Readonly<Record<string, unknown>>, key: string) => { const value = row[key]; if (typeof value !== "string" || !value) throw new Error(key); return value; };
const item = (row: Readonly<Record<string, unknown>>): AdminStudentReadItem => ({ id: string(row, "id"), platform: { platformId: string(row, "brand_id"), platformCode: string(row, "brand_code") as "medway" | "elite" | "nexus", platformDisplayName: string(row, "brand_name") }, displayName: null, emailMasked: null, phoneMasked: null, academicTermOrYear: null, university: null, studentIdMasked: null, status: string(row, "status") === "active" ? "active" : "disabled", activeSubscriptionCount: null, activeGrantCount: null, activeDeviceCount: null, activeSessionCount: null, lastSeenAt: null, riskFlags: ["none"] });
const brandArray = (brand: AdminStudentsBrandFilter) => brand === "all" ? commercial : [brand];

export class EmptyAdminStudentsReadModel implements AdminStudentsReadModel { async listStudents(input: Parameters<AdminStudentsReadModel["listStudents"]>[0]) { return repositoryOk({ data: [], pagination: { page: input.page, pageSize: input.pageSize, totalItems: 0, totalPages: 0 } }); } async findStudent(input: Parameters<AdminStudentsReadModel["findStudent"]>[0]) { return repositoryErr({ code: "not_found", message: "The requested student was not found.", correlationId: input.correlationId }); } }
export class PostgresAdminStudentsReadModel implements AdminStudentsReadModel {
  constructor(private readonly transport: ReadQueryTransport) {}
  async listStudents(input: Parameters<AdminStudentsReadModel["listStudents"]>[0]): Promise<RepositoryResult<AdminStudentsPageResult>> { try { const search = input.search?.trim() ?? ""; const codes = brandArray(input.brand); const status = input.status === "active" ? "active" : input.status ? "inactive" : ""; const clause = "from app.student_profiles sp join app.educational_brands eb on eb.id=sp.brand_id where eb.code = any(string_to_array($1, ',')) and ($2='' or sp.id::text ilike '%' || $2 || '%') and ($3='' or sp.status = $3)"; const count = await this.transport.query({ label: "admin.students.count", text: `select count(*)::text as total ${clause}`, values: [codes.join(","), search, status] }); const totalItems = number(count.rows[0]?.total); const offset = String((input.page - 1) * input.pageSize); const rows = await this.transport.query({ label: "admin.students.list", text: `select sp.id, sp.status, sp.created_at, eb.id as brand_id, eb.code as brand_code, eb.name as brand_name ${clause} order by sp.created_at desc, sp.id asc limit $4 offset $5`, values: [codes.join(","), search, status, String(input.pageSize), offset] }); return repositoryOk({ data: rows.rows.map(item), pagination: { page: input.page, pageSize: input.pageSize, totalItems, totalPages: totalItems ? Math.ceil(totalItems / input.pageSize) : 0 } }); } catch { return unavailable("Student records could not be read from the private data store.", input.correlationId); } }
  async findStudent(input: Parameters<AdminStudentsReadModel["findStudent"]>[0]): Promise<RepositoryResult<AdminStudentReadDetail>> { try { const rows = await this.transport.query({ label: "admin.students.detail", text: "select sp.id, sp.status, sp.created_at, sp.updated_at, eb.id as brand_id, eb.code as brand_code, eb.name as brand_name from app.student_profiles sp join app.educational_brands eb on eb.id=sp.brand_id where sp.id=$1 and eb.code = any(string_to_array($2, ','))", values: [input.studentId, brandArray(input.brand).join(",")] }); const row = rows.rows[0]; if (!row) return repositoryErr({ code: "not_found", message: "The requested student was not found.", correlationId: input.correlationId }); const base = item(row); return repositoryOk({ ...base, createdAt: string(row, "created_at"), updatedAt: string(row, "updated_at"), access: { activeSubscriptionCount: null, activeSeatCount: null, activeGrantCount: null, expiredGrantCount: null, revokedGrantCount: null, enrollmentCount: null }, learning: { enrollmentCount: null, completedLessonCount: null, attemptCount: null, playbackSessionCount: null, lastLearningActivityAt: null }, devices: [], sessions: [] }); } catch { return unavailable("Student details could not be read from the private data store.", input.correlationId); } }
}
