import { repositoryErr, repositoryOk, type RepositoryResult } from "../../../core/persistence";
import type { BrandScope } from "../../../core/brand-scope";
import type { M1EducationalBrandReadRepository, M2ReadRepositories } from "../../../core/repositories";
import type { AdminM2ReadModel, AcademicLevelAdminDto, AcademicSemesterAdminDto, AcademicModuleAdminDto, InstructorAdminDto, BrandInstructorAdminDto, BrandCourseAdminDto, CourseInstructorAdminDto } from "./admin-m2-read-model";

const levels = (v: import("../../../core/repositories").M2AcademicLevel): AcademicLevelAdminDto => ({ id:v.id, levelNumber:v.levelNumber, displayName:v.displayName, status:v.status, sortOrder:v.sortOrder });
const semesters = (v: import("../../../core/repositories").M2AcademicSemester): AcademicSemesterAdminDto => ({ id:v.id, academicLevelId:v.levelId, semesterNumber:v.semesterNumber, displayName:v.displayName, phase:v.phase, status:v.status, sortOrder:v.sortOrder });
const modules = (v: import("../../../core/repositories").M2AcademicModule): AcademicModuleAdminDto => ({ id:v.id, academicSemesterId:v.semesterId, moduleCode:v.moduleCode, title:v.title, status:v.status, sortOrder:v.sortOrder });
const instructors = (v: import("../../../core/repositories").M2Instructor): InstructorAdminDto => ({ id:v.id, displayName:v.displayName, professionalTitle:v.professionalTitle, status:v.status, createdAt:v.createdAt, updatedAt:v.updatedAt });
const brandInstructors = (v: import("../../../core/repositories").M2BrandInstructor): BrandInstructorAdminDto => ({ ...v });
const courses = (v: import("../../../core/repositories").M2BrandCourse): BrandCourseAdminDto => ({ ...v });
const assignments = (v: import("../../../core/repositories").M2CourseInstructor): CourseInstructorAdminDto => ({ ...v });
function mapOne<A, B>(result: RepositoryResult<A>, mapper: (value: A) => B): RepositoryResult<B> { return result.ok ? repositoryOk(mapper(result.value)) : result; }
function mapMany<A, B>(result: RepositoryResult<readonly A[]>, mapper: (value: A) => B): RepositoryResult<readonly B[]> { return result.ok ? repositoryOk(result.value.map(mapper)) : result; }

export class PostgresAdminM2ReadModel implements AdminM2ReadModel {
  constructor(private readonly educationalBrands: M1EducationalBrandReadRepository, private readonly repositories: M2ReadRepositories) {}
  private async brand(brandId: string, correlationId?: string): Promise<RepositoryResult<BrandScope>> {
    const result = await this.educationalBrands.findEducationalBrandById({ id: brandId, correlationId });
    if (!result.ok || result.value.status !== "active") return repositoryErr({ code: "not_found", message: "The requested brand was not found.", correlationId });
    return repositoryOk({ brandId: result.value.id as BrandScope["brandId"], brandCode: result.value.code, brandDisplayName: result.value.name, isActive: true });
  }
  async listAcademicLevels(input: { readonly correlationId?: string } = {}) { return mapMany(await this.repositories.academicLevels.listAcademicLevels(input), levels); }
  async listAcademicSemesters(input: { readonly levelId?: string; readonly correlationId?: string }) { return mapMany(input.levelId ? await this.repositories.academicSemesters.listAcademicSemestersByLevelId({ levelId:input.levelId, correlationId:input.correlationId }) : await this.repositories.academicSemesters.listAcademicSemesters({ correlationId:input.correlationId }), semesters); }
  async listAcademicModules(input: { readonly semesterId?: string; readonly correlationId?: string }) { return mapMany(input.semesterId ? await this.repositories.academicModules.listAcademicModulesBySemesterId({ semesterId:input.semesterId, correlationId:input.correlationId }) : await this.repositories.academicModules.listAcademicModules({ correlationId:input.correlationId }), modules); }
  async findAcademicModule(input: { readonly moduleId: string; readonly correlationId?: string }) { return mapOne(await this.repositories.academicModules.findAcademicModuleById({ id:input.moduleId, correlationId:input.correlationId }), modules); }
  async listInstructors(input: { readonly correlationId?: string } = {}) { return mapMany(await this.repositories.instructors.listInstructors(input), instructors); }
  async findInstructor(input: { readonly instructorId: string; readonly correlationId?: string }) { return mapOne(await this.repositories.instructors.findInstructorById({ id:input.instructorId, correlationId:input.correlationId }), instructors); }
  async listBrandInstructors(input: { readonly brandId: string; readonly correlationId?: string }) { const brand=await this.brand(input.brandId,input.correlationId); return brand.ok ? mapMany(await this.repositories.brandInstructors.listBrandInstructors({brand:brand.value,correlationId:input.correlationId}),brandInstructors) : brand; }
  async findBrandInstructor(input: { readonly brandId: string; readonly instructorId: string; readonly correlationId?: string }) { const brand=await this.brand(input.brandId,input.correlationId); return brand.ok ? mapOne(await this.repositories.brandInstructors.findBrandInstructor({brand:brand.value,instructorId:input.instructorId,correlationId:input.correlationId}),brandInstructors) : brand; }
  async listBrandCourses(input: { readonly brandId: string; readonly academicModuleId?: string; readonly scope?: "standalone"; readonly correlationId?: string }) { const brand=await this.brand(input.brandId,input.correlationId); if(!brand.ok)return brand; const result=input.academicModuleId ? await this.repositories.brandCourses.listBrandCoursesByAcademicModule({brand:brand.value,academicModuleId:input.academicModuleId,correlationId:input.correlationId}) : input.scope === "standalone" ? await this.repositories.brandCourses.listStandaloneBrandCourses({brand:brand.value,correlationId:input.correlationId}) : await this.repositories.brandCourses.listBrandCourses({brand:brand.value,correlationId:input.correlationId}); return mapMany(result,courses); }
  async findBrandCourse(input: { readonly brandId: string; readonly courseId: string; readonly correlationId?: string }) { const brand=await this.brand(input.brandId,input.correlationId); return brand.ok ? mapOne(await this.repositories.brandCourses.findBrandCourseById({brand:brand.value,courseId:input.courseId,correlationId:input.correlationId}),courses) : brand; }
  async listCourseInstructors(input: { readonly brandId: string; readonly courseId: string; readonly correlationId?: string }) { const brand=await this.brand(input.brandId,input.correlationId); return brand.ok ? mapMany(await this.repositories.courseInstructors.listCourseInstructors({brand:brand.value,courseId:input.courseId,correlationId:input.correlationId}),assignments) : brand; }
  async listInstructorCourseAssignments(input: { readonly brandId: string; readonly instructorId: string; readonly correlationId?: string }) { const brand=await this.brand(input.brandId,input.correlationId); return brand.ok ? mapMany(await this.repositories.courseInstructors.listInstructorCourseAssignments({brand:brand.value,instructorId:input.instructorId,correlationId:input.correlationId}),assignments) : brand; }
}
