import { repositoryErr, repositoryOk, type RepositoryResult } from "../../../core/persistence";
import type { BrandScope } from "../../../core/brand-scope";
import type { M1EducationalBrandReadRepository, M2ReadRepositories } from "../../../core/repositories";
import type { AdminM2ReadModel } from "./admin-m2-read-model";

const identity = <T>(value: T): T => value;
function mapOne<A, B>(result: RepositoryResult<A>, mapper: (value: A) => B): RepositoryResult<B> { return result.ok ? repositoryOk(mapper(result.value)) : result; }
function mapMany<A, B>(result: RepositoryResult<readonly A[]>, mapper: (value: A) => B): RepositoryResult<readonly B[]> { return result.ok ? repositoryOk(result.value.map(mapper)) : result; }

export class PostgresAdminM2ReadModel implements AdminM2ReadModel {
  constructor(private readonly educationalBrands: M1EducationalBrandReadRepository, private readonly repositories: M2ReadRepositories) {}
  private async brand(brandId: string, correlationId?: string): Promise<RepositoryResult<BrandScope>> { const result=await this.educationalBrands.findEducationalBrandById({id:brandId,correlationId}); if(!result.ok||result.value.status!=="active")return repositoryErr({code:"not_found",message:"The requested brand was not found.",correlationId}); return repositoryOk({brandId:result.value.id as BrandScope["brandId"],brandCode:result.value.code,brandDisplayName:result.value.name,isActive:true}); }
  async listAcademicLevels(input:{readonly correlationId?:string}={}){return mapMany(await this.repositories.academicLevels.listAcademicLevels(input),identity);}
  async listAcademicSemesters(input:{readonly levelId?:string;readonly correlationId?:string}){return mapMany(input.levelId?await this.repositories.academicSemesters.listAcademicSemestersByLevelId({levelId:input.levelId,correlationId:input.correlationId}):await this.repositories.academicSemesters.listAcademicSemesters({correlationId:input.correlationId}),identity);}
  async listAcademicModules(input:{readonly semesterId?:string;readonly correlationId?:string}){return mapMany(input.semesterId?await this.repositories.academicModules.listAcademicModulesBySemesterId({semesterId:input.semesterId,correlationId:input.correlationId}):await this.repositories.academicModules.listAcademicModules({correlationId:input.correlationId}),identity);}
  async findAcademicModule(input:{readonly moduleId:string;readonly correlationId?:string}){return mapOne(await this.repositories.academicModules.findAcademicModuleById({id:input.moduleId,correlationId:input.correlationId}),identity);}
  async listInstructors(input:{readonly correlationId?:string}={}){return mapMany(await this.repositories.instructors.listInstructors(input),identity);}
  async findInstructor(input:{readonly instructorId:string;readonly correlationId?:string}){return mapOne(await this.repositories.instructors.findInstructorById({id:input.instructorId,correlationId:input.correlationId}),identity);}
  async listInstructorBrandAssignments(input:{readonly instructorId:string;readonly correlationId?:string}){return mapMany(await this.repositories.instructorBrandAssignments.listInstructorBrands(input),identity);}
  async listBrandInstructors(input:{readonly brandId:string;readonly correlationId?:string}){const brand=await this.brand(input.brandId,input.correlationId);return brand.ok?mapMany(await this.repositories.instructorBrandAssignments.listBrandAssignments({brand:brand.value,correlationId:input.correlationId}),identity):brand;}
  async findBrandInstructor(input:{readonly brandId:string;readonly instructorId:string;readonly correlationId?:string}){const brand=await this.brand(input.brandId,input.correlationId);return brand.ok?mapOne(await this.repositories.instructorBrandAssignments.findBrandAssignment({brand:brand.value,instructorId:input.instructorId,correlationId:input.correlationId}),identity):brand;}
  async listBrandCourses(input:{readonly brandId:string;readonly academicModuleId?:string;readonly scope?:"standalone";readonly correlationId?:string}){const brand=await this.brand(input.brandId,input.correlationId);if(!brand.ok)return brand;const result=input.academicModuleId?await this.repositories.brandCourses.listBrandCoursesByAcademicModule({brand:brand.value,academicModuleId:input.academicModuleId,correlationId:input.correlationId}):input.scope==="standalone"?await this.repositories.brandCourses.listStandaloneBrandCourses({brand:brand.value,correlationId:input.correlationId}):await this.repositories.brandCourses.listBrandCourses({brand:brand.value,correlationId:input.correlationId});return mapMany(result,identity);}
  async findBrandCourse(input:{readonly brandId:string;readonly courseId:string;readonly correlationId?:string}){const brand=await this.brand(input.brandId,input.correlationId);return brand.ok?mapOne(await this.repositories.brandCourses.findBrandCourseById({brand:brand.value,courseId:input.courseId,correlationId:input.correlationId}),identity):brand;}
  async listCourseInstructors(input:{readonly brandId:string;readonly courseId:string;readonly correlationId?:string}){const brand=await this.brand(input.brandId,input.correlationId);return brand.ok?mapMany(await this.repositories.courseInstructorAssignments.listCourseInstructors({brand:brand.value,courseId:input.courseId,correlationId:input.correlationId}),identity):brand;}
  async listInstructorCourseAssignments(input:{readonly brandId:string;readonly instructorId:string;readonly correlationId?:string}){const brand=await this.brand(input.brandId,input.correlationId);return brand.ok?mapMany(await this.repositories.courseInstructorAssignments.listInstructorCourseAssignments({brand:brand.value,instructorId:input.instructorId,correlationId:input.correlationId}),identity):brand;}
  async listCourseChapters(input:{readonly brandId:string;readonly courseId:string;readonly correlationId?:string}){const brand=await this.brand(input.brandId,input.correlationId);if(!brand.ok)return brand;if(!this.repositories.courseDelivery)return repositoryErr({code:"provider_unavailable",message:"Course delivery read model is unavailable.",correlationId:input.correlationId});return mapMany(await this.repositories.courseDelivery.listChapters({brand:brand.value,courseId:input.courseId,correlationId:input.correlationId}),identity);}
  async listCourseLessons(input:{readonly brandId:string;readonly courseId:string;readonly correlationId?:string}){const brand=await this.brand(input.brandId,input.correlationId);if(!brand.ok)return brand;if(!this.repositories.courseDelivery)return repositoryErr({code:"provider_unavailable",message:"Course delivery read model is unavailable.",correlationId:input.correlationId});return mapMany(await this.repositories.courseDelivery.listLessons({brand:brand.value,courseId:input.courseId,correlationId:input.correlationId}),identity);}
  async listLessonResources(input:{readonly brandId:string;readonly courseId:string;readonly correlationId?:string}){const brand=await this.brand(input.brandId,input.correlationId);if(!brand.ok)return brand;if(!this.repositories.courseDelivery)return repositoryErr({code:"provider_unavailable",message:"Course delivery read model is unavailable.",correlationId:input.correlationId});return mapMany(await this.repositories.courseDelivery.listResources({brand:brand.value,courseId:input.courseId,correlationId:input.correlationId}),identity);}
}
