import type { BrandScope } from "../brand-scope";
import type { RepositoryResult } from "../persistence";

interface Versioned { readonly id:string; readonly createdAt:string; readonly updatedAt:string; readonly version?:number; }
export interface M1EducationalBrand extends Versioned { readonly code:"medway"|"elite"; readonly name:string; readonly slug:string; readonly status:"active"|"inactive"; }
export interface M1AppUser extends Versioned { readonly authUserId:string; readonly primaryEmail:string|null; readonly primaryPhone:string|null; readonly status:"pending"|"active"|"suspended"|"disabled"|"anonymized"; }
export interface M1BrandMembership extends Versioned { readonly brandId:string; readonly appUserId:string; readonly status:"pending"|"active"|"suspended"|"ended"|"revoked"|"pending_payment"|"pending_review"|"expired"|"cancelled"|"rejected"; readonly validFrom?:string; readonly validUntil?:string|null; readonly membershipType?:"student"|"admin_candidate"|"staff"; readonly activatedAt?:string|null; readonly suspendedAt?:string|null; readonly expiredAt?:string|null; readonly cancelledAt?:string|null; readonly rejectedAt?:string|null; }
export interface M1StudentProfile extends Versioned { readonly brandId:string; readonly appUserId:string; readonly brandMembershipId:string; readonly status:"active"|"inactive"|"archived"|"pending"|"suspended"; readonly fullName?:string; readonly phone?:string|null; readonly email?:string|null; readonly academicYear?:string|null; readonly academicTerm?:string|null; readonly university?:string|null; readonly studentId?:string|null; }
export interface M1AdminProfile extends Versioned { readonly appUserId:string; readonly status:"active"|"suspended"|"disabled"|"revoked"; readonly brandId?:string; readonly displayName?:string; }
export interface M1AdminAuthorizationSnapshot { readonly appUser:M1AppUser; readonly adminProfile:M1AdminProfile; readonly roleCodes:readonly string[]; readonly permissionCodes:readonly string[]; }
export interface M1AdminPermission extends Versioned { readonly code:string; readonly description:string|null; readonly status:"active"|"retired"|"deprecated"|"disabled"; readonly category?:string; }
export interface M1AdminRole extends Versioned { readonly code:string; readonly name:string; readonly assignmentScope?:"platform"; readonly status:"active"|"retired"|"disabled"|"archived"; readonly brandId?:string; readonly description?:string|null; }
export interface M1AdminRolePermission { readonly roleId:string; readonly permissionId:string; readonly createdAt:string; }
export interface M1AdminRoleAssignment extends Versioned { readonly adminProfileId:string; readonly roleId:string; readonly assignedByAdminProfileId:string|null; readonly validFrom?:string; readonly validUntil?:string|null; readonly status:"active"|"inactive"|"expired"|"revoked"; readonly brandId?:string; readonly assignedAt?:string; readonly revokedAt?:string|null; }

export interface M1EducationalBrandReadRepository { findEducationalBrandById(input:{readonly id:string;readonly correlationId?:string}):Promise<RepositoryResult<M1EducationalBrand>>; findEducationalBrandByCode(input:{readonly code:"medway"|"elite";readonly correlationId?:string}):Promise<RepositoryResult<M1EducationalBrand>>; }
export interface M1AppUserReadRepository { findAppUserById(input:{readonly id:string;readonly correlationId?:string}):Promise<RepositoryResult<M1AppUser>>; findAppUserByAuthUserId(input:{readonly authUserId:string;readonly correlationId?:string}):Promise<RepositoryResult<M1AppUser>>; }
export interface M1BrandMembershipReadRepository { findBrandMembershipByUserId(input:{readonly appUserId:string;readonly brand:BrandScope;readonly correlationId?:string}):Promise<RepositoryResult<M1BrandMembership>>; }
export interface M1StudentProfileReadRepository { findStudentProfileById(input:{readonly id:string;readonly brand:BrandScope;readonly correlationId?:string}):Promise<RepositoryResult<M1StudentProfile>>; findStudentProfileByUserId(input:{readonly appUserId:string;readonly brand:BrandScope;readonly correlationId?:string}):Promise<RepositoryResult<M1StudentProfile>>; listStudentProfilesByBrand(input:{readonly brand:BrandScope;readonly correlationId?:string}):Promise<RepositoryResult<readonly M1StudentProfile[]>>; }
export interface M1AdminProfileReadRepository { findAdminProfileById(input:{readonly id:string;readonly brand:BrandScope;readonly correlationId?:string}):Promise<RepositoryResult<M1AdminProfile>>; findAdminProfileByUserId(input:{readonly appUserId:string;readonly brand:BrandScope;readonly correlationId?:string}):Promise<RepositoryResult<M1AdminProfile>>; resolveAdminAuthorizationByAuthUserId(input:{readonly authUserId:string;readonly brand:BrandScope;readonly correlationId?:string}):Promise<RepositoryResult<M1AdminAuthorizationSnapshot>>; listAdminAuthorizationsByAuthUserId(input:{readonly authUserId:string;readonly correlationId?:string}):Promise<RepositoryResult<readonly M1AdminAuthorizationSnapshot[]>>; }
export interface M1AdminRoleReadRepository { findAdminRoleById(input:{readonly id:string;readonly brand:BrandScope;readonly correlationId?:string}):Promise<RepositoryResult<M1AdminRole>>; listAdminRolesByBrand(input:{readonly brand:BrandScope;readonly correlationId?:string}):Promise<RepositoryResult<readonly M1AdminRole[]>>; }
export interface M1AdminPermissionReadRepository { findAdminPermissionById(input:{readonly id:string;readonly correlationId?:string}):Promise<RepositoryResult<M1AdminPermission>>; findAdminPermissionByCode(input:{readonly code:string;readonly correlationId?:string}):Promise<RepositoryResult<M1AdminPermission>>; }
export interface M1AdminRolePermissionReadRepository { listAdminRolePermissions(input:{readonly roleId:string;readonly brand:BrandScope;readonly correlationId?:string}):Promise<RepositoryResult<readonly M1AdminRolePermission[]>>; }
export interface M1AdminRoleAssignmentReadRepository { listAdminRoleAssignmentsForProfile(input:{readonly adminProfileId:string;readonly brand:BrandScope;readonly correlationId?:string}):Promise<RepositoryResult<readonly M1AdminRoleAssignment[]>>; }
