import type { BrandScope } from "../brand-scope";
import type { RepositoryResult } from "../persistence";

export interface M2AcademicLevel { readonly id: string; readonly levelNumber: number; readonly displayName: string; readonly sortOrder: number; readonly status: "active" | "inactive"; readonly createdAt: string; readonly updatedAt: string; }
export interface M2AcademicSemester { readonly id: string; readonly levelId: string; readonly semesterNumber: number; readonly displayName: string; readonly phase: "phase_i" | "phase_ii"; readonly sortOrder: number; readonly status: "active" | "inactive"; readonly createdAt: string; readonly updatedAt: string; }
export interface M2AcademicModule { readonly id: string; readonly semesterId: string; readonly moduleCode: string; readonly title: string; readonly sortOrder: number; readonly status: "active" | "inactive"; readonly createdAt: string; readonly updatedAt: string; }
export interface M2Instructor { readonly id: string; readonly displayName: string; readonly professionalTitle: string | null; readonly status: "active" | "inactive"; readonly createdAt: string; readonly updatedAt: string; }
export interface M2BrandInstructor { readonly id: string; readonly brandId: string; readonly instructorId: string; readonly status: "active" | "inactive"; readonly createdAt: string; readonly updatedAt: string; }
export interface M2BrandCourse { readonly id: string; readonly brandId: string; readonly academicModuleId: string | null; readonly courseCode: string; readonly title: string; readonly courseScope: "curriculum" | "standalone"; readonly status: "draft" | "published" | "archived"; readonly createdAt: string; readonly updatedAt: string; }
export interface M2CourseInstructor { readonly id: string; readonly courseId: string; readonly brandId: string; readonly instructorId: string; readonly status: "active" | "inactive"; readonly createdAt: string; readonly updatedAt: string; }
type Correlated = { readonly correlationId?: string };
export interface M2AcademicLevelReadRepository { findAcademicLevelById(input: { readonly id: string } & Correlated): Promise<RepositoryResult<M2AcademicLevel>>; listAcademicLevels(input?: Correlated): Promise<RepositoryResult<readonly M2AcademicLevel[]>>; }
export interface M2AcademicSemesterReadRepository { findAcademicSemesterById(input: { readonly id: string } & Correlated): Promise<RepositoryResult<M2AcademicSemester>>; listAcademicSemesters(input?: Correlated): Promise<RepositoryResult<readonly M2AcademicSemester[]>>; listAcademicSemestersByLevelId(input: { readonly levelId: string } & Correlated): Promise<RepositoryResult<readonly M2AcademicSemester[]>>; }
export interface M2AcademicModuleReadRepository { findAcademicModuleById(input: { readonly id: string } & Correlated): Promise<RepositoryResult<M2AcademicModule>>; findAcademicModuleByCode(input: { readonly moduleCode: string } & Correlated): Promise<RepositoryResult<M2AcademicModule>>; listAcademicModules(input?: Correlated): Promise<RepositoryResult<readonly M2AcademicModule[]>>; listAcademicModulesBySemesterId(input: { readonly semesterId: string } & Correlated): Promise<RepositoryResult<readonly M2AcademicModule[]>>; }
export interface M2InstructorReadRepository { findInstructorById(input: { readonly id: string } & Correlated): Promise<RepositoryResult<M2Instructor>>; listInstructors(input?: Correlated): Promise<RepositoryResult<readonly M2Instructor[]>>; }
export interface M2BrandInstructorReadRepository { listBrandInstructors(input: { readonly brand: BrandScope } & Correlated): Promise<RepositoryResult<readonly M2BrandInstructor[]>>; findBrandInstructor(input: { readonly brand: BrandScope; readonly instructorId: string } & Correlated): Promise<RepositoryResult<M2BrandInstructor>>; listInstructorBrands(input: { readonly instructorId: string } & Correlated): Promise<RepositoryResult<readonly M2BrandInstructor[]>>; }
export interface M2BrandCourseReadRepository { findBrandCourseById(input: { readonly brand: BrandScope; readonly courseId: string } & Correlated): Promise<RepositoryResult<M2BrandCourse>>; findBrandCourseByCode(input: { readonly brand: BrandScope; readonly courseCode: string } & Correlated): Promise<RepositoryResult<M2BrandCourse>>; listBrandCourses(input: { readonly brand: BrandScope } & Correlated): Promise<RepositoryResult<readonly M2BrandCourse[]>>; listBrandCoursesByAcademicModule(input: { readonly brand: BrandScope; readonly academicModuleId: string } & Correlated): Promise<RepositoryResult<readonly M2BrandCourse[]>>; listStandaloneBrandCourses(input: { readonly brand: BrandScope } & Correlated): Promise<RepositoryResult<readonly M2BrandCourse[]>>; }
export interface M2CourseInstructorReadRepository { listCourseInstructors(input: { readonly brand: BrandScope; readonly courseId: string } & Correlated): Promise<RepositoryResult<readonly M2CourseInstructor[]>>; listInstructorCourseAssignments(input: { readonly brand: BrandScope; readonly instructorId: string } & Correlated): Promise<RepositoryResult<readonly M2CourseInstructor[]>>; }
export interface M2ReadRepositories { readonly academicLevels: M2AcademicLevelReadRepository; readonly academicSemesters: M2AcademicSemesterReadRepository; readonly academicModules: M2AcademicModuleReadRepository; readonly instructors: M2InstructorReadRepository; readonly brandInstructors: M2BrandInstructorReadRepository; readonly brandCourses: M2BrandCourseReadRepository; readonly courseInstructors: M2CourseInstructorReadRepository; }
