import type { BrandScope } from "../brand-scope";
import type { RepositoryResult } from "../persistence";

export type M2CatalogueStatus = "active" | "retired";
export type M2InstructorStatus = "active" | "inactive" | "archived";
export type M2AssignmentStatus = "active" | "inactive";
export type M2AcademicReviewStatus = "unreviewed" | "approved" | "blocked" | "retired";
export type M2BrandCourseClassification = "academic_module_offering" | "standalone";
export type M2BrandCourseStatus = "draft" | "published" | "archived";

interface VersionedRecord { readonly id: string; readonly createdAt: string; readonly updatedAt: string; readonly version: number; }
export interface M2AcademicLevel extends VersionedRecord { readonly levelNumber: number; readonly displayTitle: string; readonly sortOrder: number; readonly status: M2CatalogueStatus; }
export interface M2AcademicSemester extends VersionedRecord { readonly academicLevelId: string; readonly semesterNumber: number; readonly displayTitle: string; readonly sortOrder: number; readonly status: M2CatalogueStatus; }
export interface M2AcademicModule extends VersionedRecord { readonly academicSemesterId: string; readonly code: string; readonly normalizedCode: string; readonly sourceDisplayLabel: string; readonly sortOrder: number; readonly reviewStatus: M2AcademicReviewStatus; }
export interface M2AcademicModuleAlias extends VersionedRecord { readonly academicModuleId: string; readonly aliasValue: string; readonly normalizedAlias: string; readonly status: M2CatalogueStatus; }
export interface M2Instructor extends VersionedRecord { readonly code: string; readonly instructorCode: string; readonly displayName: string; readonly status: M2InstructorStatus; }
export interface M2InstructorBrandAssignment extends VersionedRecord { readonly brandId: string; readonly instructorId: string; readonly status: M2AssignmentStatus; }
export interface M2BrandCourse extends VersionedRecord { readonly brandId: string; readonly academicModuleId: string | null; readonly code: string; readonly title: string; readonly classification: M2BrandCourseClassification; readonly status: M2BrandCourseStatus; }
export interface M2CourseInstructorAssignment extends VersionedRecord { readonly courseId: string; readonly brandId: string; readonly instructorBrandAssignmentId: string; readonly instructorId: string; readonly status: M2AssignmentStatus; }

type Correlated = { readonly correlationId?: string };
export interface M2AcademicLevelReadRepository { findAcademicLevelById(input: { readonly id: string } & Correlated): Promise<RepositoryResult<M2AcademicLevel>>; listAcademicLevels(input?: Correlated): Promise<RepositoryResult<readonly M2AcademicLevel[]>>; }
export interface M2AcademicSemesterReadRepository { findAcademicSemesterById(input: { readonly id: string } & Correlated): Promise<RepositoryResult<M2AcademicSemester>>; listAcademicSemesters(input?: Correlated): Promise<RepositoryResult<readonly M2AcademicSemester[]>>; listAcademicSemestersByLevelId(input: { readonly levelId: string } & Correlated): Promise<RepositoryResult<readonly M2AcademicSemester[]>>; }
export interface M2AcademicModuleReadRepository { findAcademicModuleById(input: { readonly id: string } & Correlated): Promise<RepositoryResult<M2AcademicModule>>; findAcademicModuleByCode(input: { readonly moduleCode: string } & Correlated): Promise<RepositoryResult<M2AcademicModule>>; listAcademicModules(input?: Correlated): Promise<RepositoryResult<readonly M2AcademicModule[]>>; listAcademicModulesBySemesterId(input: { readonly semesterId: string } & Correlated): Promise<RepositoryResult<readonly M2AcademicModule[]>>; }
export interface M2AcademicModuleAliasReadRepository { findAcademicModuleAlias(input: ({ readonly normalizedAlias: string } | { readonly normalizedComparisonValue: string }) & Correlated): Promise<RepositoryResult<M2AcademicModuleAlias>>; }
export interface M2InstructorReadRepository { findInstructorById(input: { readonly id: string } & Correlated): Promise<RepositoryResult<M2Instructor>>; findInstructorByCode(input: { readonly instructorCode: string } & Correlated): Promise<RepositoryResult<M2Instructor>>; listInstructors(input?: Correlated): Promise<RepositoryResult<readonly M2Instructor[]>>; }
export interface M2InstructorBrandAssignmentReadRepository { listBrandAssignments(input: { readonly brand: BrandScope } & Correlated): Promise<RepositoryResult<readonly M2InstructorBrandAssignment[]>>; findBrandAssignment(input: { readonly brand: BrandScope; readonly instructorId: string } & Correlated): Promise<RepositoryResult<M2InstructorBrandAssignment>>; listInstructorBrands(input: { readonly instructorId: string } & Correlated): Promise<RepositoryResult<readonly M2InstructorBrandAssignment[]>>; /** @deprecated */ listBrandInstructors?(input: { readonly brand: BrandScope } & Correlated): Promise<RepositoryResult<readonly M2InstructorBrandAssignment[]>>; /** @deprecated */ findBrandInstructor?(input: { readonly brand: BrandScope; readonly instructorId: string } & Correlated): Promise<RepositoryResult<M2InstructorBrandAssignment>>; }
export interface M2BrandCourseReadRepository { findBrandCourseById(input: { readonly brand: BrandScope; readonly courseId: string } & Correlated): Promise<RepositoryResult<M2BrandCourse>>; findBrandCourseByCode(input: { readonly brand: BrandScope; readonly courseCode: string } & Correlated): Promise<RepositoryResult<M2BrandCourse>>; listBrandCourses(input: { readonly brand: BrandScope } & Correlated): Promise<RepositoryResult<readonly M2BrandCourse[]>>; listBrandCoursesByAcademicModule(input: { readonly brand: BrandScope; readonly academicModuleId: string } & Correlated): Promise<RepositoryResult<readonly M2BrandCourse[]>>; listStandaloneBrandCourses(input: { readonly brand: BrandScope } & Correlated): Promise<RepositoryResult<readonly M2BrandCourse[]>>; }
export interface M2CourseInstructorAssignmentReadRepository { listCourseInstructors(input: { readonly brand: BrandScope; readonly courseId: string } & Correlated): Promise<RepositoryResult<readonly M2CourseInstructorAssignment[]>>; listInstructorCourseAssignments(input: { readonly brand: BrandScope; readonly instructorId: string } & Correlated): Promise<RepositoryResult<readonly M2CourseInstructorAssignment[]>>; }
export type M2bContentStatus = "draft" | "published" | "archived";
export type M2bResourceKind = "video" | "document" | "quiz" | "link" | "file";
export interface M2bChapter extends VersionedRecord { readonly brandCourseId: string; readonly title: string; readonly sortOrder: number; readonly status: M2bContentStatus; }
export interface M2bLesson extends VersionedRecord { readonly brandCourseId: string; readonly courseChapterId: string; readonly title: string; readonly sortOrder: number; readonly status: M2bContentStatus; }
export interface M2bResource extends VersionedRecord { readonly brandCourseId: string; readonly courseLessonId: string; readonly resourceKind: M2bResourceKind; readonly title: string; readonly sortOrder: number; readonly status: M2bContentStatus; }
export interface M2bCourseDeliveryReadRepository { listChapters(input: { readonly brand: BrandScope; readonly courseId: string } & Correlated): Promise<RepositoryResult<readonly M2bChapter[]>>; listLessons(input: { readonly brand: BrandScope; readonly courseId: string } & Correlated): Promise<RepositoryResult<readonly M2bLesson[]>>; listResources(input: { readonly brand: BrandScope; readonly courseId: string } & Correlated): Promise<RepositoryResult<readonly M2bResource[]>>; }
export interface M2ReadRepositories { readonly academicLevels: M2AcademicLevelReadRepository; readonly academicSemesters: M2AcademicSemesterReadRepository; readonly academicModules: M2AcademicModuleReadRepository; readonly academicModuleAliases: M2AcademicModuleAliasReadRepository; readonly instructors: M2InstructorReadRepository; readonly instructorBrandAssignments: M2InstructorBrandAssignmentReadRepository; readonly brandCourses: M2BrandCourseReadRepository; readonly courseInstructorAssignments: M2CourseInstructorAssignmentReadRepository; readonly courseDelivery?: M2bCourseDeliveryReadRepository; /** @deprecated compatibility test seam */ readonly brandInstructors?: { listBrandInstructors(input: { readonly brand: BrandScope } & Correlated): Promise<RepositoryResult<readonly M2InstructorBrandAssignment[]>>; findBrandInstructor(input: { readonly brand: BrandScope; readonly instructorId: string } & Correlated): Promise<RepositoryResult<M2InstructorBrandAssignment>>; listInstructorBrands(input: { readonly instructorId: string } & Correlated): Promise<RepositoryResult<readonly M2InstructorBrandAssignment[]>>; }; /** @deprecated compatibility test seam */ readonly courseInstructors?: M2CourseInstructorAssignmentReadRepository; }
