import type { CalendarEvent, AgendaItem, ReminderItem, StudyGoalProgress } from "./calendar.types";

export const INITIAL_CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: "evt-1",
    title: "Read Quiz",
    type: "quiz",
    date: "2025-05-12",
    startTime: "10:00",
    endTime: "10:45",
    displayTime: "10:00 - 10:45 AM",
    courseTitle: "Lesson 6 • Advanced UI/UX",
    description: "Weekly comprehension quiz on responsive grid systems and typography hierarchies.",
    status: "upcoming",
  },
  {
    id: "evt-2",
    title: "UI Case Study Review",
    type: "assignment",
    date: "2025-05-12",
    startTime: "13:00",
    endTime: "14:00",
    displayTime: "1:00 - 2:00 PM",
    courseTitle: "Design Systems & Architecture",
    description: "Peer evaluation and critique session for Case Study #3 deliverables.",
    status: "upcoming",
  },
  {
    id: "evt-3",
    title: "Personal Study",
    type: "study_block",
    date: "2025-05-12",
    startTime: "16:00",
    endTime: "17:30",
    displayTime: "4:00 - 5:30 PM",
    courseTitle: "Design Systems",
    description: "Deep work session: Component token architectures and Figma auto-layout setups.",
    status: "upcoming",
  },
  {
    id: "evt-4",
    title: "Live Session",
    type: "live_session",
    date: "2025-05-13",
    startTime: "09:00",
    endTime: "10:30",
    displayTime: "9:00 - 10:30 AM",
    courseTitle: "Advanced UI/UX Workshop",
    locationOrUrl: "https://meet.greenlearn.edu/live-ux-04",
    description: "Interactive live workshop on advanced motion choreography in UI design.",
    status: "upcoming",
  },
  {
    id: "evt-5",
    title: "Office Hours",
    type: "office_hours",
    date: "2025-05-13",
    startTime: "15:00",
    endTime: "16:00",
    displayTime: "3:00 - 4:00 PM",
    courseTitle: "Human Anatomy & Design Faculty",
    locationOrUrl: "https://meet.greenlearn.edu/office-hours-dr-miller",
    description: "Open Q&A session with Prof. Miller regarding upcoming project milestones.",
    status: "upcoming",
  },
  {
    id: "evt-6",
    title: "Read Quiz",
    type: "quiz",
    date: "2025-05-14",
    startTime: "10:00",
    endTime: "10:45",
    displayTime: "10:00 - 10:45 AM",
    courseTitle: "Lesson 6 • Advanced UI/UX",
    description: "Quick 15-question quiz covering color theory and accessibility contrast ratios.",
    status: "upcoming",
  },
  {
    id: "evt-7",
    title: "Personal Study",
    type: "study_block",
    date: "2025-05-14",
    startTime: "14:00",
    endTime: "15:30",
    displayTime: "2:00 - 3:30 PM",
    courseTitle: "Interactive Prototyping",
    description: "Working on stateful components and micro-interactions.",
    status: "upcoming",
  },
  {
    id: "evt-8",
    title: "Live Session",
    type: "live_session",
    date: "2025-05-14",
    startTime: "18:00",
    endTime: "19:30",
    displayTime: "6:00 - 7:30 PM",
    courseTitle: "Advanced UI/UX",
    locationOrUrl: "https://meet.greenlearn.edu/live-ux-evening",
    description: "Live portfolio design critique and live coding frontend demonstrations.",
    status: "upcoming",
  },
  {
    id: "evt-9",
    title: "UI Case Study Review",
    type: "assignment",
    date: "2025-05-15",
    startTime: "11:00",
    endTime: "12:00",
    displayTime: "11:00 AM - 12:00 PM",
    courseTitle: "Design Systems",
    description: "Review submission draft for milestone evaluation.",
    status: "upcoming",
  },
  {
    id: "evt-10",
    title: "Read Quiz",
    type: "quiz",
    date: "2025-05-15",
    startTime: "16:00",
    endTime: "16:45",
    displayTime: "4:00 - 4:45 PM",
    courseTitle: "Lesson 7 • Usability Principles",
    description: "Heuristic evaluation principles and WCAG 2.2 standards quiz.",
    status: "upcoming",
  },
  {
    id: "evt-11",
    title: "Live Session",
    type: "live_session",
    date: "2025-05-16",
    startTime: "09:00",
    endTime: "10:30",
    displayTime: "9:00 - 10:30 AM",
    courseTitle: "Advanced UI/UX",
    locationOrUrl: "https://meet.greenlearn.edu/live-ux-friday",
    description: "Final wrap-up lecture for Module 4 with live student showcases.",
    status: "upcoming",
  },
  {
    id: "evt-12",
    title: "Personal Study",
    type: "study_block",
    date: "2025-05-16",
    startTime: "13:00",
    endTime: "14:30",
    displayTime: "1:00 - 2:30 PM",
    courseTitle: "Design Systems",
    description: "Component library documentation and variant testing.",
    status: "upcoming",
  },
  {
    id: "evt-13",
    title: "Office Hours",
    type: "office_hours",
    date: "2025-05-16",
    startTime: "17:00",
    endTime: "18:00",
    displayTime: "5:00 - 6:00 PM",
    courseTitle: "Department Mentorship",
    locationOrUrl: "https://meet.greenlearn.edu/mentorship-weekly",
    description: "1-on-1 career path guidance and resume design clinic.",
    status: "upcoming",
  },
];

export const INITIAL_AGENDA_ITEMS: AgendaItem[] = [
  {
    id: "agenda-1",
    time: "10:00 AM",
    title: "Read Quiz",
    subtitle: "Lesson 6 • Advanced UI/UX",
    type: "quiz",
  },
  {
    id: "agenda-2",
    time: "2:00 PM",
    title: "Personal Study",
    subtitle: "Design Systems",
    type: "study_block",
  },
  {
    id: "agenda-3",
    time: "6:00 PM",
    title: "Live Session",
    subtitle: "Advanced UI/UX",
    type: "live_session",
    hasAction: true,
    actionLabel: "Join",
    linkUrl: "https://meet.greenlearn.edu/live-ux-evening",
  },
];

export const INITIAL_STUDY_GOAL: StudyGoalProgress = {
  weeklyPercentage: 75,
  completedHours: 9,
  targetHours: 12,
  streakDays: [
    { day: "S", completed: true },
    { day: "M", completed: true },
    { day: "T", completed: true },
    { day: "W", completed: true, isCurrent: true },
    { day: "T", completed: true },
    { day: "F", completed: true },
    { day: "S", completed: false },
  ],
};

export const INITIAL_REMINDERS: ReminderItem[] = [
  {
    id: "rem-1",
    title: "UI Case Study Review",
    dateLabel: "May 14, 1:00 PM",
    type: "assignment",
    completed: false,
  },
  {
    id: "rem-2",
    title: "Weekly Goal Check-in",
    dateLabel: "May 18, End of day",
    type: "goal",
    completed: false,
  },
  {
    id: "rem-3",
    title: "React Quiz",
    dateLabel: "May 19, 10:00 AM",
    type: "quiz",
    completed: false,
  },
];
