import type { IncomingMessage } from "node:http";
import type { AdminPermissionCode } from "../../contracts/admin";
import type { AdminHttpRequestContextResolver } from "../../core/context";
import type { RepositoryResult } from "../../core/persistence";
import { authorizeAdminRead } from "../admin-read-authorization";
import type { HttpJsonResponse, HttpRequestContext, AdminModule } from "../http-types";
import { badRequestResponse, jsonResponse, notFoundResponse, serviceUnavailableResponse } from "../middleware/json-response";
import { safeErrorResponse } from "../middleware/error-response";
import { resolveBrandFromRequestUrl } from "../runtime/brand-resolver";

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const parse=(url:string)=>new URL(url,"http://localhost");
const validUuid=(value:string|undefined):value is string=>Boolean(value&&UUID.test(value));
const invalid=(request:HttpRequestContext,message="A valid UUID is required.")=>badRequestResponse(request.correlationId,message,{code:"invalid_input"});
function parameters(request:HttpRequestContext,allowed:readonly string[]):{ok:true;value:URLSearchParams}|{ok:false;response:HttpJsonResponse}{const values=parse(request.url).searchParams;for(const key of values.keys())if(!allowed.includes(key)||values.getAll(key).length!==1)return{ok:false,response:badRequestResponse(request.correlationId,"Unsupported or repeated query parameter.",{code:"invalid_input"})};return{ok:true,value:values};}
function response<T>(request:HttpRequestContext,value:RepositoryResult<T>):HttpJsonResponse{if(value.ok)return jsonResponse(200,{ok:true,correlationId:request.correlationId,data:value.value},{"x-correlation-id":request.correlationId});if(value.error.code==="not_found"||value.error.code==="brand_not_found")return notFoundResponse(request.correlationId);if(value.error.code==="invalid_input")return invalid(request,"The request is invalid.");if(["query_failed","provider_unavailable","query_timeout"].includes(value.error.code))return serviceUnavailableResponse(request.correlationId);return safeErrorResponse(request.correlationId,value.error);}
interface ReadDependencies{readonly raw:IncomingMessage;readonly request:HttpRequestContext;readonly resolver:AdminHttpRequestContextResolver|undefined;}
async function executeRead<T>(dependencies:ReadDependencies,run:()=>Promise<RepositoryResult<T>>,targetBrandId?:string):Promise<HttpJsonResponse>{const permission:AdminPermissionCode="admin.platform.admin.read";const authorization=await authorizeAdminRead({request:dependencies.raw,context:dependencies.request,resolver:dependencies.resolver,permission,...(targetBrandId?{target:{id:targetBrandId}}:{})});if(!authorization.ok)return authorization.response;try{return response(dependencies.request,await run())}catch(error){return safeErrorResponse(dependencies.request.correlationId,error)}}

export async function handleAdminOverview(raw:IncomingMessage,request:HttpRequestContext,admin:AdminModule,resolver:AdminHttpRequestContextResolver|undefined):Promise<HttpJsonResponse>{const brand=resolveBrandFromRequestUrl(request.url,request.correlationId);if(!brand.ok)return badRequestResponse(request.correlationId,brand.error.message,{code:brand.error.code});const authorization=await authorizeAdminRead({request:raw,context:request,resolver,permission:"admin.overview.read",target:{code:brand.value}});if(!authorization.ok)return authorization.response;try{const result=await admin.queries.getAdminOverview(authorization.context);if(!result.ok)return["query_failed","provider_unavailable","query_timeout"].includes(result.error.code)?serviceUnavailableResponse(request.correlationId):safeErrorResponse(request.correlationId,result.error);return jsonResponse(200,{ok:true,correlationId:request.correlationId,brand:result.value.brand,data:result.value},{"x-correlation-id":request.correlationId})}catch(error){return safeErrorResponse(request.correlationId,error)}}

export function isAdminM2ReadPath(path:string):boolean{return path==="/v1/admin/curriculum/levels"||path==="/v1/admin/curriculum/semesters"||path==="/v1/admin/curriculum/modules"||path==="/v1/admin/instructors"||/^\/v1\/admin\/(curriculum\/modules|instructors)\/[^/]+(?:\/brands)?$/.test(path)||/^\/v1\/admin\/brands\/[^/]+\/(instructors|courses)$/.test(path)||/^\/v1\/admin\/brands\/[^/]+\/instructors\/[^/]+(?:\/courses)?$/.test(path)||/^\/v1\/admin\/brands\/[^/]+\/courses\/[^/]+(?:\/instructors)?$/.test(path);}

export async function handleAdminM2Read(raw:IncomingMessage,request:HttpRequestContext,admin:AdminModule,resolver:AdminHttpRequestContextResolver|undefined):Promise<HttpJsonResponse|undefined>{const path=parse(request.url).pathname;const dependencies:ReadDependencies={raw,request,resolver};
  if(path==="/v1/admin/curriculum/levels"){const p=parameters(request,[]);return!p.ok?p.response:executeRead(dependencies,()=>admin.queries.m2.listAcademicLevels({correlationId:request.correlationId}));}
  if(path==="/v1/admin/curriculum/semesters"){const p=parameters(request,["levelId"]);if(!p.ok)return p.response;const levelId=p.value.get("levelId")??undefined;return!levelId||validUuid(levelId)?executeRead(dependencies,()=>admin.queries.m2.listAcademicSemesters({levelId,correlationId:request.correlationId})):invalid(request);}
  if(path==="/v1/admin/curriculum/modules"){const p=parameters(request,["semesterId"]);if(!p.ok)return p.response;const semesterId=p.value.get("semesterId")??undefined;return!semesterId||validUuid(semesterId)?executeRead(dependencies,()=>admin.queries.m2.listAcademicModules({semesterId,correlationId:request.correlationId})):invalid(request);}
  let match=path.match(/^\/v1\/admin\/curriculum\/modules\/([^/]+)$/);if(match){const p=parameters(request,[]);return!p.ok?p.response:validUuid(match[1])?executeRead(dependencies,()=>admin.queries.m2.findAcademicModule({moduleId:match![1],correlationId:request.correlationId})):invalid(request);}
  if(path==="/v1/admin/instructors"){const p=parameters(request,[]);return!p.ok?p.response:executeRead(dependencies,()=>admin.queries.m2.listInstructors({correlationId:request.correlationId}));}
  match=path.match(/^\/v1\/admin\/instructors\/([^/]+)\/brands$/);if(match){const p=parameters(request,[]);return!p.ok?p.response:validUuid(match[1])?executeRead(dependencies,()=>admin.queries.m2.listInstructorBrandAssignments({instructorId:match![1],correlationId:request.correlationId})):invalid(request);}
  match=path.match(/^\/v1\/admin\/instructors\/([^/]+)$/);if(match){const p=parameters(request,[]);return!p.ok?p.response:validUuid(match[1])?executeRead(dependencies,()=>admin.queries.m2.findInstructor({instructorId:match![1],correlationId:request.correlationId})):invalid(request);}
  match=path.match(/^\/v1\/admin\/brands\/([^/]+)\/instructors$/);if(match){const p=parameters(request,[]);return!p.ok?p.response:validUuid(match[1])?executeRead(dependencies,()=>admin.queries.m2.listBrandInstructors({brandId:match![1],correlationId:request.correlationId}),match[1]):invalid(request);}
  match=path.match(/^\/v1\/admin\/brands\/([^/]+)\/instructors\/([^/]+)\/courses$/);if(match){const p=parameters(request,[]);return!p.ok?p.response:validUuid(match[1])&&validUuid(match[2])?executeRead(dependencies,()=>admin.queries.m2.listInstructorCourseAssignments({brandId:match![1],instructorId:match![2],correlationId:request.correlationId}),match[1]):invalid(request);}
  match=path.match(/^\/v1\/admin\/brands\/([^/]+)\/instructors\/([^/]+)$/);if(match){const p=parameters(request,[]);return!p.ok?p.response:validUuid(match[1])&&validUuid(match[2])?executeRead(dependencies,()=>admin.queries.m2.findBrandInstructor({brandId:match![1],instructorId:match![2],correlationId:request.correlationId}),match[1]):invalid(request);}
  match=path.match(/^\/v1\/admin\/brands\/([^/]+)\/courses$/);if(match){const p=parameters(request,["academicModuleId","scope"]);if(!p.ok)return p.response;const academicModuleId=p.value.get("academicModuleId")??undefined;const scope=p.value.get("scope")??undefined;if(academicModuleId&&scope)return invalid(request,"academicModuleId and scope cannot be combined.");if(scope&&scope!=="standalone")return invalid(request,"scope must be standalone.");return validUuid(match[1])&&(!academicModuleId||validUuid(academicModuleId))?executeRead(dependencies,()=>admin.queries.m2.listBrandCourses({brandId:match![1],academicModuleId,scope:scope as "standalone"|undefined,correlationId:request.correlationId}),match[1]):invalid(request);}
  match=path.match(/^\/v1\/admin\/brands\/([^/]+)\/courses\/([^/]+)\/instructors$/);if(match){const p=parameters(request,[]);return!p.ok?p.response:validUuid(match[1])&&validUuid(match[2])?executeRead(dependencies,()=>admin.queries.m2.listCourseInstructors({brandId:match![1],courseId:match![2],correlationId:request.correlationId}),match[1]):invalid(request);}
  match=path.match(/^\/v1\/admin\/brands\/([^/]+)\/courses\/([^/]+)$/);if(match){const p=parameters(request,[]);return!p.ok?p.response:validUuid(match[1])&&validUuid(match[2])?executeRead(dependencies,()=>admin.queries.m2.findBrandCourse({brandId:match![1],courseId:match![2],correlationId:request.correlationId}),match[1]):invalid(request);}
  return undefined;
}
