import { Activity, ChevronLeft, ChevronRight, Download, Filter, GraduationCap, KeyRound, Laptop, LoaderCircle, LockKeyhole, MoreVertical, Plus, RotateCcw, Search, ShieldCheck, Smartphone, UsersRound, UserRound, X } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { useOutletContext } from "react-router-dom";
import type { AdminBrandContext, AdminBrandView, AdminStudentDetail, AdminStudentStatus } from "../../../features/admin/api";
import { adminDeliveryRequest, catalogueBrandAccessPath, catalogueInstitutionsPath, type CatalogueBrand, type CatalogueInstitution } from "../../../features/admin/api/adminDelivery.http";
import { loadAdminStudentDetail, studentStatusLabel, useAdminStudents, type AdminStudentRow } from "../../../features/admin/students/adminStudents.adapter";

type BrandFilter = "all" | "medway" | "elite" | "nexus";
type DetailTab = "profile" | "access" | "devices" | "sessions";
const number = new Intl.NumberFormat("en-EG");
const initials = (name?: string | null) => (name ?? "Student").split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase();
const shortDate = (date?: string | null) => date ? new Intl.DateTimeFormat("en", { month: "short", day: "numeric", year: "numeric" }).format(new Date(date)) : "—";
const relative = (date?: string | null) => date ? new Intl.RelativeTimeFormat("en", { numeric: "auto" }).format(Math.round((new Date(date).getTime() - Date.now()) / 3_600_000), "hour") : "No activity";
const splitTerm = (term?: string | null) => { const [level = "—", semester = "—"] = term?.split("/").map((part) => part.trim()) ?? []; return { level, semester }; };

function StatusBadge({ status }: { status: AdminStudentStatus }) { return <span className={`admin-students-status is-${status}`}><i aria-hidden="true" />{studentStatusLabel[status]}</span>; }
function BrandBadge({ row }: { row: AdminStudentRow }) { return <span className={`admin-students-brand is-${row.platform.platformCode}`}><ShieldCheck aria-hidden="true" />{row.platform.platformDisplayName}</span>; }

function DetailPanel({ row, detail, tab, onTab, onClose, preview }: { row?: AdminStudentRow; detail?: AdminStudentDetail; tab: DetailTab; onTab: (tab: DetailTab) => void; onClose: () => void; preview: boolean }) {
  if (!row) return <aside className="admin-students-detail admin-students-detail--empty"><UserRound aria-hidden="true" /><strong>Select a student</strong><p>Choose a row to inspect its available account, access, device, and session information.</p></aside>;
  const term = splitTerm(row.academicTermOrYear);
  const tabs: readonly DetailTab[] = ["profile", "access", "devices", "sessions"];
  const fields = [["Full Name", row.displayName ?? "Not available"], ["Student ID", row.studentIdMasked ?? "Not provided"], ["Email", row.emailMasked ?? "Not available"], ["Phone", row.phoneMasked ?? "Not provided"], ["Academic Institution", row.academicInstitution ?? row.university ?? "Not provided"], ["Academic Level", row.academicLevel ?? term.level], ["Semester", row.academicSemester ?? term.semester], ["Program", row.program ?? "Not provided"], ["Enrollment Date", shortDate(detail?.createdAt)], ["Expected Graduation", shortDate(row.expectedGraduationDate)], ["Brand", row.platform.platformDisplayName]];
  return <aside className="admin-students-detail" aria-label={`${row.displayName} details`}>
    <header className="admin-students-detail__header"><span className="admin-students-avatar">{initials(row.displayName)}</span><div><strong>{row.displayName ?? "Student profile"}</strong><StatusBadge status={row.status} /><small>{row.studentIdMasked ?? "No student ID"} · {row.emailMasked ?? "Email unavailable"}</small></div><button type="button" className="admin-students-icon-button" onClick={onClose} aria-label="Close student details"><X aria-hidden="true" /></button></header>
    <div className="admin-students-tabs" role="tablist" aria-label="Student details">{tabs.map((item) => <button key={item} type="button" role="tab" aria-selected={tab === item} onClick={() => onTab(item)}>{item}</button>)}</div>
    <div className="admin-students-detail__body">
      {tab === "profile" && <><section><h3>Student overview</h3><dl className="admin-students-fields">{fields.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section><section><h3>Quick actions</h3><div className="admin-students-quick-actions"><button type="button" disabled title="Student write actions are not connected"><LockKeyhole aria-hidden="true" />Suspend access</button><button type="button" disabled title="Device management is not connected"><Smartphone aria-hidden="true" />Reset device</button><button type="button" disabled title="Student write actions are not connected"><RotateCcw aria-hidden="true" />Restore access</button><button type="button" disabled title="Password reset is not connected"><KeyRound aria-hidden="true" />Reset password</button></div></section><section><h3>Activity summary</h3><dl className="admin-students-fields admin-students-activity"><div><dt>Last activity</dt><dd>{relative(row.lastSeenAt)}</dd></div><div><dt>Total sessions</dt><dd>{detail?.sessions.length ?? row.activeSessionCount}</dd></div><div><dt>Total login days</dt><dd>Not available</dd></div><div><dt>Average session time</dt><dd>Not available</dd></div></dl></section></>}
      {tab === "access" && <section className="admin-students-tab-empty"><ShieldCheck aria-hidden="true" /><h3>Access summary</h3><p>{detail ? `${detail.access.activeGrantCount} active grants and ${detail.access.activeSubscriptionCount} active subscriptions are available in this ${preview ? "preview" : "read-only"} record.` : "Detailed access data is unavailable for this record."}</p></section>}
      {tab === "devices" && <section className="admin-students-tab-empty"><Laptop aria-hidden="true" /><h3>Devices</h3><p>{detail ? `${detail.devices.length} detailed device records are available.` : `${row.activeDeviceCount} active device${row.activeDeviceCount === 1 ? "" : "s"} reported by the read model.`}</p></section>}
      {tab === "sessions" && <section className="admin-students-tab-empty"><Activity aria-hidden="true" /><h3>Sessions</h3><p>{detail ? `${detail.sessions.length} session records are available.` : `${row.activeSessionCount} active session${row.activeSessionCount === 1 ? "" : "s"} reported by the read model.`}</p></section>}
    </div>
  </aside>;
}

function AddStudentModal({ brands, onClose, onCreated }: { brands: readonly AdminBrandContext[]; onClose: () => void; onCreated: () => void }) {
  const [catalogue, setCatalogue] = useState<{ brands: CatalogueBrand[]; institutions: CatalogueInstitution[] }>();
  const [brandId, setBrandId] = useState(brands.find((item) => item.brandCode === "elite")?.brandId ?? brands[0]?.brandId ?? "");
  const [institutionId, setInstitutionId] = useState(""); const [levelId, setLevelId] = useState(""); const [semesterId, setSemesterId] = useState("");
  const [fullName, setFullName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [studentCode, setStudentCode] = useState("");
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState(false); const idempotencyKey = useRef("");
  useEffect(() => { void Promise.all([adminDeliveryRequest<CatalogueBrand[]>(catalogueBrandAccessPath), adminDeliveryRequest<CatalogueInstitution[]>(catalogueInstitutionsPath)]).then(([loadedBrands, institutions]) => { setCatalogue({ brands: loadedBrands, institutions }); const elite = loadedBrands.find((item) => item.code === "elite"); if (elite) { setBrandId(elite.id); const buc = elite.allowedAcademicInstitutions.find((item) => item.code.toLowerCase() === "buc"); const preferredInstitution = institutions.find((item) => item.id === buc?.id); const yearOne = preferredInstitution?.levels.find((item) => item.levelNumber === 1); const semesterOne = yearOne?.semesters.find((item) => item.semesterNumber === 1); if (preferredInstitution && yearOne && semesterOne) { setInstitutionId(preferredInstitution.id); setLevelId(yearOne.id); setSemesterId(semesterOne.id); } } }).catch((reason) => setError(reason instanceof Error ? reason.message : "Academic placement options are unavailable.")); }, []);
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === "Escape" && !busy) onClose(); }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [busy, onClose]);
  const selectedBrand = catalogue?.brands.find((item) => item.id === brandId);
  const allowedIds = new Set(selectedBrand?.allowedAcademicInstitutions.map((item) => item.id) ?? []);
  const institutions = catalogue?.institutions.filter((item) => allowedIds.has(item.id)) ?? [];
  const institution = institutions.find((item) => item.id === institutionId);
  const level = institution?.levels.find((item) => item.id === levelId);
  const semester = level?.semesters.find((item) => item.id === semesterId);
  const brand = brands.find((item) => item.brandId === brandId);
  const valid = fullName.trim().length >= 2 && /^\S+@\S+\.\S+$/.test(email) && password.length >= 12 && !!brand && !!institution && !!level && !!semester;
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!valid || !brand) return; setBusy(true); setError(""); try { await adminDeliveryRequest(`/v1/admin/students?brand=${encodeURIComponent(brand.brandCode)}`, { method: "POST", key: idempotencyKey.current ||= crypto.randomUUID(), body: { fullName: fullName.trim(), email: email.trim(), password, studentCode: studentCode.trim() || undefined, academicInstitutionId: institutionId, academicLevelId: levelId, academicSemesterId: semesterId, reason: "Create student account with verified academic placement" } }); idempotencyKey.current = ""; setSuccess(true); onCreated(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Student account could not be created."); } finally { setBusy(false); } };
  return <div className="admin-workflow-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !busy) onClose(); }}><section className="admin-workflow-modal" role="dialog" aria-modal="true" aria-labelledby="add-student-title"><header><div><small>Student account</small><h2 id="add-student-title">Add student</h2></div><button type="button" onClick={onClose} aria-label="Close"><X /></button></header>{success ? <div className="admin-workflow-result" role="status"><strong>Student account created</strong><p>The account, brand membership, and academic placement were saved.</p><button type="button" className="is-primary" onClick={onClose}>Done</button></div> : <form onSubmit={submit} onChange={() => { idempotencyKey.current = ""; }}><div className="admin-workflow-fields"><label>Full name<input required value={fullName} onChange={(event) => setFullName(event.target.value)} autoComplete="name" /></label><label>Email<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="email" /></label><label>Temporary password<input required type="password" minLength={12} value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="new-password" /><small>At least 12 characters</small></label><label>Student code <span>(optional)</span><input value={studentCode} onChange={(event) => setStudentCode(event.target.value)} /></label><label>Commercial brand<select value={brandId} onChange={(event) => { setBrandId(event.target.value); setInstitutionId(""); setLevelId(""); setSemesterId(""); }}>{brands.map((item) => <option key={item.brandId} value={item.brandId}>{item.brandDisplayName}</option>)}</select></label><label>Academic institution<select required value={institutionId} onChange={(event) => { setInstitutionId(event.target.value); setLevelId(""); setSemesterId(""); }}><option value="">Select institution</option>{institutions.map((item) => <option key={item.id} value={item.id}>{item.displayName}</option>)}</select></label><label>Level<select required value={levelId} onChange={(event) => { setLevelId(event.target.value); setSemesterId(""); }} disabled={!institution}>{(institution?.levels ?? []).map((item) => <option key={item.id} value={item.id}>{item.displayTitle}</option>)}</select></label><label>Semester<select required value={semesterId} onChange={(event) => setSemesterId(event.target.value)} disabled={!level}>{(level?.semesters ?? []).map((item) => <option key={item.id} value={item.id}>{item.displayTitle}</option>)}</select></label></div>{error && <p className="admin-workflow-error" role="alert">{error}</p>}<footer><button type="button" onClick={onClose} disabled={busy}>Cancel</button><button className="is-primary" type="submit" disabled={!valid || busy}>{busy ? "Creating…" : "Create student"}</button></footer></form>}</section></div>;
}

export function AdminStudentsPage() {
  const { brand, brandView, availableBrands } = useOutletContext<{ brand?: AdminBrandContext; brandView: AdminBrandView; availableBrands: readonly AdminBrandContext[] }>();
  const { dataset, loading, error, retry, api } = useAdminStudents(brand, availableBrands);
  const [search, setSearch] = useState(""); const [brandFilter, setBrandFilter] = useState<BrandFilter>(brandView); const [level, setLevel] = useState("all"); const [status, setStatus] = useState<"all" | AdminStudentStatus>("all"); const [page, setPage] = useState(1); const [selectedId, setSelectedId] = useState<string>(); const [detail, setDetail] = useState<AdminStudentDetail>(); const [detailOpen, setDetailOpen] = useState(false); const [tab, setTab] = useState<DetailTab>("profile"); const [selectedRows, setSelectedRows] = useState<Set<string>>(new Set()); const [addStudentOpen, setAddStudentOpen] = useState(false);
  const allCheckbox = useRef<HTMLInputElement>(null); const pageSize = 8;
  useEffect(() => { setBrandFilter(brandView); setPage(1); }, [brandView]);
  const rows = dataset?.rows ?? [];
  const levels = useMemo(() => [...new Set(rows.map((row) => splitTerm(row.academicTermOrYear).level).filter((item) => item !== "—"))], [rows]);
  const filtered = useMemo(() => { const query = search.trim().toLowerCase(); return rows.filter((row) => { const term = splitTerm(row.academicTermOrYear); return (!query || [row.displayName, row.emailMasked, row.studentIdMasked].filter(Boolean).join(" ").toLowerCase().includes(query)) && (brandFilter === "all" || row.platform.platformCode === brandFilter) && (level === "all" || term.level === level) && (status === "all" || row.status === status); }); }, [rows, search, brandFilter, level, status]);
  const totalPages = Math.max(1, Math.ceil(filtered.length / pageSize)); const visible = filtered.slice((page - 1) * pageSize, page * pageSize); const row = rows.find((item) => item.id === selectedId); const filtersActive = Boolean(search || brandFilter !== brandView || level !== "all" || status !== "all");
  const allSelected = visible.length > 0 && visible.every((item) => selectedRows.has(item.id)); const someSelected = visible.some((item) => selectedRows.has(item.id)) && !allSelected;
  useEffect(() => { if (page > totalPages) setPage(totalPages); }, [page, totalPages]); useEffect(() => { if (allCheckbox.current) allCheckbox.current.indeterminate = someSelected; }, [someSelected]);
  const choose = async (item: AdminStudentRow) => { setSelectedId(item.id); setDetail(undefined); setDetailOpen(true); setTab("profile"); const resolved = await loadAdminStudentDetail(api, item); if (resolved) setDetail(resolved); };
  const reset = () => { setSearch(""); setBrandFilter(brandView); setLevel("all"); setStatus("all"); setPage(1); };
  return <section className="admin-page admin-students-page" aria-label="Students management">
    <header className="admin-students-heading"><div><h2>Students</h2><p>Manage student accounts, access, devices, and academic progress.</p></div>{dataset?.mode === "preview" && <span className="admin-students-preview">Local preview data</span>}</header>
    <div className="admin-students-stats">{[[UsersRound, "Active Students", dataset?.stats.activeStudents], [GraduationCap, "Medway Students", dataset?.stats.medwayStudents], [UserRound, "Elite Students", dataset?.stats.eliteStudents], [Activity, "New This Month", dataset?.stats.newThisMonth]].map(([Icon, label, value]) => { const CardIcon = Icon as typeof UsersRound; return <article key={label as string}><span><CardIcon aria-hidden="true" /></span><div><small>{label as string}</small><strong>{value == null || loading || error ? "—" : number.format(value as number)}</strong><em>{dataset?.mode === "preview" ? "Preview records" : "No trend data available"}</em></div></article>; })}</div>
    <div className={`admin-students-workspace${detailOpen ? " has-detail" : ""}`}><article className="admin-students-directory"><div className="admin-students-toolbar"><label className="admin-students-search"><span className="admin-sr-only">Search students by name, email, or student ID</span><Search aria-hidden="true" /><input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Search students…" /></label><label><span className="admin-sr-only">Filter by brand</span><select value={brandFilter} onChange={(event) => { setBrandFilter(event.target.value as BrandFilter); setPage(1); }}><option value="all">All Brands</option><option value="medway">Medway</option><option value="elite">Elite</option><option value="nexus">Nexus</option></select></label><label><span className="admin-sr-only">Filter by academic level</span><select value={level} onChange={(event) => { setLevel(event.target.value); setPage(1); }}><option value="all">All Academic Levels</option>{levels.map((item) => <option key={item}>{item}</option>)}</select></label><label><span className="admin-sr-only">Filter by account status</span><select value={status} onChange={(event) => { setStatus(event.target.value as typeof status); setPage(1); }}><option value="all">All Statuses</option>{Object.entries(studentStatusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><button type="button" className="admin-students-button" onClick={reset} disabled={!filtersActive}><Filter aria-hidden="true" />More filters</button><button type="button" className="admin-students-button" disabled title="Export is not connected"><Download aria-hidden="true" />Export</button><button type="button" className="admin-students-button is-primary" onClick={() => setAddStudentOpen(true)}><Plus aria-hidden="true" />Add student</button></div>
      <div className="admin-students-table-wrap"><table className="admin-students-table"><caption className="admin-sr-only">Students directory</caption><thead><tr><th><input ref={allCheckbox} type="checkbox" aria-label="Select all students on this page" checked={allSelected} onChange={() => setSelectedRows((current) => { const next = new Set(current); visible.forEach((item) => allSelected ? next.delete(item.id) : next.add(item.id)); return next; })} /></th><th>Student</th><th>Student ID</th><th>Brand</th><th>Academic Level</th><th>Semester</th><th>Status</th><th>Devices</th><th>Last Activity</th><th>Actions</th></tr></thead><tbody>
      {loading && <tr><td colSpan={10}><div className="admin-students-table-state"><LoaderCircle aria-hidden="true" />Loading student records…</div></td></tr>}
      {error && <tr><td colSpan={10}><div className="admin-students-table-state is-error"><strong>Student records are unavailable.</strong><span>{error.message}</span><button type="button" onClick={retry}>Retry</button></div></td></tr>}
      {!loading && !error && !rows.length && <tr><td colSpan={10}><div className="admin-students-table-state"><UsersRound aria-hidden="true" /><strong>No students yet</strong><span>Student records will appear here when they are available for this brand context.</span></div></td></tr>}
      {!loading && !error && rows.length > 0 && !filtered.length && <tr><td colSpan={10}><div className="admin-students-table-state"><Search aria-hidden="true" /><strong>No matching students</strong><span>Try changing or clearing the current filters.</span><button type="button" onClick={reset}>Clear filters</button></div></td></tr>}
      {visible.map((item) => { const term = splitTerm(item.academicTermOrYear); const selected = item.id === selectedId && detailOpen; const label = item.displayName ?? "student profile"; return <tr key={item.id} className={selected ? "is-selected" : ""} onClick={() => void choose(item)}><td onClick={(event) => event.stopPropagation()}><input type="checkbox" aria-label={`Select ${label}`} checked={selectedRows.has(item.id)} onChange={() => setSelectedRows((current) => { const next = new Set(current); next.has(item.id) ? next.delete(item.id) : next.add(item.id); return next; })} /></td><td><span className="admin-students-person"><i>{initials(item.displayName)}</i><span><strong>{item.displayName ?? "Student profile"}</strong><small>{item.emailMasked ?? "Email unavailable"}</small></span></span></td><td>{item.studentIdMasked ?? "—"}</td><td><BrandBadge row={item} /></td><td>{term.level}</td><td>{term.semester}</td><td><StatusBadge status={item.status} /></td><td><span className="admin-students-device"><Laptop aria-hidden="true" />{item.activeDeviceCount ?? "—"}</span></td><td>{relative(item.lastSeenAt)}</td><td onClick={(event) => event.stopPropagation()}><span className="admin-students-actions"><button type="button" onClick={() => void choose(item)}>View student</button><button type="button" className="admin-students-icon-button" aria-label={`More actions for ${label}`} disabled><MoreVertical aria-hidden="true" /></button></span></td></tr>; })}</tbody></table></div>
      <footer className="admin-students-pagination"><span>{filtered.length ? `Showing ${(page - 1) * pageSize + 1}–${Math.min(page * pageSize, filtered.length)} of ${filtered.length} students` : "No students to show"}</span><div><button type="button" aria-label="Previous page" disabled={page === 1} onClick={() => setPage((current) => current - 1)}><ChevronLeft aria-hidden="true" /></button><strong>{page}</strong><span>of {totalPages}</span><button type="button" aria-label="Next page" disabled={page === totalPages} onClick={() => setPage((current) => current + 1)}><ChevronRight aria-hidden="true" /></button></div></footer>
    </article><DetailPanel row={detailOpen ? row : undefined} detail={detail} tab={tab} onTab={setTab} onClose={() => setDetailOpen(false)} preview={dataset?.mode === "preview"} /></div>{addStudentOpen && <AddStudentModal brands={availableBrands} onClose={() => setAddStudentOpen(false)} onCreated={() => { void retry(); }} />}</section>;
}
