import { AlertCircle, LoaderCircle } from "lucide-react";
import { useOutletContext } from "react-router-dom";
import { useAdminOverview } from "../../../features/admin/hooks/useAdminOverview";
import { brandToPlatform } from "../../../features/admin/hooks/useAdminBrand";
import { AdminDataList } from "../../../features/admin/components/AdminDataList";
import { AdminSectionCard } from "../../../features/admin/components/AdminSectionCard";
import { AdminStatCard } from "../../../features/admin/components/AdminStatCard";
import { AdminStatusPill } from "../../../features/admin/components/AdminStatusPill";
import type { AdminOverview as AdminOverviewModel, AdminBrandContext } from "../../../features/admin/api";

function formatTimestamp(value: string) { return new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
function OverviewLists({ overview }: { overview: AdminOverviewModel }) {
  return <div className="admin-overview-lists"><AdminSectionCard title="Recent audit logs" eyebrow="Append-only evidence"><AdminDataList items={overview.recentAuditLogs} emptyMessage="No recent audit logs." renderItem={(item) => <div className="admin-event-row"><div><strong>{item.action}</strong><span>{item.entityType} · {item.entityId}</span></div><time dateTime={item.occurredAt}>{formatTimestamp(item.occurredAt)}</time></div>} /></AdminSectionCard><AdminSectionCard title="Recent admin actions" eyebrow="Read-only activity"><AdminDataList items={overview.recentAdminActions} emptyMessage="No recent admin actions." renderItem={(item) => <div className="admin-event-row"><div><strong>{item.actionType}</strong><span>{item.targetEntityType} · {item.targetEntityId}</span></div><span className="admin-event-row__meta"><AdminStatusPill label={item.outcome} tone={item.outcome === "succeeded" ? "success" : "warning"} /><time dateTime={item.occurredAt}>{formatTimestamp(item.occurredAt)}</time></span></div>} /></AdminSectionCard><AdminSectionCard title="Recent security events" eyebrow="Risk signals"><AdminDataList items={overview.recentSecurityEvents} emptyMessage="No recent security events." renderItem={(item) => <div className="admin-event-row"><div><strong>{item.eventType}</strong><span>{item.userId ? `User ${item.userId}` : "System event"}</span></div><span className="admin-event-row__meta"><AdminStatusPill label={item.severity} tone={item.severity === "critical" ? "danger" : item.severity === "warning" ? "warning" : "neutral"} /><time dateTime={item.occurredAt}>{formatTimestamp(item.occurredAt)}</time></span></div>} /></AdminSectionCard></div>;
}
export function AdminOverviewPage() {
  const { brand } = useOutletContext<{ brand: AdminBrandContext }>();
  const { data, error, loading, retry, correlationId, dataSource } = useAdminOverview(brandToPlatform(brand));
  return <section className="admin-page" aria-labelledby="admin-dashboard-title"><header className="admin-page__heading"><div><p className="admin-eyebrow">Read-only operations workspace</p><h1 id="admin-dashboard-title">Admin Dashboard</h1><p className="admin-page__description">Brand-scoped operational signals for the selected educational identity.</p></div><div className="admin-page__status-group">{data && <AdminStatusPill label={`Active brand: ${brand.brandDisplayName}`} tone="success" />}<AdminStatusPill label={`Data source: ${dataSource}`} tone="neutral" /></div></header><aside className="admin-notice" aria-label="Authorization notice"><AlertCircle aria-hidden="true" /><span>Frontend permission visibility is presentation-only. Backend authorization and brand-scope validation remain authoritative.</span></aside>{loading && <div className="admin-feedback" aria-live="polite" aria-busy="true"><LoaderCircle className="admin-feedback__spinner" aria-hidden="true" /> Loading overview data…</div>}{error && <div className="admin-feedback admin-feedback--error" role="alert"><strong>{error.message}</strong><span>Correlation ID: {error.correlationId}</span><button type="button" onClick={retry}>Retry</button></div>}{data && !loading && !error && <><div className="admin-stat-grid"><AdminStatCard label="Pending payments" value={data.pendingPaymentReviewsCount} tone="warning" /><AdminStatCard label="Pending refunds" value={data.pendingRefundsCount} tone="warning" /><AdminStatCard label="Suspicious events" value={data.suspiciousSecurityEventsCount} tone="danger" /><AdminStatCard label="Active subscriptions" value={data.activeSubscriptionsCount} /><AdminStatCard label="Expired subscriptions" value={data.expiredSubscriptionsCount} tone="neutral" /><AdminStatCard label="Active grants" value={data.activeGrantsCount} /><AdminStatCard label="Revoked grants" value={data.revokedGrantsCount} tone="neutral" /><AdminStatCard label="Content awaiting release" value={data.contentAwaitingReleaseCount} tone="warning" /><AdminStatCard label="Assessments awaiting review" value={data.assessmentsAwaitingReviewCount} tone="warning" /></div><OverviewLists overview={data} /><p className="admin-debug-line">Read correlation: {correlationId}</p></>}</section>;
}