import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useOutletContext } from "react-router-dom";
import { CreditCard, Plus, ShieldCheck, UsersRound, Wallet, X } from "lucide-react";
import type { AdminBrandContext } from "../../../features/admin/api";
import { adminDeliveryRequest } from "../../../features/admin/api/adminDelivery.http";
import { WorkspaceBadge, WorkspaceCard, WorkspaceFields, WorkspaceInspector, WorkspaceMetric, WorkspaceState } from "../../../features/admin/components/AdminWorkspacePrimitives";

type Plan = { code: string; label: string; subjectCount: number; groupSize: number; amount: number | null; currency: "EGP"; listPrice?: number; deadline?: string };
type Student = { id: string; fullName: string; email: string; institution: string; level: string; semester: string };
type Course = { id: string; title: string; code: string; status: string; enrolled: boolean };
type Order = { id: string; studentProfileId: string; studentName: string; studentEmail: string; institution: string; level: string; semester: string; brandId: string; planCode: string; status: "pending" | "approved" | "rejected" | "cancelled"; subjectCount: number; groupSize: number; amountPaid: number; currency: "EGP"; paymentReference: string | null; evidenceNote: string | null; adminNotes: string | null; reviewNote: string | null; rejectionReason: string | null; createdAt: string; version: number; courses: Course[] };
const uid = () => crypto.randomUUID();
const fmtDate = (value?: string | null) => value ? new Date(value).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" }) : "Unavailable";
const fmtMoney = (amount: number) => new Intl.NumberFormat("en-EG", { style: "currency", currency: "EGP", maximumFractionDigits: 2 }).format(amount);
const planNames: Record<string, string> = { single_subject: "Single subject", promo_4_subjects_individual_5000: "Individual · 4 subjects", group_3_friends_4700_each: "Group of 3 · 4 subjects per student", group_5_friends_4500_each: "Group of 5 · 4 subjects per student" };
const brandPath = (brand: AdminBrandContext) => `?brand=${encodeURIComponent(brand.brandCode)}`;
function useManualOrders() {
  const { brand, availableBrands } = useOutletContext<{ brand?: AdminBrandContext; availableBrands: readonly AdminBrandContext[] }>();
  const targets = useMemo(() => brand ? [brand] : availableBrands, [brand, availableBrands]);
  const [orders, setOrders] = useState<Order[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [revision, setRevision] = useState(0);
  const reload = useCallback(async () => {
    setLoading(true); setError("");
    try { const lists = await Promise.all(targets.map((item) => adminDeliveryRequest<Order[]>(`/v1/admin/subscription-orders${brandPath(item)}`))); setOrders(lists.flat()); }
    catch (reason) { setOrders([]); setError(reason instanceof Error ? reason.message : "Manual subscription orders are unavailable."); }
    finally { setLoading(false); }
  }, [targets, brand, revision]);
  useEffect(() => { void reload(); }, [reload]);
  return { brand, targets, orders, loading, error, reload: () => setRevision((value) => value + 1) };
}
function WorkflowModal({ title, eyebrow, onClose, children }: { title: string; eyebrow: string; onClose: () => void; children: React.ReactNode }) {
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [onClose]);
  return <div className="admin-workflow-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="admin-workflow-modal" role="dialog" aria-modal="true" aria-label={title}><header><div><small>{eyebrow}</small><h2>{title}</h2></div><button type="button" onClick={onClose} aria-label="Close"><X /></button></header>{children}</section></div>;
}
function CreateOrderModal({ brand, targets, onClose, onCreated }: { brand?: AdminBrandContext; targets: readonly AdminBrandContext[]; onClose: () => void; onCreated: () => void }) {
  const [students, setStudents] = useState<Student[]>([]); const [plans, setPlans] = useState<Plan[]>([]); const [courses, setCourses] = useState<Course[]>([]);
  const [studentId, setStudentId] = useState(""); const [planCode, setPlanCode] = useState("single_subject"); const [courseIds, setCourseIds] = useState<string[]>([]); const [amount, setAmount] = useState(""); const [reference, setReference] = useState(""); const [evidence, setEvidence] = useState(""); const [notes, setNotes] = useState(""); const [studentSearch, setStudentSearch] = useState(""); const idempotencyKey = useRef(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [scopeCode, setScopeCode] = useState(brand?.brandCode ?? targets[0]?.brandCode ?? "elite"); const scope = brand ?? targets.find((item) => item.brandCode === scopeCode) ?? targets[0]; const plan = plans.find((item) => item.code === planCode); const student = students.find((item) => item.id === studentId); const valid = !!scope && !!student && !!plan && courseIds.length === plan.subjectCount && Number.isFinite(Number(amount)) && Number(amount) >= 0 && !busy;
  useEffect(() => { if (!scope) return; let active = true; void Promise.all([adminDeliveryRequest<Plan[]>(`/v1/admin/subscription-plans${brandPath(scope)}`), adminDeliveryRequest<Student[]>(`/v1/admin/subscription-students${brandPath(scope)}`)]).then(([p, s]) => { if (active) { setPlans(p); setStudents(s); } }).catch((reason) => { if (active) setError(reason instanceof Error ? reason.message : "Student and plan options are unavailable."); }); return () => { active = false; }; }, [scope]);
  useEffect(() => { if (!student || !scope) { setCourses([]); setCourseIds([]); return; } let active = true; setCourses([]); setCourseIds([]); void adminDeliveryRequest<Course[]>(`/v1/admin/subscription-courses${brandPath(scope)}&studentId=${encodeURIComponent(student.id)}`).then((items) => { if (active) setCourses(items.filter((item) => item.status === "published")); }).catch((reason) => { if (active) setError(reason instanceof Error ? reason.message : "Published subjects are unavailable."); }); return () => { active = false; }; }, [studentId, scope]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!valid || !student || !plan || !scope) return; setBusy(true); setError(""); try { await adminDeliveryRequest(`/v1/admin/subscription-orders${brandPath(scope)}`, { method: "POST", key: idempotencyKey.current ||= uid(), body: { studentProfileId: student.id, planCode: plan.code, courseIds, amountPaid: Number(amount), currency: "EGP", externalPaymentReference: reference.trim() || null, evidenceNote: evidence.trim() || null, adminNotes: notes.trim() || null, reason: "Record externally paid manual subscription request" } }); idempotencyKey.current = ""; onCreated(); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : "The request could not be saved."); } finally { setBusy(false); } };
  const filteredStudents = students.filter((item) => `${item.fullName} ${item.email}`.toLowerCase().includes(studentSearch.toLowerCase()));
  return <WorkflowModal eyebrow="Manual payment · pending approval" title="Create subscription" onClose={busy ? () => undefined : onClose}><form onSubmit={submit} onChange={() => { idempotencyKey.current = ""; }}><div className="admin-workflow-fields">
    {!brand && <label>Commercial brand<select value={scope?.brandCode ?? ""} onChange={(event) => { setScopeCode(event.target.value as AdminBrandContext["brandCode"]); setStudentId(""); }} disabled={busy}>{targets.map((item) => <option key={item.brandCode} value={item.brandCode}>{item.brandDisplayName}</option>)}</select></label>}
    <label className="admin-workflow-span">Find student<input type="search" placeholder="Search name or email" value={studentSearch} onChange={(event) => setStudentSearch(event.target.value)} /></label>
    <label className="admin-workflow-span">Student<select required value={studentId} onChange={(event) => setStudentId(event.target.value)}><option value="">Select student</option>{filteredStudents.map((item) => <option value={item.id} key={item.id}>{item.fullName} · {item.email} · {item.institution} · {item.level} · {item.semester}</option>)}</select></label>
    <label>Plan<select value={planCode} onChange={(event) => { setPlanCode(event.target.value); setCourseIds([]); const next = plans.find((item) => item.code === event.target.value); if (next?.amount) setAmount(String(next.amount)); }}>{plans.map((item) => <option value={item.code} key={item.code}>{item.label}{item.amount ? ` · ${fmtMoney(item.amount)}` : " · admin-entered amount"}</option>)}</select></label>
    <label>Amount paid (EGP)<input type="number" min="0" step="0.01" required value={amount} onChange={(event) => setAmount(event.target.value)} /></label>
    <div className="admin-workflow-course-list admin-workflow-span"><strong>Published subjects ({courseIds.length}/{plan?.subjectCount ?? 1})</strong>{!student ? <small>Select a student to load subjects for their placement.</small> : !courses.length ? <small>No published subjects are available for this student's placement.</small> : courses.map((course) => <label className="admin-workflow-course" key={course.id}><input type="checkbox" checked={courseIds.includes(course.id)} disabled={!courseIds.includes(course.id) && courseIds.length >= (plan?.subjectCount ?? 1)} onChange={() => setCourseIds((current) => current.includes(course.id) ? current.filter((id) => id !== course.id) : [...current, course.id])} /><span>{course.title}<small>{course.code}{course.enrolled ? " · already enrolled" : ""}</small></span></label>)}{plan && courseIds.length !== plan.subjectCount && <small className="admin-workflow-validation">Choose exactly {plan.subjectCount} published subject{plan.subjectCount === 1 ? "" : "s"} for this plan.</small>}</div>
    <label>External payment reference<input maxLength={240} value={reference} onChange={(event) => setReference(event.target.value)} /></label>
    <label className="admin-workflow-span">Payment evidence note/reference<textarea maxLength={2000} value={evidence} onChange={(event) => setEvidence(event.target.value)} placeholder="Manual evidence metadata only; file upload is unavailable." /></label>
    <label className="admin-workflow-span">Admin notes<textarea maxLength={4000} value={notes} onChange={(event) => setNotes(event.target.value)} /></label>
    {plan && plan.groupSize > 1 && <p className="admin-workflow-info admin-workflow-span">Group size and per-student price are recorded as offer metadata. Approval enrolls this selected student only.</p>}
  </div>{error && <p className="admin-workflow-error" role="alert">{error}</p>}<footer><button type="button" onClick={onClose} disabled={busy}>Cancel</button><button className="is-primary" type="submit" disabled={!valid}>{busy ? "Saving…" : "Save pending request"}</button></footer></form></WorkflowModal>;
}
function ReviewOrderModal({ order, brand, onClose, onReviewed }: { order: Order; brand: AdminBrandContext; onClose: () => void; onReviewed: () => void }) {
  const [decision, setDecision] = useState<"approve" | "reject">("approve"); const [reason, setReason] = useState(""); const idempotencyKey = useRef(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!reason.trim() || busy) return; setBusy(true); setError(""); try { const payload: Record<string, unknown> = { expectedVersion: order.version, reason: reason.trim() }; if (decision === "reject") payload.rejectionReason = reason.trim(); await adminDeliveryRequest(`/v1/admin/subscription-orders/${encodeURIComponent(order.id)}/${decision}${brandPath(brand)}`, { method: "POST", key: idempotencyKey.current ||= uid(), body: payload }); idempotencyKey.current = ""; onReviewed(); onClose(); } catch (e) { setError(e instanceof Error ? e.message : "The review could not be saved."); } finally { setBusy(false); } };
  return <WorkflowModal eyebrow="Manual payment review" title={order.studentName} onClose={busy ? () => undefined : onClose}><form onSubmit={submit} onChange={() => { idempotencyKey.current = ""; }}><WorkspaceFields fields={[["Student", `${order.studentName} · ${order.studentEmail}`], ["Placement", `${brand.brandDisplayName} · ${order.institution} · ${order.level} · ${order.semester}`], ["Plan", planNames[order.planCode] ?? order.planCode], ["Courses", order.courses.map((course) => course.title).join(", ") || "Unavailable"], ["Amount", fmtMoney(order.amountPaid)], ["External reference", order.paymentReference || "Not provided"], ["Evidence note", order.evidenceNote || "Not provided"], ["Admin notes", order.adminNotes || "None"], ["Created", fmtDate(order.createdAt)], ["Status", order.status]]} /><div className="admin-workflow-fields"><label>Decision<select value={decision} onChange={(event) => setDecision(event.target.value as "approve" | "reject")}><option value="approve">Approve and activate selected courses</option><option value="reject">Reject without enrollment</option></select></label><label>Review note{decision === "reject" ? " (rejection reason required)" : " (required)"}<textarea required maxLength={1000} value={reason} onChange={(event) => setReason(event.target.value)} /></label></div>{error && <p className="admin-workflow-error" role="alert">{error}</p>}<footer><button type="button" onClick={onClose} disabled={busy}>Cancel</button><button className="is-primary" type="submit" disabled={busy || !reason.trim()}>{busy ? "Saving…" : decision === "approve" ? "Approve payment" : "Reject request"}</button></footer></form></WorkflowModal>;
}
function ManualOrderTable({ rows, loading, error, empty, onSelect }: { rows: Order[]; loading: boolean; error: string; empty: string; onSelect: (row: Order) => void }) {
  return <><div className="admin-workspace-table-wrap"><table className="admin-workspace-table"><caption className="admin-sr-only">Manual subscription payment requests</caption><thead><tr><th>Student</th><th>Plan</th><th>Courses</th><th>Amount</th><th>Reference / evidence</th><th>Status</th><th>Created</th><th>Review</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><strong>{row.studentName}</strong></td><td>{planNames[row.planCode] ?? row.planCode}</td><td>{row.courses.map((course) => course.title).join(", ")}</td><td>{fmtMoney(row.amountPaid)}</td><td>{row.paymentReference || row.evidenceNote || "Not provided"}</td><td><WorkspaceBadge value={row.status} /></td><td>{fmtDate(row.createdAt)}</td><td><button type="button" onClick={() => onSelect(row)} disabled={row.status !== "pending"}>{row.status === "pending" ? "Review" : "View"}</button></td></tr>)}</tbody></table></div>{loading && <WorkspaceState loading title="Loading manual payment requests" />}{error && <div className="admin-workspace-state" role="alert"><h3>Manual payment requests are unavailable</h3><p>{error}</p></div>}{!loading && !error && rows.length === 0 && <WorkspaceState title={empty} />}</>;
}
function ManualOrdersWorkspace({ payments }: { payments: boolean }) {
  const data = useManualOrders(); const [createOpen, setCreateOpen] = useState(false); const [selected, setSelected] = useState<Order>(); const [search, setSearch] = useState(""); const [status, setStatus] = useState("all");
  const rows = data.orders.filter((order) => (status === "all" || order.status === status) && `${order.studentName} ${order.planCode} ${order.paymentReference ?? ""} ${order.evidenceNote ?? ""}`.toLowerCase().includes(search.toLowerCase()));
  const brand = data.brand ?? data.targets[0]; const pending = data.orders.filter((item) => item.status === "pending").length; const approved = data.orders.filter((item) => item.status === "approved").length;
  const plans = useMemo(() => [{ title: "Single subject", value: "Admin-set amount", note: "One published subject" }, { title: "Individual offer", value: "5,000 EGP", note: "Four subjects · list price 6,000 EGP" }, { title: "Friend groups", value: "4,700 / 4,500 EGP", note: "Per student for groups of 3 / 5 · four subjects" }], []);
  return <section className="admin-page admin-workspace-page" aria-label={payments ? "Manual payments" : "Subscriptions management"}><div className="admin-workspace-context"><span><ShieldCheck aria-hidden="true" />{data.brand?.brandDisplayName ?? "All brands"}</span><span className="admin-workspace-readonly">Manual payment records · no processor connected</span></div>
    <div className="admin-workspace-metrics"><WorkspaceMetric title="Pending review" value={data.loading || data.error ? "—" : pending} icon={CreditCard} note="Manual orders awaiting review" /><WorkspaceMetric title="Approved orders" value={data.loading || data.error ? "—" : approved} icon={Wallet} note="Enrollment granted on approval" /><WorkspaceMetric title="Rejected orders" value={data.loading || data.error ? "—" : data.orders.filter((item) => item.status === "rejected").length} icon={UsersRound} note="No enrollment created" /><WorkspaceMetric title="Paid amount recorded" value={data.loading || data.error ? "—" : fmtMoney(data.orders.filter((item) => item.status === "approved").reduce((sum, item) => sum + item.amountPaid, 0))} icon={ShieldCheck} note="From approved manual records" /></div>
    <div className="admin-workspace-split"><div className="admin-workspace-stack">{!payments && <WorkspaceCard title="Manual subscription offers" aside={<span className="admin-workspace-readonly">Through 10 Oct 2026</span>}><div className="admin-workspace-plans">{plans.map((plan) => <article key={plan.title}><span className="admin-workspace-metric__icon"><UsersRound aria-hidden="true" /></span><h3>{plan.title}</h3><strong>{plan.value}</strong><p>{plan.note}</p><button type="button" className="is-primary" onClick={() => setCreateOpen(true)}>Create subscription</button></article>)}</div></WorkspaceCard>}
      <WorkspaceCard title={payments ? "Manual payment requests" : "Subscription orders"} aside={<button type="button" className="is-primary" onClick={() => setCreateOpen(true)}><Plus aria-hidden="true" /> Create subscription</button>}><div className="admin-workspace-toolbar"><label><span className="admin-sr-only">Search payment orders</span><input type="search" placeholder="Search student, plan, or reference…" value={search} onChange={(event) => setSearch(event.target.value)} /></label><select aria-label="Filter manual orders by status" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option>{["pending", "approved", "rejected", "cancelled"].map((item) => <option key={item}>{item}</option>)}</select></div><ManualOrderTable rows={rows} loading={data.loading} error={data.error} empty={payments ? "No manual payments yet" : "No subscription orders yet"} onSelect={setSelected} /><footer className="admin-workspace-table-footer">{data.error || data.loading ? "Totals unavailable" : `${rows.length} manual records · evidence stored as text/reference metadata`}</footer></WorkspaceCard>
    </div><WorkspaceInspector title={payments ? "Payment details" : "Order details"} selected={!!selected}>{selected && <><div className="admin-workspace-receipt"><CreditCard aria-hidden="true" /><small>Amount recorded</small><strong>{fmtMoney(selected.amountPaid)}</strong><WorkspaceBadge value={selected.status} /></div><WorkspaceFields fields={[["Student", selected.studentName], ["Plan", planNames[selected.planCode] ?? selected.planCode], ["Courses", selected.courses.map((course) => course.title).join(", ")], ["Reference", selected.paymentReference || "Not provided"], ["Evidence note", selected.evidenceNote || "Not provided"], ["Created", fmtDate(selected.createdAt)]]} /><div className="admin-workspace-actions"><button type="button" disabled={selected.status !== "pending" || !brand} onClick={() => setSelected(selected)}>{selected.status === "pending" ? "Review payment" : "Order is closed"}</button><p>Approval activates only the selected student's listed course enrollments. Group pricing remains metadata in this MVP.</p></div></>}</WorkspaceInspector></div>
    {createOpen && <CreateOrderModal brand={data.brand} targets={data.targets} onClose={() => setCreateOpen(false)} onCreated={data.reload} />}{selected && selected.status === "pending" && brand && <ReviewOrderModal order={selected} brand={brand} onClose={() => setSelected(undefined)} onReviewed={data.reload} />}
  </section>;
}
export function AdminPaymentsPage() { return <ManualOrdersWorkspace payments />; }
export function AdminSubscriptionsPage() { return <ManualOrdersWorkspace payments={false} />; }
