import { ArrowLeft, BookOpen, CheckCircle2, FileText, Film, FolderPlus, GraduationCap, Layers3, Link2, Plus, Save, Trash2, Video } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { adminCourseFixtures, courseModuleById, brandLabel } from "../../../features/admin/courses/adminCourses.fixtures";

type ResourceKind = "video" | "document" | "quiz" | "file" | "link";
type Resource = { id: string; title: string; kind: ResourceKind; status: "draft" | "published" };
type Lesson = { id: string; title: string; resources: Resource[] };
type Chapter = { id: string; title: string; lessons: Lesson[] };

const seed = (courseId: string): Chapter[] => [{ id: `${courseId}-ch-1`, title: "Foundations", lessons: [{ id: `${courseId}-ls-1`, title: "Introduction", resources: [{ id: `${courseId}-r-1`, title: "Course handout", kind: "document", status: "published" }] }] }];
const labels: Record<ResourceKind, string> = { video: "Video / live session", document: "Document", quiz: "Quiz / exam", file: "File", link: "External link" };

export function AdminCourseBuilderPage() {
  const { courseId } = useParams();
  const navigate = useNavigate();
  const course = adminCourseFixtures.find((item) => item.id === courseId) ?? adminCourseFixtures[0];
  const module = courseModuleById(course.academicModuleId);
  const [chapters, setChapters] = useState<Chapter[]>(() => seed(course.id));
  const [activeChapter, setActiveChapter] = useState(chapters[0]?.id);
  const [activeLesson, setActiveLesson] = useState(chapters[0]?.lessons[0]?.id);
  const [chapterTitle, setChapterTitle] = useState("");
  const [lessonTitle, setLessonTitle] = useState("");
  const [resourceTitle, setResourceTitle] = useState("");
  const [resourceKind, setResourceKind] = useState<ResourceKind>("document");
  const [notice, setNotice] = useState("");
  const chapter = chapters.find((item) => item.id === activeChapter) ?? chapters[0];
  const lesson = chapter?.lessons.find((item) => item.id === activeLesson) ?? chapter?.lessons[0];
  const resourceIcon = (kind: ResourceKind) => kind === "video" ? <Video aria-hidden="true" /> : kind === "document" || kind === "file" ? <FileText aria-hidden="true" /> : kind === "link" ? <Link2 aria-hidden="true" /> : <CheckCircle2 aria-hidden="true" />;
  const addChapter = () => { if (!chapterTitle.trim()) return; const next = { id: `${course.id}-ch-${Date.now()}`, title: chapterTitle.trim(), lessons: [] }; setChapters((items) => [...items, next]); setActiveChapter(next.id); setChapterTitle(""); setNotice("Chapter staged locally. Connect the M2B command endpoint to persist it."); };
  const addLesson = () => { if (!chapter || !lessonTitle.trim()) return; const next = { id: `${chapter.id}-ls-${Date.now()}`, title: lessonTitle.trim(), resources: [] }; setChapters((items) => items.map((item) => item.id === chapter.id ? { ...item, lessons: [...item.lessons, next] } : item)); setActiveLesson(next.id); setLessonTitle(""); setNotice("Lesson staged locally. Connect the M2B command endpoint to persist it."); };
  const addResource = () => { if (!lesson || !resourceTitle.trim()) return; const next: Resource = { id: `${lesson.id}-r-${Date.now()}`, title: resourceTitle.trim(), kind: resourceKind, status: resourceKind === "video" ? "draft" : "published" }; setChapters((items) => items.map((item) => item.id === chapter?.id ? { ...item, lessons: item.lessons.map((entry) => entry.id === lesson.id ? { ...entry, resources: [...entry.resources, next] } : entry) } : item)); setResourceTitle(""); setNotice(resourceKind === "video" ? "Video staged as Draft — an admin must approve it before publishing." : "Resource staged locally and eligible for direct publication."); };
  const totals = useMemo(() => ({ lessons: chapters.reduce((count, item) => count + item.lessons.length, 0), resources: chapters.reduce((count, item) => count + item.lessons.reduce((inner, entry) => inner + entry.resources.length, 0), 0) }), [chapters]);

  return <section className="admin-page admin-course-builder" aria-label="Course content builder">
    <header className="admin-course-builder__header"><div><Link className="admin-course-builder__back" to="/admin/courses"><ArrowLeft aria-hidden="true" />Back to courses</Link><div className="admin-course-builder__title"><div className={`admin-course-cover is-${course.brandCode}`}><BookOpen aria-hidden="true" /></div><div><span className={`admin-course-brand is-${course.brandCode}`}>{brandLabel(course.brandCode)}</span><h1>{course.title}</h1><p>{module ? `${module.code} · Year ${module.levelNumber} · Semester ${module.semesterNumber}` : "Standalone course"}</p></div></div></div><div className="admin-course-builder__actions"><button type="button" onClick={() => setNotice("Structure is ready for the M2B persistence command.")}><Save aria-hidden="true" />Save changes</button><button className="is-primary" type="button" onClick={() => navigate(`/admin/courses/${course.id}/preview`)}>Preview course</button></div></header>
    <div className="admin-course-builder__notice" role="status"><Layers3 aria-hidden="true" /><span><strong>Course structure workspace</strong> Organize chapters, lessons, and resources against the approved academic module. Binary file storage is handled by the later R2 delivery layer.</span></div>
    <div className="admin-course-builder__grid"><aside className="admin-course-builder__outline"><header><div><h2>Course outline</h2><span>{chapters.length} chapters · {totals.lessons} lessons · {totals.resources} resources</span></div><FolderPlus aria-hidden="true" /></header>{chapters.map((item) => <div className="builder-chapter" key={item.id}><button className={item.id === chapter?.id ? "is-active" : ""} type="button" onClick={() => { setActiveChapter(item.id); setActiveLesson(item.lessons[0]?.id); }}><span>{item.title}</span><small>{item.lessons.length}</small></button>{item.id === chapter?.id && item.lessons.map((entry) => <button className={`builder-lesson${entry.id === lesson?.id ? " is-active" : ""}`} key={entry.id} type="button" onClick={() => setActiveLesson(entry.id)}><span>{entry.title}</span><small>{entry.resources.length}</small></button>)}</div>)}<div className="builder-inline-form"><input aria-label="New chapter title" value={chapterTitle} onChange={(event) => setChapterTitle(event.target.value)} placeholder="New chapter title" /><button type="button" onClick={addChapter} aria-label="Add chapter"><Plus aria-hidden="true" /></button></div></aside>
      <main className="admin-course-builder__main"><div className="builder-panel"><header><div><span className="builder-eyebrow">{chapter?.title ?? "Select a chapter"}</span><h2>{lesson?.title ?? "Add your first lesson"}</h2></div><GraduationCap aria-hidden="true" /></header>{lesson ? <div className="builder-resources"><div className="builder-section-label">Resources in this lesson</div>{lesson.resources.map((item) => <div className="builder-resource" key={item.id}>{resourceIcon(item.kind)}<div><strong>{item.title}</strong><span>{labels[item.kind]}</span></div><span className={`builder-resource-status is-${item.status}`}>{item.status === "published" ? "Published" : "Needs admin approval"}</span><button type="button" aria-label={`Remove ${item.title}`} onClick={() => setChapters((items) => items.map((parent) => parent.id === chapter?.id ? { ...parent, lessons: parent.lessons.map((entry) => entry.id === lesson.id ? { ...entry, resources: entry.resources.filter((resource) => resource.id !== item.id) } : entry) } : parent))}><Trash2 aria-hidden="true" /></button></div>)}{lesson.resources.length === 0 && <div className="builder-empty">No resources yet. Add a PDF, exam, link, or session below.</div>}<div className="builder-add-resource"><input aria-label="Resource title" value={resourceTitle} onChange={(event) => setResourceTitle(event.target.value)} placeholder="Resource title" /><select aria-label="Resource type" value={resourceKind} onChange={(event) => setResourceKind(event.target.value as ResourceKind)}>{Object.entries(labels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><button className="is-primary" type="button" onClick={addResource}><Plus aria-hidden="true" />Add resource</button></div><p className="builder-policy"><Film aria-hidden="true" /><span><strong>Publishing policy:</strong> documents, files, quizzes, and links can be published directly. Video and live-session resources stay Draft until an admin approves them.</span></p></div> : <div className="builder-empty builder-empty--lesson">Create a lesson from the form below to start adding resources.</div>}<div className="builder-add-lesson"><input aria-label="New lesson title" value={lessonTitle} onChange={(event) => setLessonTitle(event.target.value)} placeholder="Lesson title" /><button type="button" onClick={addLesson}><Plus aria-hidden="true" />Add lesson to {chapter?.title ?? "chapter"}</button></div></div><div className="builder-panel builder-panel--guide"><h3>How this maps to the curriculum</h3><p>{module ? `This course is anchored to ${module.code} ${module.title}. Keep each chapter and lesson focused on that approved module; do not create a second academic module from the builder.` : "Map this course to an approved academic module before publishing curriculum content."}</p></div></main>
    </div>{notice && <div className="admin-course-toast" role="status">{notice}<button type="button" onClick={() => setNotice("")} aria-label="Dismiss notice">×</button></div>}
  </section>;
}
