import type { HttpJsonResponse } from "../http-types";
export function jsonResponse(statusCode: number, body: Readonly<Record<string, unknown>>, headers: Readonly<Record<string, string>> = {}): HttpJsonResponse { return { statusCode, body, headers: { "content-type": "application/json; charset=utf-8", ...headers } }; }
export function methodNotAllowedResponse(correlationId: string, allowedMethods: readonly string[] = ["GET"]): HttpJsonResponse { return jsonResponse(405, { ok: false, error: { code: "method_not_allowed", message: "The requested method is not supported.", correlationId } }, { allow: allowedMethods.join(", "), "x-correlation-id": correlationId }); }
export function notFoundResponse(correlationId: string): HttpJsonResponse { return jsonResponse(404, { ok: false, error: { code: "not_found", message: "The requested resource was not found.", correlationId } }, { "x-correlation-id": correlationId }); }
export function badRequestResponse(correlationId: string, message: string, details?: Readonly<Record<string, unknown>>): HttpJsonResponse { return jsonResponse(400, { ok: false, error: { code: "bad_request", message, correlationId, ...(details ? { details } : {}) } }, { "x-correlation-id": correlationId }); }
export function internalErrorResponse(correlationId: string): HttpJsonResponse { return jsonResponse(500, { ok: false, error: { code: "internal_error", message: "An unexpected server error occurred.", correlationId } }, { "x-correlation-id": correlationId }); }
export function serviceUnavailableResponse(correlationId: string): HttpJsonResponse { return jsonResponse(503, { ok: false, error: { code: "dependency_unavailable", message: "The requested data is temporarily unavailable.", correlationId } }, { "x-correlation-id": correlationId }); }
export function unauthorizedResponse(correlationId: string): HttpJsonResponse { return jsonResponse(401, { ok: false, error: { code: "unauthenticated", message: "Authentication is required.", correlationId } }, { "x-correlation-id": correlationId }); }
export function forbiddenResponse(correlationId: string): HttpJsonResponse { return jsonResponse(403, { ok: false, error: { code: "forbidden", message: "Administrative access is not available.", correlationId } }, { "x-correlation-id": correlationId }); }
export function conflictResponse(correlationId: string): HttpJsonResponse { return jsonResponse(409, { ok: false, error: { code: "conflict", message: "The requested change conflicts with the current state.", correlationId } }, { "x-correlation-id": correlationId }); }
