/** Pure Prompt 52 contract self-test. It never opens a transport, pool, repository, or network connection. */
import type { AdminSensitiveCommandMetadata, CreateBrandCourseCommand, CreateInstructorCommand } from "../../../contracts/admin";
import { validateAssignInstructorToBrandCommand, validateAssignInstructorToCourseCommand, validateBrandCourseDefinition, validateCreateBrandCourseCommand, validateCreateInstructorCommand, validateSetBrandCourseStatusCommand, validateSetBrandInstructorStatusCommand, validateSetCourseInstructorStatusCommand, validateSetInstructorStatusCommand, validateUpdateBrandCourseCommand, validateUpdateInstructorCommand } from "../../../core/validation";
import { validateAssignInstructorToBrandPolicy, validateAssignInstructorToCoursePolicy, validateBrandCourseStatusTransition, validateM2BrandCourseDefinitionPolicy } from "../../../core/policies";

type Case = { readonly name: string; readonly passed: boolean; readonly details?: Record<string, unknown> };
export type AdminM2CommandContractsSelfTestResult = { readonly passed: boolean; readonly cases: readonly Case[] };

const id = "123e4567-e89b-12d3-a456-426614174000";
const otherId = "123e4567-e89b-12d3-a456-426614174001";
const metadata: AdminSensitiveCommandMetadata = { platform: { platformId: id, platformCode: "medway" }, reason: "Controlled contract self-test.", correlationId: "m2-command-contract-selftest", idempotencyKey: "m2-command-contract-selftest-idempotency" };
const instructor: CreateInstructorCommand = { metadata, displayName: "Dr. Example", professionalTitle: "Professor" };
const course: CreateBrandCourseCommand = { metadata, brandId: id, courseCode: "MED-101", title: "Example course", courseScope: "curriculum", academicModuleId: otherId, status: "draft" };

function assert(value: unknown, message: string): asserts value { if (!value) throw new Error(message); }
function pass(result: { readonly ok: boolean }, label: string): void { assert(result.ok, `${label} should succeed`); }
function failure(result: { readonly ok: boolean; readonly error?: { readonly code: string } }, code: string, label: string): void { assert(!result.ok && result.error?.code === code, `${label} should fail with ${code}`); }
async function record(name: string, run: () => void | Promise<void>): Promise<Case> { try { await run(); return { name, passed: true }; } catch (error) { return { name, passed: false, details: { message: error instanceof Error ? error.message : "Unexpected self-test failure." } }; } }

export async function runAdminM2CommandContractsSelfTest(): Promise<AdminM2CommandContractsSelfTestResult> {
  const cases: Case[] = [];
  cases.push(await record("valid global instructor create is syntactically accepted", () => pass(validateCreateInstructorCommand(instructor), "create instructor")));
  cases.push(await record("blank instructor name is rejected", () => failure(validateCreateInstructorCommand({ ...instructor, displayName: "  " }), "validation_failed", "blank instructor")));
  cases.push(await record("instructor status commands accept only active/inactive", () => { pass(validateSetInstructorStatusCommand({ metadata, instructorId: id, status: "active" }), "active instructor"); failure(validateSetInstructorStatusCommand({ metadata, instructorId: id, status: "suspended" as "active" }), "validation_failed", "invalid instructor status"); }));
  cases.push(await record("instructor update requires an explicit mutable field", () => { pass(validateUpdateInstructorCommand({ metadata, instructorId: id, displayName: "Dr. Updated" }), "instructor update"); failure(validateUpdateInstructorCommand({ metadata, instructorId: id }), "validation_failed", "empty instructor update"); }));
  cases.push(await record("brand instructor commands require canonical identifiers", () => { pass(validateAssignInstructorToBrandCommand({ metadata, brandId: id, instructorId: otherId }), "brand assignment"); failure(validateAssignInstructorToBrandCommand({ metadata, brandId: "bad", instructorId: otherId }), "validation_failed", "invalid brand"); pass(validateSetBrandInstructorStatusCommand({ metadata, brandId: id, instructorId: otherId, status: "inactive" }), "brand instructor status"); }));
  cases.push(await record("curriculum course requires an academic module", () => { pass(validateCreateBrandCourseCommand(course), "curriculum course"); failure(validateCreateBrandCourseCommand({ ...course, academicModuleId: null }), "validation_failed", "curriculum module requirement"); }));
  cases.push(await record("standalone course accepts a null academic module", () => pass(validateCreateBrandCourseCommand({ ...course, courseScope: "standalone", academicModuleId: null }), "standalone course")));
  cases.push(await record("course scope, status, code, and title validation are strict", () => { failure(validateBrandCourseDefinition(metadata.correlationId, "invalid", null), "validation_failed", "invalid scope"); failure(validateCreateBrandCourseCommand({ ...course, courseCode: " " }), "validation_failed", "blank course code"); failure(validateCreateBrandCourseCommand({ ...course, title: " " }), "validation_failed", "blank course title"); failure(validateSetBrandCourseStatusCommand({ metadata, brandId: id, courseId: otherId, status: "inactive" as "draft" }), "validation_failed", "invalid course status"); }));
  cases.push(await record("course update validates only explicit mutable fields", () => { pass(validateUpdateBrandCourseCommand({ metadata, brandId: id, courseId: otherId, title: "Revised title" }), "course update"); failure(validateUpdateBrandCourseCommand({ metadata, brandId: id, courseId: otherId }), "validation_failed", "empty course update"); failure(validateUpdateBrandCourseCommand({ metadata, brandId: id, courseId: otherId, courseScope: "curriculum", academicModuleId: null }), "validation_failed", "invalid curriculum update"); }));
  cases.push(await record("course instructor commands require brand, course, instructor, and legal status", () => { pass(validateAssignInstructorToCourseCommand({ metadata, brandId: id, courseId: otherId, instructorId: "123e4567-e89b-12d3-a456-426614174002" }), "course assignment"); failure(validateAssignInstructorToCourseCommand({ metadata, brandId: id, courseId: "bad", instructorId: otherId }), "validation_failed", "invalid course ID"); pass(validateSetCourseInstructorStatusCommand({ metadata, brandId: id, courseId: otherId, instructorId: "123e4567-e89b-12d3-a456-426614174002", status: "inactive" }), "course instructor status"); }));
  cases.push(await record("course lifecycle is conservative and idempotent only for same status", () => { pass(validateBrandCourseStatusTransition(metadata.correlationId, "draft", "published"), "draft publish"); pass(validateBrandCourseStatusTransition(metadata.correlationId, "published", "archived"), "published archive"); const same = validateBrandCourseStatusTransition(metadata.correlationId, "draft", "draft"); assert(same.ok && same.value.idempotent, "same status must be idempotent"); failure(validateBrandCourseStatusTransition(metadata.correlationId, "archived", "draft"), "lifecycle_transition_denied", "archived reopen"); failure(validateBrandCourseStatusTransition(metadata.correlationId, "archived", "published"), "lifecycle_transition_denied", "archived republish"); }));
  cases.push(await record("stateful policy facts enforce active same-brand teaching relationships", () => { pass(validateM2BrandCourseDefinitionPolicy(metadata.correlationId, { courseScope: "standalone", academicModuleId: null, academicModuleExists: false }), "standalone policy"); failure(validateM2BrandCourseDefinitionPolicy(metadata.correlationId, { courseScope: "curriculum", academicModuleId: otherId, academicModuleExists: false }), "policy_validation_failed", "missing module policy"); pass(validateAssignInstructorToBrandPolicy(metadata.correlationId, { brandExists: true, brandIsActive: true, instructorExists: true, instructorStatus: "active" }), "brand assignment policy"); failure(validateAssignInstructorToBrandPolicy(metadata.correlationId, { brandExists: true, brandIsActive: true, instructorExists: true, instructorStatus: "inactive" }), "policy_validation_failed", "inactive instructor assignment"); pass(validateAssignInstructorToCoursePolicy(metadata.correlationId, { brandExists: true, brandIsActive: true, instructorExists: true, instructorStatus: "active", courseExistsInBrand: true, brandInstructorStatus: "active" }), "same brand course assignment"); failure(validateAssignInstructorToCoursePolicy(metadata.correlationId, { brandExists: true, brandIsActive: true, instructorExists: true, instructorStatus: "active", courseExistsInBrand: false, brandInstructorStatus: "active" }), "policy_validation_failed", "cross brand course assignment"); }));
  cases.push(await record("academic reference write contracts are deliberately absent", () => { const source = `${validateCreateInstructorCommand} ${validateCreateBrandCourseCommand}`; assert(!source.includes("AcademicModule"), "Academic reference command must not exist in Prompt 52 contracts"); }));
  return { passed: cases.every((item) => item.passed), cases };
}

if (process.argv[1]?.endsWith("admin-m2-command-contracts.selftest.js")) runAdminM2CommandContractsSelfTest().then((result) => { if (!result.passed) throw new Error(JSON.stringify(result.cases.filter((item) => !item.passed))); console.log("admin M2 command contracts selftest passed"); });
