import { Pool } from "pg";
import { adminCoreError, type AdminCoreError } from "../../core/errors";
import type { AdminM2ActionEvidence,AdminM2BrandCourseState,AdminM2BrandInstructorState,AdminM2CourseInstructorState,AdminM2IdempotencyIdentity,AdminM2InstructorState,AdminM2Receipt,AdminM2WriteTransaction,AdminM2WriteTransactionRunner } from "../../core/repositories";
import { fail,ok,type Result } from "../../shared";
import { requiredPersistenceTimestamp } from "../supabase/repositories/persistence-timestamp";
import { resolvePostgresPoolConfiguration } from "./postgres-pool-config";
import type { SupabaseBoundaryEnvironment } from "../supabase/supabase-config";

export interface PgWriteQueryResult<Row extends Record<string,unknown>=Record<string,unknown>>{readonly rows:readonly Row[];}
export interface PgWriteClientLike{query<Row extends Record<string,unknown>=Record<string,unknown>>(text:string,values?:readonly unknown[]):Promise<PgWriteQueryResult<Row>>;release():void;}
export interface PgWritePoolLike{connect():Promise<PgWriteClientLike>;end():Promise<void>;}
export type PostgresWritePoolFactory=(configuration:ConstructorParameters<typeof Pool>[0])=>PgWritePoolLike;
class WriteError extends Error{constructor(readonly kind:"persistence"|"evidence"|"idempotency_race"|"conflict"|"not_found",readonly constraint?:string){super("Admin M2 transaction failed.")}}
const facts=(e:unknown)=>e&&typeof e==="object"?{code:"code" in e?String(e.code):"",constraint:"constraint" in e?String(e.constraint):""}:{code:"",constraint:""};
function translated(error:unknown):WriteError{if(error instanceof WriteError)return error;const f=facts(error);if(f.code==="23505"&&f.constraint==="admin_command_receipts_actor_idempotency_key_key")return new WriteError("idempotency_race",f.constraint);if(f.code==="23505"||f.code==="40001")return new WriteError("conflict",f.constraint);if(f.code==="23503")return new WriteError("not_found",f.constraint);return new WriteError("persistence",f.constraint);}
const str=(r:Record<string,unknown>,k:string)=>{const v=r[k];if(typeof v!=="string"||!v)throw new WriteError("persistence");return v};
const nullable=(r:Record<string,unknown>,k:string)=>{const v=r[k];if(v==null)return null;if(typeof v!=="string")throw new WriteError("persistence");return v};
const integer=(r:Record<string,unknown>,k:string)=>{const v=r[k];const n=typeof v==="string"?Number(v):v;if(typeof n!=="number"||!Number.isSafeInteger(n))throw new WriteError("persistence");return n};
const object=(r:Record<string,unknown>,k:string)=>{const v=r[k];if(!v||typeof v!=="object"||Array.isArray(v))throw new WriteError("persistence");return v as Readonly<Record<string,unknown>>};
const assignmentStatus=(v:unknown)=>{if(v==="active"||v==="inactive")return v;throw new WriteError("persistence")};
const instructorStatus=(v:unknown)=>{if(v==="active"||v==="inactive"||v==="archived")return v;throw new WriteError("persistence")};
const courseStatus=(v:unknown)=>{if(v==="draft"||v==="published"||v==="archived")return v;throw new WriteError("persistence")};
const classification=(v:unknown)=>{if(v==="academic_module_offering"||v==="standalone")return v;throw new WriteError("persistence")};
const instructor=(r:Record<string,unknown>):AdminM2InstructorState=>({id:str(r,"id"),code:str(r,"code"),displayName:str(r,"display_name"),status:instructorStatus(r.status),version:integer(r,"version"),updatedAt:requiredPersistenceTimestamp(r.updated_at)});
const brandAssignment=(r:Record<string,unknown>):AdminM2BrandInstructorState=>({id:str(r,"id"),brandId:str(r,"brand_id"),instructorId:str(r,"instructor_id"),status:assignmentStatus(r.status),version:integer(r,"version"),updatedAt:requiredPersistenceTimestamp(r.updated_at)});
const course=(r:Record<string,unknown>):AdminM2BrandCourseState=>({id:str(r,"id"),brandId:str(r,"brand_id"),academicModuleId:nullable(r,"academic_module_id"),code:str(r,"code"),title:str(r,"title"),classification:classification(r.classification),status:courseStatus(r.status),version:integer(r,"version"),updatedAt:requiredPersistenceTimestamp(r.updated_at)});
const courseAssignment=(r:Record<string,unknown>):AdminM2CourseInstructorState=>({id:str(r,"id"),brandId:str(r,"brand_id"),courseId:str(r,"course_id"),instructorBrandAssignmentId:str(r,"instructor_brand_assignment_id"),instructorId:str(r,"instructor_id"),status:assignmentStatus(r.status),version:integer(r,"version"),updatedAt:requiredPersistenceTimestamp(r.updated_at)});
const receipt=(r:Record<string,unknown>):AdminM2Receipt=>({receiptId:str(r,"receipt_id"),auditEventId:str(r,"audit_event_id"),requestFingerprint:str(r,"request_fingerprint"),resultSummary:object(r,"result_summary")});
const INSTRUCTOR="id,code,display_name,status,version,updated_at";
const BRAND_ASSIGNMENT="id,brand_id,instructor_id,status,version,updated_at";
const COURSE="id,brand_id,academic_module_id,code,title,classification,status,version,updated_at";
const COURSE_ASSIGNMENT="cia.id,cia.brand_id,cia.course_id,cia.instructor_brand_assignment_id,iba.instructor_id,cia.status,cia.version,cia.updated_at";

class Transaction implements AdminM2WriteTransaction{
  constructor(private readonly client:PgWriteClientLike){}
  private async one<R extends Record<string,unknown>>(text:string,values:readonly unknown[]):Promise<R|null>{try{return(await this.client.query<R>(text,values)).rows[0]??null}catch(e){throw translated(e)}}
  async lockExecutionIdentity(i:{scopeKind:"global"|"brand";brandId:string|null;adminProfileId:string}){const p=await this.one("select id from app.admin_profiles where id=$1 and status='active' for update",[i.adminProfileId]);if(!p)return false;if(i.scopeKind==="global")return i.brandId===null;return Boolean(i.brandId&&await this.one("select id from app.educational_brands where id=$1 and status='active' for update",[i.brandId]));}
  async findReceipt(i:AdminM2IdempotencyIdentity){const row=await this.one("select r.id as receipt_id,a.id as audit_event_id,r.request_fingerprint,r.result_summary from app.admin_command_receipts r join app.admin_audit_events a on a.receipt_id=r.id where r.actor_admin_profile_id=$1 and r.idempotency_key=$2",[i.adminProfileId,i.idempotencyKey]);return row?receipt(row):null;}
  async lockInstructor(id:string){const r=await this.one(`select ${INSTRUCTOR} from app.instructors where id=$1 for update`,[id]);return r?instructor(r):null;}
  async lockAcademicModule(id:string){return Boolean(await this.one("select id from app.academic_modules where id=$1 and review_status<>'retired' for update",[id]));}
  async lockBrandInstructor(brandId:string,instructorId:string){const r=await this.one(`select ${BRAND_ASSIGNMENT} from app.instructor_brand_assignments where brand_id=$1 and instructor_id=$2 for update`,[brandId,instructorId]);return r?brandAssignment(r):null;}
  async lockBrandCourse(brandId:string,courseId:string){const r=await this.one(`select ${COURSE} from app.brand_courses where brand_id=$1 and id=$2 for update`,[brandId,courseId]);return r?course(r):null;}
  async lockBrandCourseByCode(brandId:string,code:string){const r=await this.one(`select ${COURSE} from app.brand_courses where brand_id=$1 and code=$2 for update`,[brandId,code]);return r?course(r):null;}
  async lockCourseInstructor(brandId:string,courseId:string,instructorId:string){const r=await this.one(`select ${COURSE_ASSIGNMENT} from app.course_instructor_assignments cia join app.instructor_brand_assignments iba on iba.id=cia.instructor_brand_assignment_id and iba.brand_id=cia.brand_id where cia.brand_id=$1 and cia.course_id=$2 and iba.instructor_id=$3 for update of cia`,[brandId,courseId,instructorId]);return r?courseAssignment(r):null;}
  async insertInstructor(i:{code:string;displayName:string}){const r=await this.one(`insert into app.instructors(code,display_name) values($1,$2) returning ${INSTRUCTOR}`,[i.code,i.displayName]);if(!r)throw new WriteError("persistence");return instructor(r);}
  async updateInstructor(i:{id:string;code:string;displayName:string;status:"active"|"inactive"|"archived"}){const r=await this.one(`update app.instructors set code=$2,display_name=$3,status=$4 where id=$1 returning ${INSTRUCTOR}`,[i.id,i.code,i.displayName,i.status]);if(!r)throw new WriteError("not_found");return instructor(r);}
  async insertBrandInstructor(i:{brandId:string;instructorId:string}){const r=await this.one(`insert into app.instructor_brand_assignments(brand_id,instructor_id) values($1,$2) returning ${BRAND_ASSIGNMENT}`,[i.brandId,i.instructorId]);if(!r)throw new WriteError("persistence");return brandAssignment(r);}
  async updateBrandInstructorStatus(i:{id:string;status:"active"|"inactive"}){const r=await this.one(`update app.instructor_brand_assignments set status=$2 where id=$1 returning ${BRAND_ASSIGNMENT}`,[i.id,i.status]);if(!r)throw new WriteError("not_found");return brandAssignment(r);}
  async insertBrandCourse(i:{brandId:string;academicModuleId:string|null;code:string;title:string;classification:"academic_module_offering"|"standalone"}){const r=await this.one(`insert into app.brand_courses(brand_id,academic_module_id,code,title,classification) values($1,$2,$3,$4,$5) returning ${COURSE}`,[i.brandId,i.academicModuleId,i.code,i.title,i.classification]);if(!r)throw new WriteError("persistence");return course(r);}
  async updateBrandCourse(i:{id:string;academicModuleId:string|null;title:string;classification:"academic_module_offering"|"standalone";status:"draft"|"published"|"archived"}){const r=await this.one(`update app.brand_courses set academic_module_id=$2,title=$3,classification=$4,status=$5 where id=$1 returning ${COURSE}`,[i.id,i.academicModuleId,i.title,i.classification,i.status]);if(!r)throw new WriteError("not_found");return course(r);}
  async insertCourseInstructor(i:{brandId:string;courseId:string;instructorId:string}){const r=await this.one(`insert into app.course_instructor_assignments(brand_id,course_id,instructor_brand_assignment_id) select $1,$2,id from app.instructor_brand_assignments where brand_id=$1 and instructor_id=$3 returning id,brand_id,course_id,instructor_brand_assignment_id,status,version,updated_at`,[i.brandId,i.courseId,i.instructorId]);if(!r)throw new WriteError("not_found");return courseAssignment({...r,instructor_id:i.instructorId});}
  async updateCourseInstructorStatus(i:{id:string;status:"active"|"inactive"}){const r=await this.one(`update app.course_instructor_assignments cia set status=$2 from app.instructor_brand_assignments iba where cia.id=$1 and iba.id=cia.instructor_brand_assignment_id returning ${COURSE_ASSIGNMENT}`,[i.id,i.status]);if(!r)throw new WriteError("not_found");return courseAssignment(r);}
  async writeEvidence(i:AdminM2ActionEvidence){try{const rr=await this.client.query<{id:string}>("insert into app.admin_command_receipts(actor_admin_profile_id,scope_kind,brand_id,command_name,target_type,target_id,idempotency_key,request_fingerprint,correlation_id,outcome,result_summary) values($1,$2,$3,$4,$5,$6,$7,$8,$9,'succeeded',$10::jsonb) returning id",[i.identity.adminProfileId,i.identity.scopeKind,i.identity.brandId,i.identity.commandName,i.targetType,i.targetId,i.identity.idempotencyKey,i.requestFingerprint,i.correlationId,JSON.stringify(i.resultSummary)]);const receiptId=rr.rows[0]?.id;if(!receiptId)throw new WriteError("evidence");const ar=await this.client.query<{id:string}>("insert into app.admin_audit_events(receipt_id,actor_admin_profile_id,scope_kind,brand_id,command_name,target_type,target_id,reason,before_summary,after_summary,metadata) values($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10::jsonb,$11::jsonb) returning id",[receiptId,i.identity.adminProfileId,i.identity.scopeKind,i.identity.brandId,i.identity.commandName,i.targetType,i.targetId,i.reason,i.beforeSummary===null?null:JSON.stringify(i.beforeSummary),JSON.stringify(i.afterSummary),JSON.stringify(i.metadata)]);const auditEventId=ar.rows[0]?.id;if(!auditEventId)throw new WriteError("evidence");return{receiptId,auditEventId}}catch(e){const m=translated(e);if(m.kind==="idempotency_race")throw m;throw new WriteError("evidence",m.constraint)}}
}
function failure(e:WriteError,c:string):AdminCoreError{if(e.kind==="idempotency_race")return adminCoreError("conflict","The administrative command raced with another request.",c,{reason:"idempotency_race"});if(e.kind==="conflict")return adminCoreError("conflict","The requested change conflicts with current state.",c);if(e.kind==="not_found")return adminCoreError("target_not_found","The requested target was not found.",c);if(e.kind==="evidence")return adminCoreError("audit_write_failed","Administrative evidence could not be written.",c);return adminCoreError("persistence_failed","The administrative transaction could not be completed.",c);}
export class PostgresAdminM2WriteTransactionRunner implements AdminM2WriteTransactionRunner{private closePromise?:Promise<void>;constructor(private readonly pool:PgWritePoolLike){}async run<T>(c:string,work:(t:AdminM2WriteTransaction)=>Promise<Result<T,AdminCoreError>>){let client:PgWriteClientLike|undefined;let begun=false;try{client=await this.pool.connect();await client.query("BEGIN");begun=true;const result=await work(new Transaction(client));if(!result.ok){await client.query("ROLLBACK");begun=false;return result}await client.query("COMMIT");begun=false;return result}catch(e){if(client&&begun)try{await client.query("ROLLBACK")}catch{}return fail(failure(translated(e),c))}finally{client?.release()}}async findCommittedReceipt(i:AdminM2IdempotencyIdentity,c:string){let client:PgWriteClientLike|undefined;try{client=await this.pool.connect();return ok(await new Transaction(client).findReceipt(i))}catch(e){return fail(failure(translated(e),c))}finally{client?.release()}}close(){if(!this.closePromise)this.closePromise=this.pool.end().catch(()=>{throw new Error("Admin M2 write pool could not be closed.")});return this.closePromise}}
export function createPostgresAdminM2WriteTransactionRunner(environment:SupabaseBoundaryEnvironment=process.env,poolFactory:PostgresWritePoolFactory=(configuration)=>new Pool(configuration)){const c=resolvePostgresPoolConfiguration(environment);return new PostgresAdminM2WriteTransactionRunner(poolFactory({host:c.host,port:c.port,...(c.user?{user:c.user}:{}),...(c.password?{password:c.password}:{}),database:c.database,max:c.max,idleTimeoutMillis:c.idleTimeoutMillis,connectionTimeoutMillis:c.connectionTimeoutMillis,ssl:{rejectUnauthorized:true,...(c.trustedRootCertificate?{ca:c.trustedRootCertificate}:{})}}))}
