import type { AdminAdminActionItem, AdminAuditLogItem, AdminBrandContext, AdminPlatformContext, AdminSecurityEventItem } from "../../contracts/admin";

export interface AdminOverviewCounts { readonly pendingPaymentReviews: number; readonly pendingRefunds: number; readonly suspiciousSecurityEvents: number; readonly activeSubscriptions: number; readonly expiredSubscriptions: number; readonly activeGrants: number; readonly revokedGrants: number; readonly contentAwaitingRelease: number; readonly assessmentsAwaitingReview: number; }
export interface AdminOverviewReadModel { readonly brand: AdminBrandContext; /** @deprecated Compatibility projection for existing consumers. */ readonly platform: AdminPlatformContext; readonly counts: AdminOverviewCounts; readonly recent: { readonly auditLogs: readonly AdminAuditLogItem[]; readonly adminActions: readonly AdminAdminActionItem[]; readonly securityEvents: readonly AdminSecurityEventItem[] }; }
export interface AdminReadModels { getOverview(brandId: string): AdminOverviewReadModel | undefined; }
export class InMemoryAdminReadModels implements AdminReadModels { constructor(private readonly overviewByBrand: ReadonlyMap<string, AdminOverviewReadModel>) {} getOverview(brandId: string) { return this.overviewByBrand.get(brandId); } }
const scope = (brandId: string, brandCode: "medway" | "elite", brandDisplayName: string) => ({ brand: { brandId, brandCode, brandDisplayName }, platform: { platformId: brandId, platformCode: brandCode, platformDisplayName: brandDisplayName } });
const sample = (brandId: string, brandCode: "medway" | "elite", displayName: string, prefix: string, counts: AdminOverviewCounts): AdminOverviewReadModel => { const { brand, platform } = scope(brandId, brandCode, displayName); return { brand, platform, counts, recent: { auditLogs: [{ id: `${prefix}-audit-001`, platform, occurredAt: "2026-01-01T10:00:00.000Z", actorType: "admin", actorId: `${prefix}-admin-001`, action: "overview_read", entityType: "brand", entityId: brand.brandId, correlationId: `${prefix}-correlation-001` }], adminActions: [{ id: `${prefix}-action-001`, platform, adminUserId: `${prefix}-admin-001`, actionType: "read_overview", targetEntityType: "brand", targetEntityId: brand.brandId, authorizationReference: `${prefix}-authorization-redacted-001`, occurredAt: "2026-01-01T10:00:00.000Z", outcome: "succeeded" }], securityEvents: [{ id: `${prefix}-security-001`, platform, eventType: "admin_security", occurredAt: "2026-01-01T10:00:00.000Z", userId: `${prefix}-user-001`, sessionId: null, severity: "info", metadataReference: `${prefix}-security-redacted-001` }] } }; };
export function createInMemoryAdminReadModels(): InMemoryAdminReadModels { return new InMemoryAdminReadModels(new Map([
  ["platform-medway", sample("platform-medway", "medway", "Medway", "med", { pendingPaymentReviews: 2, pendingRefunds: 1, suspiciousSecurityEvents: 2, activeSubscriptions: 3, expiredSubscriptions: 1, activeGrants: 4, revokedGrants: 1, contentAwaitingRelease: 2, assessmentsAwaitingReview: 1 })],
  ["platform-elite", sample("platform-elite", "elite", "Elite", "elite", { pendingPaymentReviews: 1, pendingRefunds: 0, suspiciousSecurityEvents: 1, activeSubscriptions: 1, expiredSubscriptions: 0, activeGrants: 1, revokedGrants: 0, contentAwaitingRelease: 1, assessmentsAwaitingReview: 0 })],
])); }