import type { BrandScope } from "../../../core/brand-scope";
import { repositoryErr, repositoryOk, type RepositoryResult } from "../../../core/persistence";
import type * as M1 from "../../../core/repositories/m1-read-repositories";
import type { ReadQueryRequest, ReadQueryTransport } from "../read-query-transport";
import { nullablePersistenceTimestamp, requiredPersistenceTimestamp } from "./persistence-timestamp";

type Row=Readonly<Record<string,unknown>>;
const str=(r:Row,k:string)=>{const v=r[k];if(typeof v!=="string"||!v)throw new Error(k);return v};
const nullable=(r:Row,k:string)=>{const v=r[k];if(v==null)return null;if(typeof v!=="string")throw new Error(k);return v};
const integer=(r:Row,k:string)=>{const v=r[k];const n=typeof v==="string"?Number(v):v;if(typeof n!=="number"||!Number.isSafeInteger(n))throw new Error(k);return n};
const one=<T extends string>(r:Row,k:string,a:readonly T[])=>{const v=str(r,k);if(!a.includes(v as T))throw new Error(k);return v as T};
const strings=(r:Row,k:string)=>{const v=r[k];if(!Array.isArray(v)||v.some(x=>typeof x!=="string"))throw new Error(k);return Object.freeze([...new Set(v as string[])].sort())};
const versioned=(r:Row)=>({id:str(r,"id"),createdAt:requiredPersistenceTimestamp(r.created_at),updatedAt:requiredPersistenceTimestamp(r.updated_at),version:integer(r,"version")});
const brand=(r:Row):M1.M1EducationalBrand=>({...versioned(r),code:one(r,"code",["medway","elite"]),name:str(r,"name"),slug:str(r,"slug"),status:one(r,"status",["active","inactive"])});
const user=(r:Row):M1.M1AppUser=>({...versioned(r),authUserId:str(r,"auth_user_id"),primaryEmail:null,primaryPhone:null,status:one(r,"status",["pending","active","suspended","disabled"])});
const membership=(r:Row):M1.M1BrandMembership=>({...versioned(r),appUserId:str(r,"app_user_id"),brandId:str(r,"brand_id"),status:one(r,"status",["pending","active","suspended","ended","revoked"]),validFrom:requiredPersistenceTimestamp(r.valid_from),validUntil:nullablePersistenceTimestamp(r.valid_until)});
const student=(r:Row):M1.M1StudentProfile=>({...versioned(r),brandMembershipId:str(r,"brand_membership_id"),appUserId:str(r,"app_user_id"),brandId:str(r,"brand_id"),status:one(r,"status",["active","inactive","archived"])});
const profile=(r:Row):M1.M1AdminProfile=>({...versioned(r),appUserId:str(r,"app_user_id"),status:one(r,"status",["active","suspended","disabled"])});
const permission=(r:Row):M1.M1AdminPermission=>({...versioned(r),code:str(r,"code"),description:str(r,"description"),status:one(r,"status",["active","retired"])});
const role=(r:Row):M1.M1AdminRole=>({...versioned(r),code:str(r,"code"),name:str(r,"name"),assignmentScope:one(r,"assignment_scope",["platform"] as const),status:one(r,"status",["active","retired"])});
const rolePermission=(r:Row):M1.M1AdminRolePermission=>({roleId:str(r,"admin_role_id"),permissionId:str(r,"admin_permission_id"),createdAt:requiredPersistenceTimestamp(r.created_at)});
const assignment=(r:Row):M1.M1AdminRoleAssignment=>({...versioned(r),adminProfileId:str(r,"admin_profile_id"),roleId:str(r,"admin_role_id"),assignedByAdminProfileId:nullable(r,"assigned_by_admin_profile_id"),validFrom:requiredPersistenceTimestamp(r.valid_from),validUntil:nullablePersistenceTimestamp(r.valid_until),status:one(r,"status",["active","inactive","expired","revoked"])});
const authorization=(r:Row):M1.M1AdminAuthorizationSnapshot=>({appUser:{id:str(r,"app_user_id"),authUserId:str(r,"auth_user_id"),primaryEmail:null,primaryPhone:null,status:one(r,"app_user_status",["pending","active","suspended","disabled"]),createdAt:requiredPersistenceTimestamp(r.app_user_created_at),updatedAt:requiredPersistenceTimestamp(r.app_user_updated_at),version:integer(r,"app_user_version")},adminProfile:{id:str(r,"admin_profile_id"),appUserId:str(r,"app_user_id"),status:one(r,"admin_profile_status",["active","suspended","disabled"]),createdAt:requiredPersistenceTimestamp(r.admin_profile_created_at),updatedAt:requiredPersistenceTimestamp(r.admin_profile_updated_at),version:integer(r,"admin_profile_version")},roleCodes:strings(r,"role_codes"),permissionCodes:strings(r,"permission_codes")});

abstract class Base{constructor(protected readonly transport:ReadQueryTransport){}protected async one(q:ReadQueryRequest,c?:string):Promise<RepositoryResult<Row>>{try{const r=(await this.transport.query<Row>(q)).rows[0];return r?repositoryOk(r):repositoryErr({code:"not_found",message:"Requested record was not found.",correlationId:c})}catch{return repositoryErr({code:"query_failed",message:"Persistence read failed.",correlationId:c})}}protected async many(q:ReadQueryRequest,c?:string):Promise<RepositoryResult<readonly Row[]>>{try{return repositoryOk((await this.transport.query<Row>(q)).rows)}catch{return repositoryErr({code:"query_failed",message:"Persistence read failed.",correlationId:c})}}}
const mapOne=<T>(r:RepositoryResult<Row>,f:(x:Row)=>T,c?:string):RepositoryResult<T>=>{if(!r.ok)return r;try{return repositoryOk(f(r.value))}catch{return repositoryErr({code:"persistence_data_invalid",message:"Persisted data is malformed.",correlationId:c})}};
const mapMany=<T>(r:RepositoryResult<readonly Row[]>,f:(x:Row)=>T,c?:string):RepositoryResult<readonly T[]>=>{if(!r.ok)return r;try{return repositoryOk(r.value.map(f))}catch{return repositoryErr({code:"persistence_data_invalid",message:"Persisted data is malformed.",correlationId:c})}};
const BRANDS="id, code, name, slug, status, created_at, updated_at, version";
const USERS="id, auth_user_id, status, created_at, updated_at, version";
const MEMBERSHIPS="id, app_user_id, brand_id, status, valid_from, valid_until, created_at, updated_at, version";
const STUDENTS="id, brand_membership_id, app_user_id, brand_id, status, created_at, updated_at, version";
const PROFILES="id, app_user_id, status, created_at, updated_at, version";
const PERMISSIONS="id, code, description, status, created_at, updated_at, version";
const ROLES="id, code, name, assignment_scope, status, created_at, updated_at, version";
const ASSIGNMENTS="id, admin_profile_id, admin_role_id, assigned_by_admin_profile_id, valid_from, valid_until, status, created_at, updated_at, version";
const AUTH_SQL="select au.id as app_user_id, au.auth_user_id, au.status as app_user_status, au.created_at as app_user_created_at, au.updated_at as app_user_updated_at, au.version as app_user_version, ap.id as admin_profile_id, ap.status as admin_profile_status, ap.created_at as admin_profile_created_at, ap.updated_at as admin_profile_updated_at, ap.version as admin_profile_version, coalesce(array_agg(distinct ar.code) filter (where para.status='active' and para.valid_from <= now() and (para.valid_until is null or para.valid_until > now()) and ar.status='active'),array[]::text[]) as role_codes, coalesce(array_agg(distinct perm.code) filter (where para.status='active' and para.valid_from <= now() and (para.valid_until is null or para.valid_until > now()) and ar.status='active' and perm.status='active'),array[]::text[]) as permission_codes from app.app_users au join app.admin_profiles ap on ap.app_user_id=au.id left join app.platform_admin_role_assignments para on para.admin_profile_id=ap.id left join app.admin_roles ar on ar.id=para.admin_role_id left join app.admin_role_permissions arp on arp.admin_role_id=ar.id left join app.admin_permissions perm on perm.id=arp.admin_permission_id where au.auth_user_id=$1 group by au.id,ap.id";

export class SupabaseM1EducationalBrandReadRepository extends Base implements M1.M1EducationalBrandReadRepository{async findEducationalBrandById(i:{id:string;correlationId?:string}){return mapOne(await this.one({label:"m1.brand.by-id",text:`select ${BRANDS} from app.educational_brands where id=$1`,values:[i.id]},i.correlationId),brand,i.correlationId)}async findEducationalBrandByCode(i:{code:"medway"|"elite";correlationId?:string}){return mapOne(await this.one({label:"m1.brand.by-code",text:`select ${BRANDS} from app.educational_brands where code=$1`,values:[i.code]},i.correlationId),brand,i.correlationId)}}
export class SupabaseM1AppUserReadRepository extends Base implements M1.M1AppUserReadRepository{async findAppUserById(i:{id:string;correlationId?:string}){return mapOne(await this.one({label:"m1.user.by-id",text:`select ${USERS} from app.app_users where id=$1`,values:[i.id]},i.correlationId),user,i.correlationId)}async findAppUserByAuthUserId(i:{authUserId:string;correlationId?:string}){return mapOne(await this.one({label:"m1.user.by-auth",text:`select ${USERS} from app.app_users where auth_user_id=$1`,values:[i.authUserId]},i.correlationId),user,i.correlationId)}}
export class SupabaseM1BrandMembershipReadRepository extends Base implements M1.M1BrandMembershipReadRepository{async findBrandMembershipByUserId(i:{appUserId:string;brand:BrandScope;correlationId?:string}){return mapOne(await this.one({label:"m1.membership.by-user-brand",text:`select ${MEMBERSHIPS} from app.brand_memberships where app_user_id=$1 and brand_id=$2 order by (status='active') desc, created_at desc limit 1`,values:[i.appUserId,i.brand.brandId]},i.correlationId),membership,i.correlationId)}}
export class SupabaseM1StudentProfileReadRepository extends Base implements M1.M1StudentProfileReadRepository{async findStudentProfileById(i:{id:string;brand:BrandScope;correlationId?:string}){return mapOne(await this.one({label:"m1.student.by-id-brand",text:`select ${STUDENTS} from app.student_profiles where id=$1 and brand_id=$2`,values:[i.id,i.brand.brandId]},i.correlationId),student,i.correlationId)}async findStudentProfileByUserId(i:{appUserId:string;brand:BrandScope;correlationId?:string}){return mapOne(await this.one({label:"m1.student.by-user-brand",text:`select ${STUDENTS} from app.student_profiles where app_user_id=$1 and brand_id=$2`,values:[i.appUserId,i.brand.brandId]},i.correlationId),student,i.correlationId)}async listStudentProfilesByBrand(i:{brand:BrandScope;correlationId?:string}){return mapMany(await this.many({label:"m1.student.list-brand",text:`select ${STUDENTS} from app.student_profiles where brand_id=$1 order by created_at,id`,values:[i.brand.brandId]},i.correlationId),student,i.correlationId)}}
export class SupabaseM1AdminProfileReadRepository extends Base implements M1.M1AdminProfileReadRepository{async findAdminProfileById(i:{id:string;brand:BrandScope;correlationId?:string}){return mapOne(await this.one({label:"m1.admin-profile.by-id",text:`select ${PROFILES} from app.admin_profiles where id=$1`,values:[i.id]},i.correlationId),profile,i.correlationId)}async findAdminProfileByUserId(i:{appUserId:string;brand:BrandScope;correlationId?:string}){return mapOne(await this.one({label:"m1.admin-profile.by-user",text:`select ${PROFILES} from app.admin_profiles where app_user_id=$1`,values:[i.appUserId]},i.correlationId),profile,i.correlationId)}async resolveAdminAuthorizationByAuthUserId(i:{authUserId:string;brand:BrandScope;correlationId?:string}){return mapOne(await this.one({label:"m1.admin-authorization.by-auth",text:AUTH_SQL,values:[i.authUserId]},i.correlationId),authorization,i.correlationId)}async listAdminAuthorizationsByAuthUserId(i:{authUserId:string;correlationId?:string}){return mapMany(await this.many({label:"m1.admin-authorization.list-by-auth",text:AUTH_SQL,values:[i.authUserId]},i.correlationId),authorization,i.correlationId)}}
export class SupabaseM1AdminPermissionReadRepository extends Base implements M1.M1AdminPermissionReadRepository{async findAdminPermissionById(i:{id:string;correlationId?:string}){return mapOne(await this.one({label:"m1.permission.by-id",text:`select ${PERMISSIONS} from app.admin_permissions where id=$1`,values:[i.id]},i.correlationId),permission,i.correlationId)}async findAdminPermissionByCode(i:{code:string;correlationId?:string}){return mapOne(await this.one({label:"m1.permission.by-code",text:`select ${PERMISSIONS} from app.admin_permissions where code=$1`,values:[i.code]},i.correlationId),permission,i.correlationId)}}
export class SupabaseM1AdminRoleReadRepository extends Base implements M1.M1AdminRoleReadRepository{async findAdminRoleById(i:{id:string;brand:BrandScope;correlationId?:string}){return mapOne(await this.one({label:"m1.role.by-id",text:`select ${ROLES} from app.admin_roles where id=$1`,values:[i.id]},i.correlationId),role,i.correlationId)}async listAdminRolesByBrand(i:{brand:BrandScope;correlationId?:string}){return mapMany(await this.many({label:"m1.role.list",text:`select ${ROLES} from app.admin_roles order by code,id`,values:[]},i.correlationId),role,i.correlationId)}}
export class SupabaseM1AdminRolePermissionReadRepository extends Base implements M1.M1AdminRolePermissionReadRepository{async listAdminRolePermissions(i:{roleId:string;brand:BrandScope;correlationId?:string}){return mapMany(await this.many({label:"m1.role-permission.list",text:"select admin_role_id,admin_permission_id,created_at from app.admin_role_permissions where admin_role_id=$1 order by admin_permission_id",values:[i.roleId]},i.correlationId),rolePermission,i.correlationId)}}
export class SupabaseM1AdminRoleAssignmentReadRepository extends Base implements M1.M1AdminRoleAssignmentReadRepository{async listAdminRoleAssignmentsForProfile(i:{adminProfileId:string;brand:BrandScope;correlationId?:string}){return mapMany(await this.many({label:"m1.role-assignment.list",text:`select ${ASSIGNMENTS} from app.platform_admin_role_assignments where admin_profile_id=$1 order by valid_from,id`,values:[i.adminProfileId]},i.correlationId),assignment,i.correlationId)}}
