import type { BrandScope } from "../../../core/brand-scope";
import type { ReadQueryRequest, ReadQueryResult, ReadQueryTransport } from "../read-query-transport";
import { SupabaseM2AcademicLevelReadRepository, SupabaseM2AcademicModuleReadRepository, SupabaseM2BrandCourseReadRepository, SupabaseM2BrandInstructorReadRepository, SupabaseM2CourseInstructorReadRepository, SupabaseM2InstructorReadRepository } from "./m2-supabase-read-repositories";
export interface M2SupabaseReadRepositorySelfTestRunResult { readonly passed:boolean; readonly cases: readonly {readonly name:string;readonly passed:boolean}[]; }
const brand:BrandScope={brandId:"brand-medway" as BrandScope["brandId"],brandCode:"medway",brandDisplayName:"Medway",isActive:true};
const now="2026-01-01T00:00:00.000Z"; const moduleRow={id:"module-1",semester_id:"semester-1",module_code:"MSK2115",title:"MSK",sort_order:1,status:"active",created_at:now,updated_at:now}; const courseRow={id:"course-1",brand_id:"brand-medway",academic_module_id:null,course_code:"STANDALONE",title:"Standalone",course_scope:"standalone",status:"draft",created_at:now,updated_at:now};
class Fake implements ReadQueryTransport { readonly requests:ReadQueryRequest[]=[]; constructor(private readonly rows:Record<string,readonly Record<string,unknown>[]>,private readonly fail=false){} async query<Row extends Record<string,unknown>>(r:ReadQueryRequest):Promise<ReadQueryResult<Row>>{this.requests.push(r);if(this.fail)throw new Error("network");return{rows:(this.rows[r.label]??[]) as readonly Row[]}} }
const ok=(v:unknown,m:string)=>{if(!v)throw new Error(m)}; const select=(r:ReadQueryRequest)=>{ok(/^select\b/i.test(r.text)&&r.text.includes("app."),"not app SELECT");ok(!/\b(insert|update|delete|create|alter|drop|grant|revoke)\b/i.test(r.text),"unsafe SQL")};
export async function runM2SupabaseReadRepositorySelfTest():Promise<M2SupabaseReadRepositorySelfTestRunResult>{const cases:{name:string;passed:boolean}[]=[];const test=async(name:string,run:()=>Promise<void>|void)=>{try{await run();cases.push({name,passed:true})}catch{cases.push({name,passed:false})}};
await test("construction issues no query",()=>{const f=new Fake({});new SupabaseM2AcademicLevelReadRepository(f);new SupabaseM2InstructorReadRepository(f);ok(f.requests.length===0,"queried")});
await test("module code trims and binds",async()=>{const f=new Fake({"m2.academic-module.by-code":[moduleRow]});const r=await new SupabaseM2AcademicModuleReadRepository(f).findAcademicModuleByCode({moduleCode:" MSK2115 "});ok(r.ok,"missing");ok(f.requests[0]?.values[0]==="MSK2115","code")});
await test("malformed row is safe",async()=>{const f=new Fake({"m2.academic-module.by-id":[{...moduleRow,status:"bad"}]});const r=await new SupabaseM2AcademicModuleReadRepository(f).findAcademicModuleById({id:"module-1"});ok(!r.ok&&r.error.code==="persistence_data_invalid","mapping")});
await test("brand lists bind scope and preserve null module",async()=>{const f=new Fake({"m2.brand-course.list-brand":[courseRow],"m2.brand-instructor.list-brand":[],"m2.course-instructor.list-brand-course":[]});const c=await new SupabaseM2BrandCourseReadRepository(f).listBrandCourses({brand});await new SupabaseM2BrandInstructorReadRepository(f).listBrandInstructors({brand});await new SupabaseM2CourseInstructorReadRepository(f).listCourseInstructors({brand,courseId:"course-1"});ok(c.ok&&c.value[0]?.academicModuleId===null,"standalone");ok(f.requests.every(r=>r.values[0]===brand.brandId),"brand binding");f.requests.forEach(select)});
await test("cross brand and failures do not leak",async()=>{const none=await new SupabaseM2BrandCourseReadRepository(new Fake({})).findBrandCourseById({brand,courseId:"other"});const failed=await new SupabaseM2InstructorReadRepository(new Fake({},true)).listInstructors();ok(!none.ok&&none.error.code==="not_found"&&!none.error.message.includes("other"),"not found");ok(!failed.ok&&failed.error.code==="query_failed","failure")});
return{passed:cases.every(c=>c.passed),cases};}
if(process.argv[1]?.endsWith("m2-supabase-read-repositories.selftest.js")){runM2SupabaseReadRepositorySelfTest().then(r=>{if(!r.passed)process.exitCode=1;else console.log("m2 supabase read repository selftest passed")});}
