import { repositoryErr, repositoryOk, type RepositoryResult } from "../../../core/persistence";
import type * as M2 from "../../../core/repositories/m2-read-repositories";
import type { ReadQueryRequest, ReadQueryTransport } from "../read-query-transport";
import { requiredPersistenceTimestamp } from "./persistence-timestamp";
type Row = Readonly<Record<string, unknown>>;
const limit = " limit 200";
const str = (r: Row, k: string) => { const v = r[k]; if (typeof v !== "string" || !v) throw new Error(k); return v; };
const nullable = (r: Row, k: string) => { const v = r[k]; if (v == null) return null; if (typeof v !== "string") throw new Error(k); return v; };
const num = (r: Row, k: string) => { const v = r[k]; if (typeof v !== "number" || !Number.isInteger(v)) throw new Error(k); return v; };
const one = <T extends string>(r: Row, k: string, values: readonly T[]): T => { const v = str(r, k); if (!values.includes(v as T)) throw new Error(k); return v as T; };
const invalid = <T>(correlationId?: string): RepositoryResult<T> => repositoryErr({ code: "persistence_data_invalid", message: "Persisted data is malformed.", correlationId });
abstract class Base { constructor(protected readonly transport: ReadQueryTransport) {} protected async one(q: ReadQueryRequest, correlationId?: string): Promise<RepositoryResult<Row>> { try { const rows = (await this.transport.query<Row>(q)).rows; return rows[0] ? repositoryOk(rows[0]) : repositoryErr({ code: "not_found", message: "Requested record was not found.", correlationId }); } catch { return repositoryErr({ code: "query_failed", message: "Persistence read failed.", correlationId }); } } protected async many(q: ReadQueryRequest, correlationId?: string): Promise<RepositoryResult<readonly Row[]>> { try { return repositoryOk((await this.transport.query<Row>(q)).rows); } catch { return repositoryErr({ code: "query_failed", message: "Persistence read failed.", correlationId }); } } }
const mapOne = <T>(result: RepositoryResult<Row>, fn: (r: Row) => T, c?: string): RepositoryResult<T> => { if (!result.ok) return result; try { return repositoryOk(fn(result.value)); } catch { return invalid(c); } };
const mapMany = <T>(result: RepositoryResult<readonly Row[]>, fn: (r: Row) => T, c?: string): RepositoryResult<readonly T[]> => { if (!result.ok) return result; try { return repositoryOk(result.value.map(fn)); } catch { return invalid(c); } };
const level = (r: Row): M2.M2AcademicLevel => ({ id:str(r,"id"),levelNumber:num(r,"level_number"),displayName:str(r,"display_name"),sortOrder:num(r,"sort_order"),status:one(r,"status",["active","inactive"]),createdAt:requiredPersistenceTimestamp(r.created_at),updatedAt:requiredPersistenceTimestamp(r.updated_at) });
const semester = (r: Row): M2.M2AcademicSemester => ({ id:str(r,"id"),levelId:str(r,"level_id"),semesterNumber:num(r,"semester_number"),displayName:str(r,"display_name"),phase:one(r,"phase",["phase_i","phase_ii"]),sortOrder:num(r,"sort_order"),status:one(r,"status",["active","inactive"]),createdAt:requiredPersistenceTimestamp(r.created_at),updatedAt:requiredPersistenceTimestamp(r.updated_at) });
const academicModule = (r: Row): M2.M2AcademicModule => ({ id:str(r,"id"),semesterId:str(r,"semester_id"),moduleCode:str(r,"module_code"),title:str(r,"title"),sortOrder:num(r,"sort_order"),status:one(r,"status",["active","inactive"]),createdAt:requiredPersistenceTimestamp(r.created_at),updatedAt:requiredPersistenceTimestamp(r.updated_at) });
const instructor = (r: Row): M2.M2Instructor => ({ id:str(r,"id"),displayName:str(r,"display_name"),professionalTitle:nullable(r,"professional_title"),status:one(r,"status",["active","inactive"]),createdAt:requiredPersistenceTimestamp(r.created_at),updatedAt:requiredPersistenceTimestamp(r.updated_at) });
const brandInstructor = (r: Row): M2.M2BrandInstructor => ({ id:str(r,"id"),brandId:str(r,"brand_id"),instructorId:str(r,"instructor_id"),status:one(r,"status",["active","inactive"]),createdAt:requiredPersistenceTimestamp(r.created_at),updatedAt:requiredPersistenceTimestamp(r.updated_at) });
const course = (r: Row): M2.M2BrandCourse => ({ id:str(r,"id"),brandId:str(r,"brand_id"),academicModuleId:nullable(r,"academic_module_id"),courseCode:str(r,"course_code"),title:str(r,"title"),courseScope:one(r,"course_scope",["curriculum","standalone"]),status:one(r,"status",["draft","published","archived"]),createdAt:requiredPersistenceTimestamp(r.created_at),updatedAt:requiredPersistenceTimestamp(r.updated_at) });
const assignment = (r: Row): M2.M2CourseInstructor => ({ id:str(r,"id"),courseId:str(r,"course_id"),brandId:str(r,"brand_id"),instructorId:str(r,"instructor_id"),status:one(r,"status",["active","inactive"]),createdAt:requiredPersistenceTimestamp(r.created_at),updatedAt:requiredPersistenceTimestamp(r.updated_at) });
const levels="id, level_number, display_name, sort_order, status, created_at, updated_at", semesters="id, level_id, semester_number, display_name, phase, sort_order, status, created_at, updated_at", modules="id, semester_id, module_code, title, sort_order, status, created_at, updated_at", instructors="id, display_name, professional_title, status, created_at, updated_at", bi="id, brand_id, instructor_id, status, created_at, updated_at", courses="id, brand_id, academic_module_id, course_code, title, course_scope, status, created_at, updated_at", ci="id, course_id, brand_id, instructor_id, status, created_at, updated_at";
export class SupabaseM2AcademicLevelReadRepository extends Base implements M2.M2AcademicLevelReadRepository { async findAcademicLevelById(i:{id:string;correlationId?:string}) { return mapOne(await this.one({label:"m2.academic-level.by-id",text:`select ${levels} from app.academic_levels where id = $1 limit 1`,values:[i.id]},i.correlationId),level,i.correlationId); } async listAcademicLevels(i:{correlationId?:string}={}) { return mapMany(await this.many({label:"m2.academic-level.list",text:`select ${levels} from app.academic_levels order by sort_order asc, level_number asc, id asc${limit}`,values:[]},i.correlationId),level,i.correlationId); } }
export class SupabaseM2AcademicSemesterReadRepository extends Base implements M2.M2AcademicSemesterReadRepository { async findAcademicSemesterById(i:{id:string;correlationId?:string}) { return mapOne(await this.one({label:"m2.academic-semester.by-id",text:`select ${semesters} from app.academic_semesters where id = $1 limit 1`,values:[i.id]},i.correlationId),semester,i.correlationId); } async listAcademicSemesters(i:{correlationId?:string}={}) { return mapMany(await this.many({label:"m2.academic-semester.list",text:`select ${semesters} from app.academic_semesters order by sort_order asc, semester_number asc, id asc${limit}`,values:[]},i.correlationId),semester,i.correlationId); } async listAcademicSemestersByLevelId(i:{levelId:string;correlationId?:string}) { return mapMany(await this.many({label:"m2.academic-semester.list-level",text:`select ${semesters} from app.academic_semesters where level_id = $1 order by sort_order asc, semester_number asc, id asc${limit}`,values:[i.levelId]},i.correlationId),semester,i.correlationId); } }
export class SupabaseM2AcademicModuleReadRepository extends Base implements M2.M2AcademicModuleReadRepository { async findAcademicModuleById(i:{id:string;correlationId?:string}) { return mapOne(await this.one({label:"m2.academic-module.by-id",text:`select ${modules} from app.academic_modules where id = $1 limit 1`,values:[i.id]},i.correlationId),academicModule,i.correlationId); } async findAcademicModuleByCode(i:{moduleCode:string;correlationId?:string}) { const code=i.moduleCode.trim(); if(!code) return repositoryErr({code:"invalid_input",message:"Module code is required.",correlationId:i.correlationId}); return mapOne(await this.one({label:"m2.academic-module.by-code",text:`select ${modules} from app.academic_modules where module_code = $1 limit 1`,values:[code]},i.correlationId),academicModule,i.correlationId); } async listAcademicModules(i:{correlationId?:string}={}) { return mapMany(await this.many({label:"m2.academic-module.list",text:`select ${modules} from app.academic_modules order by sort_order asc, module_code asc, id asc${limit}`,values:[]},i.correlationId),academicModule,i.correlationId); } async listAcademicModulesBySemesterId(i:{semesterId:string;correlationId?:string}) { return mapMany(await this.many({label:"m2.academic-module.list-semester",text:`select ${modules} from app.academic_modules where semester_id = $1 order by sort_order asc, module_code asc, id asc${limit}`,values:[i.semesterId]},i.correlationId),academicModule,i.correlationId); } }
export class SupabaseM2InstructorReadRepository extends Base implements M2.M2InstructorReadRepository { async findInstructorById(i:{id:string;correlationId?:string}) { return mapOne(await this.one({label:"m2.instructor.by-id",text:`select ${instructors} from app.instructors where id = $1 limit 1`,values:[i.id]},i.correlationId),instructor,i.correlationId); } async listInstructors(i:{correlationId?:string}={}) { return mapMany(await this.many({label:"m2.instructor.list",text:`select ${instructors} from app.instructors order by display_name asc, id asc${limit}`,values:[]},i.correlationId),instructor,i.correlationId); } }
export class SupabaseM2BrandInstructorReadRepository extends Base implements M2.M2BrandInstructorReadRepository { async listBrandInstructors(i:any) { return mapMany(await this.many({label:"m2.brand-instructor.list-brand",text:`select ${bi} from app.brand_instructors where brand_id = $1 order by instructor_id asc, id asc${limit}`,values:[i.brand.brandId]},i.correlationId),brandInstructor,i.correlationId); } async findBrandInstructor(i:any) { return mapOne(await this.one({label:"m2.brand-instructor.by-brand-instructor",text:`select ${bi} from app.brand_instructors where brand_id = $1 and instructor_id = $2 limit 1`,values:[i.brand.brandId,i.instructorId]},i.correlationId),brandInstructor,i.correlationId); } async listInstructorBrands(i:any) { return mapMany(await this.many({label:"m2.brand-instructor.list-instructor",text:`select ${bi} from app.brand_instructors where instructor_id = $1 order by brand_id asc, id asc${limit}`,values:[i.instructorId]},i.correlationId),brandInstructor,i.correlationId); } }
export class SupabaseM2BrandCourseReadRepository extends Base implements M2.M2BrandCourseReadRepository { private async manyBrand(label:string, where:string, values:string[], c?:string){return mapMany(await this.many({label,text:`select ${courses} from app.brand_courses where ${where} order by course_code asc, title asc, id asc${limit}`,values},c),course,c);} async findBrandCourseById(i:any){return mapOne(await this.one({label:"m2.brand-course.by-brand-id",text:`select ${courses} from app.brand_courses where brand_id = $1 and id = $2 limit 1`,values:[i.brand.brandId,i.courseId]},i.correlationId),course,i.correlationId)} async findBrandCourseByCode(i:any){return mapOne(await this.one({label:"m2.brand-course.by-brand-code",text:`select ${courses} from app.brand_courses where brand_id = $1 and course_code = $2 limit 1`,values:[i.brand.brandId,i.courseCode]},i.correlationId),course,i.correlationId)} async listBrandCourses(i:any){return this.manyBrand("m2.brand-course.list-brand","brand_id = $1",[i.brand.brandId],i.correlationId)} async listBrandCoursesByAcademicModule(i:any){return this.manyBrand("m2.brand-course.list-brand-module","brand_id = $1 and academic_module_id = $2",[i.brand.brandId,i.academicModuleId],i.correlationId)} async listStandaloneBrandCourses(i:any){return this.manyBrand("m2.brand-course.list-brand-standalone","brand_id = $1 and course_scope = 'standalone' and academic_module_id is null",[i.brand.brandId],i.correlationId)} }
export class SupabaseM2CourseInstructorReadRepository extends Base implements M2.M2CourseInstructorReadRepository { async listCourseInstructors(i:any){return mapMany(await this.many({label:"m2.course-instructor.list-brand-course",text:`select ${ci} from app.course_instructors where brand_id = $1 and course_id = $2 order by instructor_id asc, id asc${limit}`,values:[i.brand.brandId,i.courseId]},i.correlationId),assignment,i.correlationId)} async listInstructorCourseAssignments(i:any){return mapMany(await this.many({label:"m2.course-instructor.list-brand-instructor",text:`select ${ci} from app.course_instructors where brand_id = $1 and instructor_id = $2 order by course_id asc, id asc${limit}`,values:[i.brand.brandId,i.instructorId]},i.correlationId),assignment,i.correlationId)} }
