import { repositoryErr, repositoryOk, type RepositoryResult } from "../../../core/persistence";
import type * as M2 from "../../../core/repositories/m2-read-repositories";
import type { ReadQueryRequest, ReadQueryTransport } from "../read-query-transport";
import { requiredPersistenceTimestamp } from "./persistence-timestamp";

type Row = Readonly<Record<string, unknown>>;
const LIMIT = " limit 500";
const str = (row: Row, key: string): string => { const value = row[key]; if (typeof value !== "string" || !value) throw new Error(key); return value; };
const nullable = (row: Row, key: string): string | null => { const value = row[key]; if (value == null) return null; if (typeof value !== "string") throw new Error(key); return value; };
const integer = (row: Row, key: string): number => { const value = row[key]; const parsed = typeof value === "string" ? Number(value) : value; if (typeof parsed !== "number" || !Number.isSafeInteger(parsed)) throw new Error(key); return parsed; };
const one = <T extends string>(row: Row, key: string, values: readonly T[]): T => { const value = str(row, key); if (!values.includes(value as T)) throw new Error(key); return value as T; };
const malformed = <T>(correlationId?: string): RepositoryResult<T> => repositoryErr({ code: "persistence_data_invalid", message: "Persisted data is malformed.", correlationId });

abstract class Base {
  constructor(protected readonly transport: ReadQueryTransport) {}
  protected async one(query: ReadQueryRequest, correlationId?: string): Promise<RepositoryResult<Row>> { try { const row = (await this.transport.query<Row>(query)).rows[0]; return row ? repositoryOk(row) : repositoryErr({ code: "not_found", message: "Requested record was not found.", correlationId }); } catch { return repositoryErr({ code: "query_failed", message: "Persistence read failed.", correlationId }); } }
  protected async many(query: ReadQueryRequest, correlationId?: string): Promise<RepositoryResult<readonly Row[]>> { try { return repositoryOk((await this.transport.query<Row>(query)).rows); } catch { return repositoryErr({ code: "query_failed", message: "Persistence read failed.", correlationId }); } }
}
const mapOne = <T>(result: RepositoryResult<Row>, mapper: (row: Row) => T, correlationId?: string): RepositoryResult<T> => { if (!result.ok) return result; try { return repositoryOk(mapper(result.value)); } catch { return malformed(correlationId); } };
const mapMany = <T>(result: RepositoryResult<readonly Row[]>, mapper: (row: Row) => T, correlationId?: string): RepositoryResult<readonly T[]> => { if (!result.ok) return result; try { return repositoryOk(result.value.map(mapper)); } catch { return malformed(correlationId); } };
const versioned = (row: Row) => ({ id: str(row, "id"), createdAt: requiredPersistenceTimestamp(row.created_at), updatedAt: requiredPersistenceTimestamp(row.updated_at), version: integer(row, "version") });
const level = (row: Row): M2.M2AcademicLevel => ({ ...versioned(row), levelNumber: integer(row, "level_number"), displayTitle: str(row, "display_title"), sortOrder: integer(row, "sort_order"), status: one(row, "status", ["active", "retired"]) });
const semester = (row: Row): M2.M2AcademicSemester => ({ ...versioned(row), academicLevelId: str(row, "academic_level_id"), semesterNumber: integer(row, "semester_number"), displayTitle: str(row, "display_title"), sortOrder: integer(row, "sort_order"), status: one(row, "status", ["active", "retired"]) });
const moduleRow = (row: Row): M2.M2AcademicModule => ({ ...versioned(row), academicSemesterId: str(row, "academic_semester_id"), code: str(row, "code"), normalizedCode: str(row, "normalized_code"), sourceDisplayLabel: str(row, "source_display_label"), sortOrder: integer(row, "sort_order"), reviewStatus: one(row, "review_status", ["unreviewed", "approved", "blocked", "retired"]) });
const alias = (row: Row): M2.M2AcademicModuleAlias => ({ ...versioned(row), academicModuleId: str(row, "academic_module_id"), aliasValue: str(row, "alias_value"), normalizedAlias: str(row, "normalized_alias"), status: one(row, "status", ["active", "retired"]) });
const instructor = (row: Row): M2.M2Instructor => { const code=str(row,"code"); return { ...versioned(row), code, instructorCode:code, displayName:str(row,"display_name"), status:one(row,"status",["active","inactive","archived"]) }; };
const brandAssignment = (row: Row): M2.M2InstructorBrandAssignment => ({ ...versioned(row), brandId: str(row, "brand_id"), instructorId: str(row, "instructor_id"), status: one(row, "status", ["active", "inactive"]) });
const course = (row: Row): M2.M2BrandCourse => ({ ...versioned(row), brandId: str(row, "brand_id"), academicModuleId: nullable(row, "academic_module_id"), code: str(row, "code"), title: str(row, "title"), classification: one(row, "classification", ["academic_module_offering", "standalone"]), status: one(row, "status", ["draft", "published", "archived"]) });
const courseAssignment = (row: Row): M2.M2CourseInstructorAssignment => ({ ...versioned(row), courseId: str(row, "course_id"), brandId: str(row, "brand_id"), instructorBrandAssignmentId: str(row, "instructor_brand_assignment_id"), instructorId: str(row, "instructor_id"), status: one(row, "status", ["active", "inactive"]) });

const LEVELS = "id, level_number, display_title, sort_order, status, created_at, updated_at, version";
const SEMESTERS = "id, academic_level_id, semester_number, display_title, sort_order, status, created_at, updated_at, version";
const MODULES = "id, academic_semester_id, code, normalized_code, source_display_label, sort_order, review_status, created_at, updated_at, version";
const ALIASES = "id, academic_module_id, alias_value, normalized_alias, status, created_at, updated_at, version";
const INSTRUCTORS = "id, code, display_name, status, created_at, updated_at, version";
const BRAND_ASSIGNMENTS = "id, brand_id, instructor_id, status, created_at, updated_at, version";
const COURSES = "id, brand_id, academic_module_id, code, title, classification, status, created_at, updated_at, version";
const COURSE_ASSIGNMENTS = "cia.id, cia.course_id, cia.brand_id, cia.instructor_brand_assignment_id, iba.instructor_id, cia.status, cia.created_at, cia.updated_at, cia.version";
const CHAPTERS = "id, brand_course_id, title, sort_order, status, created_at, updated_at, version";
const LESSONS = "id, brand_course_id, course_chapter_id, title, sort_order, status, created_at, updated_at, version";
const RESOURCES = "id, brand_course_id, course_lesson_id, resource_kind, title, sort_order, status, created_at, updated_at, version";
const chapter = (row: Row): M2.M2bChapter => ({ ...versioned(row), brandCourseId: str(row, "brand_course_id"), title: str(row, "title"), sortOrder: integer(row, "sort_order"), status: one(row, "status", ["draft", "published", "archived"]) });
const lesson = (row: Row): M2.M2bLesson => ({ ...versioned(row), brandCourseId: str(row, "brand_course_id"), courseChapterId: str(row, "course_chapter_id"), title: str(row, "title"), sortOrder: integer(row, "sort_order"), status: one(row, "status", ["draft", "published", "archived"]) });
const resource = (row: Row): M2.M2bResource => ({ ...versioned(row), brandCourseId: str(row, "brand_course_id"), courseLessonId: str(row, "course_lesson_id"), resourceKind: one(row, "resource_kind", ["video", "document", "quiz", "link", "file"]), title: str(row, "title"), sortOrder: integer(row, "sort_order"), status: one(row, "status", ["draft", "published", "archived"]) });

export class SupabaseM2AcademicLevelReadRepository extends Base implements M2.M2AcademicLevelReadRepository { async findAcademicLevelById(i:{id:string;correlationId?:string}) { return mapOne(await this.one({ label:"m2.academic-level.by-id", text:`select ${LEVELS} from app.academic_levels where id = $1`, values:[i.id] },i.correlationId),level,i.correlationId); } async listAcademicLevels(i:{correlationId?:string}={}) { return mapMany(await this.many({ label:"m2.academic-level.list", text:`select ${LEVELS} from app.academic_levels order by sort_order, level_number, id${LIMIT}`, values:[] },i.correlationId),level,i.correlationId); } }
export class SupabaseM2AcademicSemesterReadRepository extends Base implements M2.M2AcademicSemesterReadRepository { async findAcademicSemesterById(i:{id:string;correlationId?:string}) { return mapOne(await this.one({label:"m2.academic-semester.by-id",text:`select ${SEMESTERS} from app.academic_semesters where id = $1`,values:[i.id]},i.correlationId),semester,i.correlationId); } async listAcademicSemesters(i:{correlationId?:string}={}) { return mapMany(await this.many({label:"m2.academic-semester.list",text:`select ${SEMESTERS} from app.academic_semesters order by sort_order, semester_number, id${LIMIT}`,values:[]},i.correlationId),semester,i.correlationId); } async listAcademicSemestersByLevelId(i:{levelId:string;correlationId?:string}) { return mapMany(await this.many({label:"m2.academic-semester.list-level",text:`select ${SEMESTERS} from app.academic_semesters where academic_level_id = $1 order by sort_order, semester_number, id${LIMIT}`,values:[i.levelId]},i.correlationId),semester,i.correlationId); } }
export class SupabaseM2AcademicModuleReadRepository extends Base implements M2.M2AcademicModuleReadRepository { async findAcademicModuleById(i:{id:string;correlationId?:string}) { return mapOne(await this.one({label:"m2.academic-module.by-id",text:`select ${MODULES} from app.academic_modules where id = $1`,values:[i.id]},i.correlationId),moduleRow,i.correlationId); } async findAcademicModuleByCode(i:{moduleCode:string;correlationId?:string}) { const code=i.moduleCode.trim().toUpperCase(); if(!code)return repositoryErr({code:"invalid_input",message:"Module code is required.",correlationId:i.correlationId}); return mapOne(await this.one({label:"m2.academic-module.by-code",text:`select ${MODULES} from app.academic_modules where normalized_code = $1`,values:[code]},i.correlationId),moduleRow,i.correlationId); } async listAcademicModules(i:{correlationId?:string}={}) { return mapMany(await this.many({label:"m2.academic-module.list",text:`select ${MODULES} from app.academic_modules order by sort_order, normalized_code, id${LIMIT}`,values:[]},i.correlationId),moduleRow,i.correlationId); } async listAcademicModulesBySemesterId(i:{semesterId:string;correlationId?:string}) { return mapMany(await this.many({label:"m2.academic-module.list-semester",text:`select ${MODULES} from app.academic_modules where academic_semester_id = $1 order by sort_order, normalized_code, id${LIMIT}`,values:[i.semesterId]},i.correlationId),moduleRow,i.correlationId); } }
export class SupabaseM2AcademicModuleAliasReadRepository extends Base implements M2.M2AcademicModuleAliasReadRepository { async findAcademicModuleAlias(i:({normalizedAlias:string}|{normalizedComparisonValue:string})&{correlationId?:string}) { const value=("normalizedAlias" in i?i.normalizedAlias:i.normalizedComparisonValue).trim().toUpperCase(); if(!value)return repositoryErr({code:"invalid_input",message:"Module alias is required.",correlationId:i.correlationId}); return mapOne(await this.one({label:"m2.academic-module-alias.by-normalized-value",text:`select ${ALIASES} from app.academic_module_aliases where normalized_alias = $1 and status = 'active'`,values:[value]},i.correlationId),alias,i.correlationId); } }
export class SupabaseM2InstructorReadRepository extends Base implements M2.M2InstructorReadRepository { async findInstructorById(i:{id:string;correlationId?:string}) { return mapOne(await this.one({label:"m2.instructor.by-id",text:`select ${INSTRUCTORS} from app.instructors where id = $1`,values:[i.id]},i.correlationId),instructor,i.correlationId); } async findInstructorByCode(i:{instructorCode:string;correlationId?:string}) { const code=i.instructorCode.trim(); if(!code)return repositoryErr({code:"invalid_input",message:"Instructor code is required.",correlationId:i.correlationId}); return mapOne(await this.one({label:"m2.instructor.by-code",text:`select ${INSTRUCTORS} from app.instructors where code = $1`,values:[code]},i.correlationId),instructor,i.correlationId); } async listInstructors(i:{correlationId?:string}={}) { return mapMany(await this.many({label:"m2.instructor.list",text:`select ${INSTRUCTORS} from app.instructors order by display_name, code, id${LIMIT}`,values:[]},i.correlationId),instructor,i.correlationId); } }
export class SupabaseM2InstructorBrandAssignmentReadRepository extends Base implements M2.M2InstructorBrandAssignmentReadRepository { async listBrandAssignments(i:{brand:{brandId:string};correlationId?:string}) { return mapMany(await this.many({label:"m2.instructor-brand-assignment.list-brand",text:`select ${BRAND_ASSIGNMENTS} from app.instructor_brand_assignments where brand_id = $1 order by instructor_id, id${LIMIT}`,values:[i.brand.brandId]},i.correlationId),brandAssignment,i.correlationId); } async listBrandInstructors(i:{brand:{brandId:string};correlationId?:string}) { return this.listBrandAssignments(i); } async findBrandAssignment(i:{brand:{brandId:string};instructorId:string;correlationId?:string}) { return mapOne(await this.one({label:"m2.instructor-brand-assignment.by-brand-instructor",text:`select ${BRAND_ASSIGNMENTS} from app.instructor_brand_assignments where brand_id = $1 and instructor_id = $2`,values:[i.brand.brandId,i.instructorId]},i.correlationId),brandAssignment,i.correlationId); } async findBrandInstructor(i:{brand:{brandId:string};instructorId:string;correlationId?:string}) { return this.findBrandAssignment(i); } async listInstructorBrands(i:{instructorId:string;correlationId?:string}) { return mapMany(await this.many({label:"m2.instructor-brand-assignment.list-instructor",text:`select ${BRAND_ASSIGNMENTS} from app.instructor_brand_assignments where instructor_id = $1 order by brand_id, id${LIMIT}`,values:[i.instructorId]},i.correlationId),brandAssignment,i.correlationId); } }
export class SupabaseM2BrandCourseReadRepository extends Base implements M2.M2BrandCourseReadRepository { private async list(label:string,where:string,values:readonly string[],correlationId?:string){return mapMany(await this.many({label,text:`select ${COURSES} from app.brand_courses where ${where} order by code, title, id${LIMIT}`,values},correlationId),course,correlationId);} async findBrandCourseById(i:{brand:{brandId:string};courseId:string;correlationId?:string}){return mapOne(await this.one({label:"m2.brand-course.by-brand-id",text:`select ${COURSES} from app.brand_courses where brand_id = $1 and id = $2`,values:[i.brand.brandId,i.courseId]},i.correlationId),course,i.correlationId)} async findBrandCourseByCode(i:{brand:{brandId:string};courseCode:string;correlationId?:string}){return mapOne(await this.one({label:"m2.brand-course.by-brand-code",text:`select ${COURSES} from app.brand_courses where brand_id = $1 and code = $2`,values:[i.brand.brandId,i.courseCode]},i.correlationId),course,i.correlationId)} async listBrandCourses(i:{brand:{brandId:string};correlationId?:string}){return this.list("m2.brand-course.list-brand","brand_id = $1",[i.brand.brandId],i.correlationId)} async listBrandCoursesByAcademicModule(i:{brand:{brandId:string};academicModuleId:string;correlationId?:string}){return this.list("m2.brand-course.list-brand-module","brand_id = $1 and academic_module_id = $2",[i.brand.brandId,i.academicModuleId],i.correlationId)} async listStandaloneBrandCourses(i:{brand:{brandId:string};correlationId?:string}){return this.list("m2.brand-course.list-brand-standalone","brand_id = $1 and classification = 'standalone' and academic_module_id is null",[i.brand.brandId],i.correlationId)} }
export class SupabaseM2CourseInstructorAssignmentReadRepository extends Base implements M2.M2CourseInstructorAssignmentReadRepository { async listCourseInstructors(i:{brand:{brandId:string};courseId:string;correlationId?:string}){return mapMany(await this.many({label:"m2.course-instructor-assignment.list-brand-course",text:`select ${COURSE_ASSIGNMENTS} from app.course_instructor_assignments cia join app.instructor_brand_assignments iba on iba.id = cia.instructor_brand_assignment_id and iba.brand_id = cia.brand_id where cia.brand_id = $1 and cia.course_id = $2 order by iba.instructor_id, cia.id${LIMIT}`,values:[i.brand.brandId,i.courseId]},i.correlationId),courseAssignment,i.correlationId)} async listInstructorCourseAssignments(i:{brand:{brandId:string};instructorId:string;correlationId?:string}){return mapMany(await this.many({label:"m2.course-instructor-assignment.list-brand-instructor",text:`select ${COURSE_ASSIGNMENTS} from app.course_instructor_assignments cia join app.instructor_brand_assignments iba on iba.id = cia.instructor_brand_assignment_id and iba.brand_id = cia.brand_id where cia.brand_id = $1 and iba.instructor_id = $2 order by cia.course_id, cia.id${LIMIT}`,values:[i.brand.brandId,i.instructorId]},i.correlationId),courseAssignment,i.correlationId)} }
export class SupabaseM2CourseDeliveryReadRepository extends Base implements M2.M2bCourseDeliveryReadRepository {
  async listChapters(i:{brand:{brandId:string};courseId:string;correlationId?:string}) { return mapMany(await this.many({label:"m2b.chapters.list",text:`select ${CHAPTERS} from app.course_chapters where brand_id = $1 and brand_course_id = $2 order by sort_order, id${LIMIT}`,values:[i.brand.brandId,i.courseId]},i.correlationId),chapter,i.correlationId); }
  async listLessons(i:{brand:{brandId:string};courseId:string;correlationId?:string}) { return mapMany(await this.many({label:"m2b.lessons.list",text:`select ${LESSONS} from app.course_lessons where brand_id = $1 and brand_course_id = $2 order by sort_order, id${LIMIT}`,values:[i.brand.brandId,i.courseId]},i.correlationId),lesson,i.correlationId); }
  async listResources(i:{brand:{brandId:string};courseId:string;correlationId?:string}) { return mapMany(await this.many({label:"m2b.resources.list",text:`select ${RESOURCES} from app.lesson_resources where brand_id = $1 and brand_course_id = $2 order by sort_order, id${LIMIT}`,values:[i.brand.brandId,i.courseId]},i.correlationId),resource,i.correlationId); }
}

// Compatibility exports for existing composition imports. The implementations use canonical tables only.
export { SupabaseM2InstructorBrandAssignmentReadRepository as SupabaseM2BrandInstructorReadRepository };
export { SupabaseM2CourseInstructorAssignmentReadRepository as SupabaseM2CourseInstructorReadRepository };
