-- Migration 000: non-business private application foundation.
-- This migration deliberately creates no application tables, rows, RLS policies,
-- grants, roles, brand data, Auth identities, or seed data.

create schema if not exists app;

comment on schema app is
  'Private backend-owned application schema. It is not an exposed Data API schema.';

-- UUIDs are generated by the database, never accepted as client authority. A
-- supported UUID generator must be available before later business migrations run.
do $$
begin
  if to_regprocedure('pg_catalog.gen_random_uuid()') is null
     and to_regprocedure('extensions.gen_random_uuid()') is null then
    raise exception using
      errcode = '55000',
      message = 'Migration 000 requires a database UUID generation capability.';
  end if;
end;
$$;

-- Contract for later versioned application tables only:
--   * updated_at is server-authored at statement time on every update;
--   * version is a non-null integer owned by the database and increases by one;
--   * target tables must provide updated_at and version columns.
-- The function is SECURITY INVOKER and has no dynamic SQL or caller-controlled
-- search path. Later migrations attach it explicitly to their own tables.
create function app.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog, app
as $$
begin
  new.updated_at := statement_timestamp();
  new.version := old.version + 1;
  return new;
end;
$$;

comment on function app.set_updated_at() is
  'Private UPDATE trigger utility for later versioned app tables; server stamps updated_at and increments version.';

-- app is private to trusted backend database roles. Migration 000 makes no
-- grants; later migrations must add narrowly reviewed privileges if required.
revoke all on schema app from public;
revoke all on schema app from anon;
revoke all on schema app from authenticated;

-- PostgreSQL grants EXECUTE to PUBLIC for new functions by default. Remove it
-- explicitly, and do not make this private trigger utility a Data API surface.
revoke all on function app.set_updated_at() from public;
revoke all on function app.set_updated_at() from anon;
revoke all on function app.set_updated_at() from authenticated;
