type ApiDocsTemplateOptions = Readonly<{
  supabaseUrl: string;
  supabasePublishableKey: string;
}>;

/**
 * Standalone operational API console. It is generated from /openapi.json, but
 * it intentionally does not show generated payloads or synthetic path values.
 */
export function createApiDocsHtml(options: ApiDocsTemplateOptions): string {
  const configJson = JSON.stringify({
    supabaseUrl: options.supabaseUrl,
    supabasePublishableKey: options.supabasePublishableKey,
  }).replace(/</g, '\\u003c');

  return String.raw`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>BUC E-Learning API Console</title>
  <style>
    :root{--ink:#0b172a;--ink-soft:#30435f;--muted:#6c7a8f;--line:#dfe7e3;--line-strong:#cfdcd5;--surface:#fff;--surface-soft:#f7fbf8;--surface-muted:#eef5f1;--green:#159a54;--green-dark:#08743b;--green-soft:#eaf8ef;--green-line:#b9e5ca;--blue:#226ec8;--blue-soft:#edf5ff;--amber:#a8600e;--amber-soft:#fff6e8;--red:#c84242;--red-soft:#fff0f0;--code:#101820;--code-line:#25333f;--code-text:#d9e8ef;--radius:8px;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:var(--ink);background:#f5f8f6}
    *{box-sizing:border-box}html,body{min-height:100%;margin:0}button,input,select,textarea{font:inherit}button{cursor:pointer}button:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible{outline:3px solid rgba(21,154,84,.25);outline-offset:2px}.hidden{display:none!important}
    .shell{display:grid;grid-template-columns:360px minmax(0,1fr);min-height:100vh}.sidebar{min-height:0;border-right:1px solid var(--line);background:#fff;display:flex;flex-direction:column}.brand{height:72px;display:flex;align-items:center;gap:12px;padding:0 22px;border-bottom:1px solid var(--line)}.brand-mark{width:34px;height:34px;display:grid;place-items:center;border-radius:9px;background:var(--green);color:#fff;font-weight:900}.brand h1{margin:0;font-size:18px;letter-spacing:-.035em}.brand p{margin:3px 0 0;color:var(--muted);font-size:12px}.search{padding:16px 18px;border-bottom:1px solid var(--line)}.search input{width:100%;height:40px;border:1px solid var(--line-strong);border-radius:8px;padding:0 12px;color:var(--ink);background:#fff}.endpoint-list{min-height:0;overflow:auto;padding:8px 12px 18px}.group-title{margin:16px 6px 7px;color:#52677e;font-size:11px;font-weight:850;letter-spacing:.04em;text-transform:uppercase}.endpoint{width:100%;display:grid;grid-template-columns:56px minmax(0,1fr);gap:9px;align-items:center;margin:0 0 4px;padding:9px 10px;border:1px solid transparent;border-radius:8px;background:transparent;text-align:left;color:var(--ink)}.endpoint:hover{background:#f6faf8}.endpoint[aria-current="true"]{border-color:var(--green-line);background:var(--green-soft)}.method{display:inline-flex;align-items:center;justify-content:center;height:24px;border-radius:6px;font-size:10px;font-weight:900;letter-spacing:.03em}.get{background:var(--blue-soft);color:var(--blue)}.post{background:var(--green-soft);color:var(--green-dark)}.put,.patch{background:var(--amber-soft);color:var(--amber)}.delete{background:var(--red-soft);color:var(--red)}.endpoint-path{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:12px;font-weight:800}.endpoint-summary{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;margin-top:2px;color:var(--muted);font-size:11px}
    .main{min-width:0;display:flex;flex-direction:column}.topbar{position:sticky;top:0;z-index:3;background:#fff;border-bottom:1px solid var(--line);padding:14px 24px}.auth-grid{display:grid;grid-template-columns:170px minmax(190px,1fr) minmax(210px,1fr) minmax(180px,1fr) minmax(220px,1fr) auto auto;gap:9px;align-items:end}.field label{display:block;margin:0 0 5px;color:#40566e;font-size:11px;font-weight:850}.field input,.field select,.field textarea{width:100%;border:1px solid var(--line-strong);border-radius:8px;background:#fff;color:var(--ink);font-size:12px}.field input,.field select{height:38px;padding:0 10px}.field textarea{min-height:126px;padding:10px;resize:vertical;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;line-height:1.5}.button{height:38px;display:inline-flex;align-items:center;justify-content:center;gap:7px;border:1px solid var(--line-strong);border-radius:8px;background:#fff;color:var(--ink-soft);font-size:12px;font-weight:850;white-space:nowrap}.button.primary{border-color:var(--green);background:var(--green);color:#fff}.button.primary:hover{background:var(--green-dark)}.button.danger{border-color:#f0caca;color:var(--red);background:#fff}.auth-status{margin-top:9px;color:var(--muted);font-size:12px}.auth-status.ok{color:var(--green-dark)}.auth-status.error{color:var(--red)}
    .workspace{display:grid;grid-template-columns:minmax(0,1fr) minmax(420px,.82fr);gap:18px;padding:20px 24px 28px;min-height:0}.panel{border:1px solid var(--line);border-radius:10px;background:#fff;box-shadow:0 10px 26px rgba(10,23,51,.04)}.panel-head{display:flex;align-items:flex-start;justify-content:space-between;gap:14px;padding:16px 17px;border-bottom:1px solid var(--line)}.route{min-width:0}.route-line{display:flex;align-items:center;gap:10px;min-width:0}.route h2{margin:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:21px;letter-spacing:-.04em}.route p{margin:7px 0 0;color:var(--muted);font-size:12.5px;line-height:1.45}.panel-body{padding:16px 17px}.section-title{margin:0 0 11px;font-size:13px;color:#263d55}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.wide{grid-column:1/-1}.empty-note{margin:0;padding:13px;border:1px dashed var(--line-strong);border-radius:8px;color:var(--muted);background:#fbfdfc;font-size:12px}.muted{color:var(--muted)}.request-actions{display:flex;align-items:center;gap:9px;margin-top:15px}.request-url{overflow:auto;margin-top:12px;padding:10px;border:1px solid var(--line);border-radius:8px;background:#f8fbf9;color:#334861;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:11.5px;white-space:nowrap}.write-note{margin:10px 0 0;color:var(--amber);font-size:11.5px;font-weight:750}.response-meta{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.pill{display:inline-flex;align-items:center;min-height:24px;padding:0 8px;border-radius:999px;background:#f0f4f2;color:#4f6278;font-size:11px;font-weight:850}.pill.ok{background:var(--green-soft);color:var(--green-dark)}.pill.error{background:var(--red-soft);color:var(--red)}.code{overflow:hidden;border:1px solid var(--code-line);border-radius:9px;background:var(--code)}.code pre{overflow:auto;min-height:360px;max-height:calc(100vh - 290px);margin:0;padding:14px;color:var(--code-text);font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:12px;line-height:1.55;white-space:pre-wrap}.toast{position:fixed;right:22px;bottom:20px;z-index:10;max-width:380px;padding:12px 14px;border:1px solid var(--green-line);border-radius:8px;background:#fff;color:#2e4b3a;box-shadow:0 14px 34px rgba(10,23,51,.14);font-size:12px;font-weight:750}.toast.error{border-color:#f0caca;color:var(--red)}
    @media(max-width:1300px){.shell{grid-template-columns:318px minmax(0,1fr)}.auth-grid{grid-template-columns:150px 1fr 1fr}.workspace{grid-template-columns:1fr}.code pre{max-height:520px}.topbar{position:static}}
    @media(max-width:860px){body{min-width:760px}.workspace{padding:16px}.topbar{padding:12px 16px}.auth-grid{grid-template-columns:1fr 1fr}.grid{grid-template-columns:1fr}}
  </style>
</head>
<body>
  <div class="shell">
    <aside class="sidebar">
      <header class="brand"><div class="brand-mark">API</div><div><h1>BUC API Console</h1><p>Real requests only. No generated payloads.</p></div></header>
      <div class="search"><input id="endpointSearch" type="search" autocomplete="off" placeholder="Search endpoints"></div>
      <nav id="endpointList" class="endpoint-list" aria-label="API endpoints"></nav>
    </aside>
    <main class="main">
      <section class="topbar" aria-label="Authentication settings">
        <form id="authForm" class="auth-grid" autocomplete="off">
          <div class="field"><label for="authRole">Account</label><select id="authRole"><option value="admin">Admin</option><option value="student">Student</option></select></div>
          <div class="field"><label for="supabaseUrl">SUPABASE_URL</label><input id="supabaseUrl" type="url" autocomplete="off"></div>
          <div class="field"><label for="publishableKey">SUPABASE_PUBLISHABLE_KEY</label><input id="publishableKey" type="password" autocomplete="off"></div>
          <div class="field"><label for="authEmail">EMAIL</label><input id="authEmail" type="email" autocomplete="username"></div>
          <div class="field"><label for="authPassword">PASSWORD</label><input id="authPassword" type="password" autocomplete="current-password"></div>
          <button class="button primary" type="submit">Sign in</button>
          <button class="button" id="clearAuth" type="button">Clear</button>
        </form>
        <div class="auth-grid" style="margin-top:9px;grid-template-columns:minmax(320px,1fr) auto">
          <div class="field"><label for="studentBearerToken">STUDENT_BEARER_TOKEN</label><input id="studentBearerToken" type="password" autocomplete="off" placeholder="Optional: paste an existing student token"></div>
          <button class="button" id="saveToken" type="button">Save token</button>
        </div>
        <div id="authStatus" class="auth-status">Settings are stored in this browser. Passwords are never saved.</div>
      </section>
      <section class="workspace">
        <article class="panel">
          <div class="panel-head"><div class="route"><div class="route-line"><span id="methodBadge" class="method get">GET</span><h2 id="routePath">/health</h2></div><p id="routeSummary">Select an endpoint to prepare a real request.</p></div></div>
          <div class="panel-body">
            <h3 class="section-title">Request</h3>
            <div id="requestFields" class="grid"></div>
            <div id="bodyBlock" class="field wide hidden" style="margin-top:12px"><label for="requestBody">JSON body</label><textarea id="requestBody" spellcheck="false" placeholder="Paste a real JSON body"></textarea></div>
            <div id="idempotencyBlock" class="field wide hidden" style="margin-top:12px"><label for="idempotencyKey">Idempotency-Key</label><input id="idempotencyKey" autocomplete="off"><p class="write-note">Mutation requests are real. Use a fresh idempotency key for every intended write.</p></div>
            <div class="request-actions"><button id="sendRequest" class="button primary" type="button">Send request</button><button id="copyUrl" class="button" type="button">Copy URL</button></div>
            <div id="requestUrl" class="request-url">/api/health</div>
          </div>
        </article>
        <aside class="panel">
          <div class="panel-head"><div><h3 class="section-title" style="margin:0 0 6px">Response</h3><div class="response-meta"><span id="statusPill" class="pill">No request sent</span><span id="timePill" class="pill">0ms</span><span id="authPill" class="pill">Public</span></div></div><button id="copyResponse" class="button" type="button">Copy response</button></div>
          <div class="panel-body"><div class="code"><pre id="responseBody">Press Send request to see the live API response.</pre></div></div>
        </aside>
      </section>
    </main>
  </div>
  <div id="toast" class="toast hidden" role="status"></div>
  <script>window.__apiDocsConfig=${configJson};</script>
  <script>
  (function(){
    var config=window.__apiDocsConfig||{};
    var settingsKey='buc-api-docs-settings';
    var state={api:null,endpoints:[],groups:{},selected:null,form:{},response:null,tokens:{admin:'',student:''},emails:{admin:'',student:''}};
    function q(selector,root){return (root||document).querySelector(selector)}
    function qa(selector,root){return Array.prototype.slice.call((root||document).querySelectorAll(selector))}
    function escapeHtml(value){return String(value==null?'':value).replace(/[&<>"']/g,function(char){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]})}
    function pretty(value){try{return JSON.stringify(typeof value==='string'?JSON.parse(value):value,null,2)}catch(error){return String(value==null?'':value)}}
    function methodClass(method){return 'method '+String(method||'GET').toLowerCase()}
    function toast(message,isError){var node=q('#toast');node.textContent=message;node.className='toast'+(isError?' error':'');clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(function(){node.className='toast hidden'},3200)}
    function readSettings(){try{return JSON.parse(localStorage.getItem(settingsKey)||'{}')||{}}catch(error){return {}}}
    function persistSettings(){var role=q('#authRole').value;try{localStorage.setItem(settingsKey,JSON.stringify({supabaseUrl:q('#supabaseUrl').value.trim(),publishableKey:q('#publishableKey').value.trim(),adminEmail:state.emails.admin||'',studentEmail:state.emails.student||'',studentBearerToken:q('#studentBearerToken').value.trim()}))}catch(error){}hydrateEmail(role)}
    function setAuthStatus(message,type){var node=q('#authStatus');node.textContent=message;node.className='auth-status '+(type||'')}
    function authRoleFor(endpoint){return endpoint&&endpoint.path.indexOf('/v1/student/')===0?'student':endpoint&&endpoint.auth?'admin':'public'}
    function tokenFor(endpoint){var role=authRoleFor(endpoint);return role==='public'?'':state.tokens[role]||''}
    function hydrateEmail(role){var saved=readSettings();q('#authEmail').value=role==='student'?(saved.studentEmail||state.emails.student||''):(saved.adminEmail||state.emails.admin||'')}
    function hydrateAuth(){var saved=readSettings();q('#supabaseUrl').value=saved.supabaseUrl||config.supabaseUrl||'';q('#publishableKey').value=saved.publishableKey||config.supabasePublishableKey||'';q('#studentBearerToken').value=saved.studentBearerToken||'';if(saved.studentBearerToken)state.tokens.student=saved.studentBearerToken;state.emails.admin=saved.adminEmail||'';state.emails.student=saved.studentEmail||'';hydrateEmail(q('#authRole').value)}
    async function signIn(event){event.preventDefault();var role=q('#authRole').value;var email=q('#authEmail').value.trim();var password=q('#authPassword').value;var supabaseUrl=q('#supabaseUrl').value.trim();var publishableKey=q('#publishableKey').value.trim();if(!supabaseUrl||!publishableKey){setAuthStatus('Enter SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY.','error');return}if(!email||!password){setAuthStatus('Enter email and password.','error');return}setAuthStatus('Signing in...');try{var response=await fetch(supabaseUrl.replace(/\/$/,'')+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:publishableKey,'Content-Type':'application/json'},body:JSON.stringify({email:email,password:password})});var payload=await response.json().catch(function(){return {}});if(!response.ok||!payload.access_token)throw new Error(payload.error_description||payload.msg||'Supabase sign-in failed.');state.tokens[role]=payload.access_token;state.emails[role]=email;q('#authPassword').value='';persistSettings();setAuthStatus((role==='student'?'Student':'Admin')+' token ready. Choose an endpoint or use the auto-loaded response.','ok');renderSelected();autoRequestSelected()}catch(error){q('#authPassword').value='';setAuthStatus(error.message||'Sign-in failed.','error')}}
    function saveStudentToken(){var token=q('#studentBearerToken').value.trim();if(!token){setAuthStatus('Paste STUDENT_BEARER_TOKEN first.','error');return}state.tokens.student=token;state.emails.student=q('#authEmail').value.trim()||state.emails.student||'';persistSettings();setAuthStatus('Student bearer token saved for this browser.','ok');renderSelected();autoRequestSelected()}
    function clearAuth(){var role=q('#authRole').value;state.tokens[role]='';state.emails[role]='';q('#authEmail').value='';q('#authPassword').value='';if(role==='student')q('#studentBearerToken').value='';persistSettings();setAuthStatus('Cleared '+role+' token from this browser.');renderSelected()}
    function normalize(openapi){var endpoints=[];Object.keys(openapi.paths||{}).forEach(function(path){var pathItem=openapi.paths[path]||{};Object.keys(pathItem).forEach(function(method){if(!/^(get|post|put|patch|delete)$/i.test(method))return;var operation=pathItem[method]||{};endpoints.push({id:method.toUpperCase()+' '+path,method:method.toUpperCase(),path:path,group:(operation.tags&&operation.tags[0])||'System',summary:operation.summary||operation.description||'Untitled endpoint',description:operation.description||operation.summary||'',auth:Array.isArray(operation.security)&&operation.security.length>0,parameters:operation.parameters||[],requestBody:operation.requestBody||null,responses:operation.responses||{}})})});return endpoints.sort(function(a,b){return (a.group+a.path+a.method).localeCompare(b.group+b.path+b.method)})}
    function renderNavigation(){var search=q('#endpointSearch').value.trim().toLowerCase();var host=q('#endpointList');var groups={};state.endpoints.forEach(function(endpoint){var hay=(endpoint.method+' '+endpoint.path+' '+endpoint.summary+' '+endpoint.group).toLowerCase();if(search&&hay.indexOf(search)<0)return;if(!groups[endpoint.group])groups[endpoint.group]=[];groups[endpoint.group].push(endpoint)});host.innerHTML='';Object.keys(groups).sort().forEach(function(group){var title=document.createElement('div');title.className='group-title';title.textContent=group;host.appendChild(title);groups[group].forEach(function(endpoint){var button=document.createElement('button');button.type='button';button.className='endpoint';button.dataset.endpoint=endpoint.id;button.setAttribute('aria-current',state.selected&&state.selected.id===endpoint.id?'true':'false');button.innerHTML='<span class="'+methodClass(endpoint.method)+'">'+escapeHtml(endpoint.method)+'</span><span><span class="endpoint-path">'+escapeHtml(endpoint.path)+'</span><span class="endpoint-summary">'+escapeHtml(endpoint.summary)+'</span></span>';host.appendChild(button)})});if(!host.children.length)host.innerHTML='<p class="empty-note">No endpoints found.</p>'}
    function selectEndpoint(id){state.selected=state.endpoints.filter(function(endpoint){return endpoint.id===id})[0]||state.endpoints[0]||null;state.response=null;state.form={};(state.selected&&state.selected.parameters||[]).forEach(function(parameter){if(parameter.in==='path'||parameter.in==='query')state.form[parameter.in+':'+parameter.name]=''});renderNavigation();renderSelected();autoRequestSelected()}
    function inputFor(parameter){var key=parameter.in+':'+parameter.name;var id='field-'+key.replace(/[^a-z0-9]+/gi,'-');var required=Boolean(parameter.required);var label=escapeHtml(parameter.name)+(required?' *':'')+' <span class="muted">'+escapeHtml(parameter.in)+'</span>';var value=state.form[key]||'';var schema=parameter.schema||{};var control;if(schema.enum&&schema.enum.length){control='<select id="'+id+'" data-key="'+escapeHtml(key)+'"><option value=""></option>'+schema.enum.map(function(item){return '<option value="'+escapeHtml(item)+'" '+(String(item)===String(value)?'selected':'')+'>'+escapeHtml(item)+'</option>'}).join('')+'</select>'}else{control='<input id="'+id+'" data-key="'+escapeHtml(key)+'" value="'+escapeHtml(value)+'" autocomplete="off" '+(schema.format==='uuid'?'placeholder="real UUID"':'')+'>'}return '<div class="field"><label for="'+id+'">'+label+'</label>'+control+'</div>'}
    function hasBody(endpoint){return Boolean(endpoint&&endpoint.requestBody&&endpoint.requestBody.content)}
    function hasRequiredBody(endpoint){return Boolean(endpoint&&endpoint.requestBody&&endpoint.requestBody.required)}
    function updateFormFromDom(){qa('[data-key]').forEach(function(field){state.form[field.dataset.key]=field.value});var key=q('#idempotencyKey');if(key)state.idempotencyKey=key.value.trim();var body=q('#requestBody');if(body)state.body=body.value}
    function buildUrl(){updateFormFromDom();var endpoint=state.selected;if(!endpoint)return '/api';var path=endpoint.path;var query=new URLSearchParams();(endpoint.parameters||[]).forEach(function(parameter){var value=state.form[parameter.in+':'+parameter.name]||'';if(parameter.in==='path')path=path.replace('{'+parameter.name+'}',encodeURIComponent(value));if(parameter.in==='query'&&value.trim())query.set(parameter.name,value.trim())});return '/api'+path+(query.toString()?'?'+query.toString():'')}
    function missingFields(){updateFormFromDom();var missing=[];(state.selected.parameters||[]).forEach(function(parameter){if(parameter.required&&!String(state.form[parameter.in+':'+parameter.name]||'').trim())missing.push(parameter.name)});if(hasRequiredBody(state.selected)&&!String(state.body||'').trim())missing.push('JSON body');if(state.selected.method!=='GET'&&!String(state.idempotencyKey||'').trim())missing.push('Idempotency-Key');return missing}
    function canAutoRequest(endpoint){if(!endpoint||endpoint.method!=='GET')return false;if((endpoint.parameters||[]).some(function(parameter){return parameter.in==='path'&&parameter.required}))return false;if(endpoint.auth&&!tokenFor(endpoint))return false;return missingFields().length===0}
    function autoRequestSelected(){window.clearTimeout(window.__apiAutoRequestTimer);window.__apiAutoRequestTimer=window.setTimeout(function(){if(canAutoRequest(state.selected))sendRequest({automatic:true})},180)}
    function renderSelected(){var endpoint=state.selected;if(!endpoint)return;q('#methodBadge').className=methodClass(endpoint.method);q('#methodBadge').textContent=endpoint.method;q('#routePath').textContent=endpoint.path;q('#routeSummary').textContent=endpoint.summary||endpoint.description||'';q('#authPill').textContent=endpoint.auth?(authRoleFor(endpoint)==='student'?'Student token':'Admin token'):'Public';q('#authPill').className='pill '+(endpoint.auth&&tokenFor(endpoint)?'ok':'');var fields=(endpoint.parameters||[]).filter(function(parameter){return parameter.in==='path'||parameter.in==='query'}).map(inputFor).join('');q('#requestFields').innerHTML=fields||'<p class="empty-note wide">This endpoint has no path or query fields.</p>';q('#bodyBlock').className='field wide '+(hasBody(endpoint)?'':'hidden');q('#idempotencyBlock').className='field wide '+(endpoint.method==='GET'?'hidden':'');if(endpoint.method!=='GET'&&!q('#idempotencyKey').value)q('#idempotencyKey').value='api-docs-'+Date.now()+'-'+Math.random().toString(16).slice(2);q('#requestBody').value=state.body||'';q('#requestUrl').textContent=buildUrl();q('#responseBody').textContent=state.response?state.response.body:'Press Send request to see the live API response.';q('#statusPill').textContent=state.response?'HTTP '+state.response.status:'No request sent';q('#statusPill').className='pill '+(state.response?(state.response.ok?'ok':'error'):'');q('#timePill').textContent=state.response?state.response.time+'ms':'0ms'}
    async function copyText(text,message){try{await navigator.clipboard.writeText(text);toast(message||'Copied.')}catch(error){toast('Copy is unavailable in this browser.',true)}}
    async function sendRequest(options){var automatic=Boolean(options&&options.automatic);var missing=missingFields();if(missing.length){if(!automatic)toast('Missing: '+missing.join(', '),true);return}var endpoint=state.selected;var requestToken=tokenFor(endpoint);if(endpoint.auth&&!requestToken){if(!automatic)toast('This endpoint needs a '+(authRoleFor(endpoint)==='student'?'student':'admin')+' token.',true);return}var headers={Accept:'application/json'};if(requestToken)headers.Authorization='Bearer '+requestToken;if(endpoint.method!=='GET')headers['Idempotency-Key']=state.idempotencyKey;if(hasBody(endpoint)){var bodyText=String(state.body||'').trim();if(bodyText){try{JSON.parse(bodyText)}catch(error){toast('JSON body is invalid.',true);return}headers['Content-Type']='application/json'}}var options={method:endpoint.method,headers:headers};if(hasBody(endpoint)&&String(state.body||'').trim())options.body=String(state.body).trim();var started=performance.now();q('#statusPill').textContent='Loading';q('#responseBody').textContent='Sending request...';try{var response=await fetch(buildUrl(),options);var text=await response.text();state.response={status:response.status,ok:response.ok,time:Math.round(performance.now()-started),body:pretty(text)};renderSelected();if(!response.ok&&!automatic)toast('Request returned HTTP '+response.status+'.',true)}catch(error){state.response={status:0,ok:false,time:Math.round(performance.now()-started),body:'Request could not be sent. Check server connectivity.'};renderSelected();if(!automatic)toast('Request could not be sent.',true)}}
    q('#authForm').addEventListener('submit',signIn);q('#authRole').addEventListener('change',function(){hydrateEmail(q('#authRole').value);setAuthStatus('Loaded '+q('#authRole').value+' settings.')});q('#saveToken').addEventListener('click',saveStudentToken);q('#clearAuth').addEventListener('click',clearAuth);q('#endpointSearch').addEventListener('input',renderNavigation);q('#endpointList').addEventListener('click',function(event){var button=event.target.closest('[data-endpoint]');if(button)selectEndpoint(button.dataset.endpoint)});q('#sendRequest').addEventListener('click',function(){sendRequest({automatic:false})});q('#copyUrl').addEventListener('click',function(){copyText(buildUrl(),'Request URL copied.')});q('#copyResponse').addEventListener('click',function(){copyText(q('#responseBody').textContent,'Response copied.')});document.addEventListener('input',function(event){if(event.target.matches('[data-key],#requestBody,#idempotencyKey')){updateFormFromDom();q('#requestUrl').textContent=buildUrl()}});
    hydrateAuth();fetch('/openapi.json',{headers:{Accept:'application/json'}}).then(function(response){if(!response.ok)throw new Error('openapi');return response.json()}).then(function(openapi){state.api=openapi;state.endpoints=normalize(openapi);renderNavigation();var preferred=state.endpoints.filter(function(endpoint){return endpoint.path==='/health'&&endpoint.method==='GET'})[0]||state.endpoints[0];selectEndpoint(preferred&&preferred.id)}).catch(function(){q('#responseBody').textContent='Unable to load /openapi.json from this API server.';toast('Unable to load the API contract.',true)});
  })();
  </script>
</body>
</html>`;
}
