import type { IncomingMessage, ServerResponse } from "node:http";
import { createCorrelationId } from "./middleware/correlation";
import { createRequestId } from "./middleware/request-id";
import { methodNotAllowedResponse, notFoundResponse } from "./middleware/json-response";
import { safeErrorResponse } from "./middleware/error-response";
import { handleAdminM2Read, handleAdminOverview, isAdminM2ReadPath } from "./routes/admin.routes";
import { handleAdminM2Write, isAdminM2WritePath } from "./routes/admin-m2-write.routes";
import { handleHealth, handleReady } from "./routes/health.routes";
import type { HttpAppDependencies, HttpMethod, HttpRequestContext } from "./http-types";
function normalizeMethod(method: string | undefined): HttpMethod { return (method ?? "GET").toUpperCase() as HttpMethod; }
export function createHttpApp(dependencies: HttpAppDependencies) { return async function handleHttpRequest(request: IncomingMessage, response: ServerResponse): Promise<void> { const correlationId = createCorrelationId(typeof request.headers["x-correlation-id"] === "string" ? request.headers["x-correlation-id"] : undefined); const context: HttpRequestContext = { method: normalizeMethod(request.method), url: request.url ?? "/", headers: Object.fromEntries(Object.entries(request.headers).map(([key, value]) => [key.toLowerCase(), Array.isArray(value) ? value[0] : value])), correlationId, requestId: createRequestId() }; let result; try { const path = context.url.split("?")[0]; if (path === "/health") result = context.method === "GET" ? handleHealth(context) : methodNotAllowedResponse(correlationId); else if (path === "/ready") result = context.method === "GET" ? handleReady(context, dependencies.admin) : methodNotAllowedResponse(correlationId); else if (path === "/v1/admin/overview") result = context.method === "GET" ? await handleAdminOverview(context, dependencies.admin) : methodNotAllowedResponse(correlationId); else if (context.method === "GET" && isAdminM2ReadPath(path)) result = (await handleAdminM2Read(context, dependencies.admin)) ?? notFoundResponse(correlationId); else if (isAdminM2WritePath(path)) result = await handleAdminM2Write(request, context, dependencies.admin, dependencies.adminHttpContextResolver); else if (isAdminM2ReadPath(path)) result = methodNotAllowedResponse(correlationId); else result = notFoundResponse(correlationId); } catch (error) { result = safeErrorResponse(correlationId, error); } if (!result) result = notFoundResponse(correlationId); response.statusCode = result.statusCode; for (const [name, value] of Object.entries(result.headers ?? {})) response.setHeader(name, value); if (!result.headers?.["x-correlation-id"]) response.setHeader("x-correlation-id", correlationId); response.end(JSON.stringify(result.body)); }; }
