import { studentCoursePaths, studentCourseSchemas } from "./openapi-student-courses";
import { academicCataloguePaths, academicCatalogueSchemas, catalogueReadResponse } from "./openapi-academic-catalogue";
import type { HttpJsonResponse } from "./http-types";
import { createApiDocsHtml } from "./api-docs-template";
import { m2bPaths, m2bSchemas } from './openapi-m2b';

const json = (statusCode: number, body: Readonly<Record<string, unknown>>, headers?: Readonly<Record<string, string>>): HttpJsonResponse => ({ statusCode, body, headers });

const id = (name: string, required = true) => ({ name, in: "path", required, schema: { type: "string", format: "uuid" } });
const bearer = [{ AdminBearerAuth: [] }];
const writeHeaders = [
  { name: "Authorization", in: "header", required: true, schema: { type: "string" }, description: "Admin bearer access token. Optional console overrides are stored only in this browser localStorage." },
  { name: "Idempotency-Key", in: "header", required: true, schema: { type: "string", minLength: 1, maxLength: 128 }, description: "Required only for POST/PATCH administrative mutation commands. Do not send this header on GET read/list operations." },
];
const reason = { type: "string", minLength: 1, maxLength: 500 };
const version = { type: "integer", minimum: 1 };
const body = (properties: Record<string, unknown>, required: string[]) => ({ required: true, content: { "application/json": { schema: { type: "object", additionalProperties: false, properties, required } } } });
const response = (description: string) => ({ description, content: { "application/json": { schema: { type: "object" } } } });
const read = (summary: string) => ({ summary, description: "Requires a verified admin identity and persisted administrative permission. A student bearer does not grant admin access. Missing bearer is rejected before route/query validation; a syntactically supplied bearer with an invalid route/query can return 400 before identity resolution.", security: bearer, responses: { "200": response("Successful response"), "400": response("Invalid route or query"), "404": response("Resource not found in authorized scope"), "503": response("Read source unavailable"), "401": response("Authentication required"), "403": response("Permission denied") } });
const write = (summary: string, requestBody: unknown) => ({ summary, security: bearer, requestBody, responses: { "200": response("Command accepted or replayed"), "201": response("Command applied"), "400": response("Invalid command"), "401": response("Authentication required"), "403": response("Permission denied"), "409": response("Version or idempotency conflict") } });
const studentReadSchemas = {
  AdminStudentReadItem: { type: "object", additionalProperties: false, description: "Authorized administrative student read. Full name is private admin data; email and student code are masked. Phone, device, session, activity, and access facts remain null or empty until an approved source exists.", properties: { id: { type: "string", format: "uuid" }, platform: { type: "object" }, displayName: { type: ["string", "null"] }, emailMasked: { type: ["string", "null"] }, studentIdMasked: { type: ["string", "null"] }, phoneMasked: { type: ["null"] }, academicInstitution: { type: ["string", "null"], description: "Academic institution such as BUC or Delta; never a commercial brand." }, academicLevel: { type: ["string", "null"] }, academicLevelId: { type: ["string", "null"], format: "uuid" }, academicSemester: { type: ["string", "null"] }, program: { type: ["string", "null"] }, expectedGraduationDate: { type: ["string", "null"], format: "date" }, status: { type: "string", enum: ["active", "disabled"] }, activeDeviceCount: { type: ["null"] }, activeSessionCount: { type: ["null"] }, lastSeenAt: { type: ["null"] } } },
  AdminStudentsListResponse: { type: "object", properties: { ok: { const: true }, correlationId: { type: "string" }, data: { type: "object", properties: { data: { type: "array", items: { $ref: "#/components/schemas/AdminStudentReadItem" } }, pagination: { type: "object" } } } } },
  AdminStudentDetailResponse: { type: "object", properties: { ok: { const: true }, correlationId: { type: "string" }, data: { allOf: [{ $ref: "#/components/schemas/AdminStudentReadItem" }, { type: "object", properties: { access: { type: "object", description: "Unavailable source fields are null." }, devices: { type: "array", maxItems: 0 }, sessions: { type: "array", maxItems: 0 } } }] } } },
} as const;
const studentsListResponse = { description: "Read-only student list with private fields minimized.", content: { "application/json": { schema: { $ref: "#/components/schemas/AdminStudentsListResponse" } } } };
const studentDetailResponse = { description: "Read-only student detail with private fields minimized.", content: { "application/json": { schema: { $ref: "#/components/schemas/AdminStudentDetailResponse" } } } };

export const openApiDocument = {
  openapi: "3.1.0",
  info: { title: "E-Learning Backend API", version: "1.0.0-mvp-a", description: "Course/Lesson visibility and administrative metadata API. Commercial brands: Medway, Elite, Nexus. Academic institutions: BUC, Delta. Student and admin bearers have separate persisted authorization boundaries. The private app schema is not exposed through Supabase Data API." },
  servers: [{ url: ".", description: "Current API base, including its mounted prefix" }],
  tags: [{ name: "Student courses" }, { name: "System" }, { name: "Admin overview" }, { name: "Students" }, { name: "Subscriptions" }, { name: "Academic catalogue" }, { name: "Instructors" }, { name: "Brand teaching" }],
  components: { schemas: { ...studentCourseSchemas, ...m2bSchemas, ...academicCatalogueSchemas, ...studentReadSchemas }, securitySchemes: { AdminBearerAuth: { type: "http", scheme: "bearer", bearerFormat: "JWT", description: "Real admin access token with persisted admin permission." }, StudentBearerAuth: { type: "http", scheme: "bearer", bearerFormat: "JWT", description: "Real student access token with active student membership and placement. An identity with an admin profile is rejected." } } },
  paths: {
    ...studentCoursePaths,
    ...m2bPaths,
    ...academicCataloguePaths,
    "/openapi.json": { get: { tags: ["System"], operationId: "getOpenApi", summary: "Read the API contract", security: [], responses: { "200": response("OpenAPI JSON document") } } },
    "/docs": { get: { tags: ["System"], operationId: "getApiDocs", summary: "Open the operational API console", security: [], responses: { "200": { description: "API documentation HTML", content: { "text/html": { schema: { type: "string" } } } } } } },
    "/health": { get: { tags: ["System"], operationId: "getHealth", summary: "Liveness probe", security: [], description: "Public liveness endpoint. It never requires Authorization or Idempotency-Key.", responses: { "200": response("Service is alive") } } },
    "/ready": { get: { tags: ["System"], operationId: "getReady", summary: "Readiness probe", security: [], description: "Public readiness endpoint. It never requires Authorization or Idempotency-Key.", responses: { "200": response("Service is ready"), "503": response("A required dependency is unavailable") } } },
    "/v1/health": { get: { tags: ["System"], operationId: "getHealthV1Compatibility", summary: "Liveness probe (compatibility path)", deprecated: true, security: [], description: "Compatibility alias for /health used by generic API test runners. Public; never requires Authorization or Idempotency-Key.", responses: { "200": response("Service is alive") } } },
    "/v1/ready": { get: { tags: ["System"], operationId: "getReadyV1Compatibility", summary: "Readiness probe (compatibility path)", deprecated: true, security: [], description: "Compatibility alias for /ready used by generic API test runners. Public; never requires Authorization or Idempotency-Key.", responses: { "200": response("Service is ready"), "503": response("A required dependency is unavailable") } } },
    "/v1/admin/subscription-plans": { get: { tags: ["Subscriptions"], parameters: [{ name: "brand", in: "query", required: true, schema: { type: "string", enum: ["medway", "elite", "nexus"] } }], ...read("List supported manual/offline subscription plans") } },
    "/v1/admin/subscription-students": { get: { tags: ["Subscriptions"], parameters: [{ name: "brand", in: "query", required: true, schema: { type: "string", enum: ["medway", "elite", "nexus"] } }], ...read("List real student profiles eligible for manual order selection") } },
    "/v1/admin/subscription-courses": { get: { tags: ["Subscriptions"], parameters: [{ name: "brand", in: "query", required: true, schema: { type: "string", enum: ["medway", "elite", "nexus"] } }, { name: "studentId", in: "query", required: true, schema: { type: "string", format: "uuid" } }], ...read("List published subjects matching the selected student's academic placement") } },
    "/v1/admin/subscription-orders": {
      get: { tags: ["Subscriptions"], parameters: [{ name: "brand", in: "query", required: true, schema: { type: "string", enum: ["medway", "elite", "nexus"] } }], ...read("List manual/offline subscription payment requests") },
      post: { tags: ["Subscriptions"], parameters: [{ name: "brand", in: "query", required: true, schema: { type: "string", enum: ["medway", "elite", "nexus"] } }, ...writeHeaders], ...write("Create a pending manual subscription request; group size and price are metadata and enrollment is scoped to the selected student", body({ studentProfileId: { type: "string", format: "uuid" }, planCode: { type: "string", enum: ["single_subject", "promo_4_subjects_individual_5000", "group_3_friends_4700_each", "group_5_friends_4500_each"] }, courseIds: { type: "array", minItems: 1, items: { type: "string", format: "uuid" } }, amountPaid: { type: "number", minimum: 0 }, currency: { const: "EGP" }, externalPaymentReference: { type: ["string", "null"], maxLength: 240 }, evidenceNote: { type: ["string", "null"], maxLength: 2000 }, adminNotes: { type: ["string", "null"], maxLength: 4000 }, reason }, ["studentProfileId", "planCode", "courseIds", "amountPaid", "currency", "reason"])) },
    },
    "/v1/admin/subscription-orders/{orderId}/approve": { post: { tags: ["Subscriptions"], parameters: [id("orderId"), { name: "brand", in: "query", required: true, schema: { type: "string", enum: ["medway", "elite", "nexus"] } }, ...writeHeaders], ...write("Approve a pending order and activate its eligible course enrollments", body({ expectedVersion: version, reason }, ["expectedVersion", "reason"])) } },
    "/v1/admin/subscription-orders/{orderId}/reject": { post: { tags: ["Subscriptions"], parameters: [id("orderId"), { name: "brand", in: "query", required: true, schema: { type: "string", enum: ["medway", "elite", "nexus"] } }, ...writeHeaders], ...write("Reject a pending order without creating enrollments", body({ expectedVersion: version, reason, rejectionReason: { type: "string", minLength: 1, maxLength: 1000 } }, ["expectedVersion", "reason", "rejectionReason"])) } },
    "/v1/admin/overview": { get: { tags: ["Admin overview"], parameters: [{ name: "brand", in: "query", required: true, schema: { type: "string", enum: ["medway", "elite", "nexus"] }, description: "Commercial brand whose overview is requested." }], ...read("Read the administrative overview") } },
    "/v1/admin/students": { post: { tags: ["Students"], parameters: [{ name: "brand", in: "query", required: true, schema: { type: "string", enum: ["medway", "elite", "nexus"] } }, ...writeHeaders], ...write("Create a student Auth account and academic profile using server-side Auth administration", body({ fullName: { type: "string", minLength: 2, maxLength: 160 }, email: { type: "string", format: "email" }, password: { type: "string", minLength: 12 }, studentCode: { type: "string" }, academicInstitutionId: { type: "string", format: "uuid" }, academicLevelId: { type: "string", format: "uuid" }, academicSemesterId: { type: "string", format: "uuid" }, reason }, ["fullName", "email", "password", "academicInstitutionId", "academicLevelId", "academicSemesterId", "reason"])) }, get: { tags: ["Students"], parameters: [{ name: "brand", in: "query", required: false, schema: { type: "string", enum: ["all", "medway", "elite", "nexus"] }, description: "Commercial brand scope only; BUC and Delta are academic institutions, not brands." }, { name: "search", in: "query", required: false, schema: { type: "string", maxLength: 120 }, description: "Matches opaque student-profile ID, or the private name, email, or student code without returning raw email/code." }, { name: "academicLevel", in: "query", required: false, schema: { type: "string", format: "uuid" }, description: "Academic level ID from the private academic placement source." }, { name: "status", in: "query", required: false, schema: { type: "string", enum: ["active", "pending", "disabled", "suspended"] } }, { name: "page", in: "query", required: false, schema: { type: "integer", minimum: 1 } }, { name: "pageSize", in: "query", required: false, schema: { type: "integer", minimum: 1, maximum: 100 } }], ...read("List read-only student profile records across commercial brands"), responses: { ...read("").responses, "200": studentsListResponse } } },
    "/v1/admin/students/{studentId}": { get: { tags: ["Students"], parameters: [id("studentId"), { name: "brand", in: "query", required: false, schema: { type: "string", enum: ["all", "medway", "elite", "nexus"] } }], ...read("Read one student profile without exposing auth or service-role data"), responses: { ...read("").responses, "200": studentDetailResponse } } },
    "/v1/admin/curriculum/levels": { get: { tags: ["Academic catalogue"], operationId: "listAcademicLevels", ...read("List academic levels"), responses: { ...read("").responses, "200": catalogueReadResponse("AcademicLevel") } } },
    "/v1/admin/curriculum/semesters": { get: { tags: ["Academic catalogue"], operationId: "listAcademicSemesters", parameters: [{ name: "levelId", in: "query", required: false, schema: { type: "string", format: "uuid" } }], ...read("List semesters; optionally filter by academic level"), responses: { ...read("").responses, "200": catalogueReadResponse("AcademicSemester") } } },
    "/v1/admin/curriculum/modules": { get: { tags: ["Academic catalogue"], parameters: [{ name: "semesterId", in: "query", required: false, schema: { type: "string", format: "uuid" } }], ...read("List modules; optionally filter by semester"), responses: { ...read("").responses, "200": catalogueReadResponse("AcademicModule") } } },
    "/v1/admin/curriculum/modules/{moduleId}": { get: { tags: ["Academic catalogue"], parameters: [id("moduleId")], ...read("Read a module with its ordered chapter outline"), responses: { ...read("").responses, "200": catalogueReadResponse("AcademicModule", false) } } },
    "/v1/admin/instructors": {
      get: { tags: ["Instructors"], operationId: "listGlobalInstructors", ...read("List global instructor identities"), responses: { ...read("").responses, "200": catalogueReadResponse("Instructor") } },
      post: { tags: ["Instructors"], parameters: writeHeaders, ...write("Create a global instructor identity", body({ code: { type: "string" }, displayName: { type: "string" }, reason }, ["code", "displayName", "reason"])) },
    },
    "/v1/admin/instructors/{instructorId}": {
      get: { tags: ["Instructors"], parameters: [id("instructorId")], ...read("Read one global instructor"), responses: { ...read("").responses, "200": catalogueReadResponse("Instructor", false) } },
      patch: { tags: ["Instructors"], parameters: [id("instructorId"), ...writeHeaders], ...write("Update global instructor identity", body({ code: { type: "string" }, displayName: { type: "string" }, expectedVersion: version, reason }, ["reason"])) },
    },
    "/v1/admin/instructors/{instructorId}/status": { patch: { tags: ["Instructors"], parameters: [id("instructorId"), ...writeHeaders], ...write("Change global instructor lifecycle", body({ status: { type: "string", enum: ["active", "inactive", "archived"] }, expectedVersion: version, reason }, ["status", "reason"])) } },
    "/v1/admin/instructors/{instructorId}/brands": { get: { tags: ["Instructors"], parameters: [id("instructorId")], ...read("List brand assignments for one instructor") } },
    "/v1/admin/brands/{brandId}/instructors": {
      get: { tags: ["Brand teaching"], parameters: [id("brandId")], ...read("List instructors assigned to one brand") },
      post: { tags: ["Brand teaching"], parameters: [id("brandId"), ...writeHeaders], ...write("Assign an instructor to a brand", body({ instructorId: { type: "string", format: "uuid" }, reason }, ["instructorId", "reason"])) },
    },
    "/v1/admin/brands/{brandId}/instructors/{instructorId}": { get: { tags: ["Brand teaching"], operationId: "getBrandInstructor", parameters: [id("brandId"), id("instructorId")], ...read("Read an instructor brand assignment"), responses: { ...read("").responses, "200": catalogueReadResponse("InstructorBrandAssignment", false) } } },
    "/v1/admin/brands/{brandId}/instructors/{instructorId}/status": { patch: { tags: ["Brand teaching"], parameters: [id("brandId"), id("instructorId"), ...writeHeaders], ...write("Change an instructor brand assignment", body({ status: { type: "string", enum: ["active", "inactive"] }, expectedVersion: version, reason }, ["status", "reason"])) } },
    "/v1/admin/brands/{brandId}/instructors/{instructorId}/courses": { get: { tags: ["Brand teaching"], parameters: [id("brandId"), id("instructorId")], ...read("List a brand instructor's course assignments") } },
    "/v1/admin/brands/{brandId}/courses": {
      get: { tags: ["Brand teaching"], operationId: "listBrandCourses", parameters: [id("brandId"), { name: "academicModuleId", in: "query", schema: { type: "string", format: "uuid" }, description: "Optional linked academic module filter. Cannot be combined with scope." }, { name: "scope", in: "query", schema: { type: "string", enum: ["standalone"] }, description: "Optional standalone course filter. Cannot be combined with academicModuleId." }], ...read("List courses owned by one brand"), responses:{...read("").responses,"200":catalogueReadResponse("CatalogueBrandCourse")} },
      post: { tags: ["Brand teaching"], operationId: "createBrandCourse", parameters: [id("brandId"), ...writeHeaders], ...write("Create a brand course", body({ code: { type: "string" }, title: { type: "string" }, classification: { type: "string", enum: ["academic_module_offering", "standalone"] }, cataloguePresentation: { type: "string", enum: ["module_based", "subject_based"], description: "Commercial packaging mode. Subject-based is used when a first-year offering is sold/displayed as a subject while staying linked to an academic module." }, academicInstitutionId: { type: "string", format: "uuid", description: "Required for creation; must be allowed for the commercial brand and match any linked module." }, academicModuleId: { type: ["string", "null"], format: "uuid" }, reason }, ["code", "title", "classification", "academicInstitutionId", "academicModuleId", "reason"])) },
    },
    "/v1/admin/brands/{brandId}/courses/{courseId}": {
      get: { tags: ["Brand teaching"], parameters: [id("brandId"), id("courseId")], ...read("Read a brand-owned course"), responses:{...read("").responses,"200":catalogueReadResponse("CatalogueBrandCourse",false)} },
      patch: { tags: ["Brand teaching"], parameters: [id("brandId"), id("courseId"), ...writeHeaders], ...write("Update a brand-owned course", body({ title: { type: "string" }, classification: { type: "string", enum: ["academic_module_offering", "standalone"] }, cataloguePresentation: { type: "string", enum: ["module_based", "subject_based"] }, academicInstitutionId: { type: "string", format: "uuid", description: "Required for creation; must be allowed for the commercial brand and match any linked module." }, academicModuleId: { type: ["string", "null"], format: "uuid" }, expectedVersion: version, reason }, ["reason"])) },
    },
    "/v1/admin/brands/{brandId}/courses/{courseId}/status": { patch: { tags: ["Brand teaching"], operationId: "changeBrandCourseStatus", parameters: [id("brandId"), id("courseId"), ...writeHeaders], ...write("Change brand course lifecycle", body({ status: { type: "string", enum: ["draft", "published", "archived"] }, expectedVersion: version, reason }, ["status", "reason"])) } },
    "/v1/admin/brands/{brandId}/courses/{courseId}/instructors": {
      get: { tags: ["Brand teaching"], parameters: [id("brandId"), id("courseId")], ...read("List instructors assigned to a brand course") },
      post: { tags: ["Brand teaching"], parameters: [id("brandId"), id("courseId"), ...writeHeaders], ...write("Assign a brand-approved instructor to a course", body({ instructorId: { type: "string", format: "uuid" }, reason }, ["instructorId", "reason"])) },
    },
    "/v1/admin/brands/{brandId}/courses/{courseId}/instructors/{instructorId}/status": { patch: { tags: ["Brand teaching"], parameters: [id("brandId"), id("courseId"), id("instructorId"), ...writeHeaders], ...write("Change a course instructor assignment", body({ status: { type: "string", enum: ["active", "inactive"] }, expectedVersion: version, reason }, ["status", "reason"])) } },
  },
} as const;

export const openApiResponse = (): HttpJsonResponse => json(200, openApiDocument, { "content-type": "application/json; charset=utf-8", "cache-control": "no-store" });
export const apiDocsResponse = (): HttpJsonResponse => ({ statusCode: 200, body: {}, rawBody: createApiDocsHtml({ supabaseUrl: process.env.SUPABASE_URL?.trim() || "", supabasePublishableKey: process.env.SUPABASE_PUBLISHABLE_KEY?.trim() || "" }), headers: { "content-type": "text/html; charset=utf-8", "cache-control": "no-store" } });
